// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package spec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import "github.com/chai2010/qingcloud-go/config"
import "github.com/chai2010/qingcloud-go/request"

var _ = config.Config{}
var _ = request.Request{}

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type JobServiceProperties struct {
	Zone string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
}

func (m *JobServiceProperties) Reset()                    { *m = JobServiceProperties{} }
func (m *JobServiceProperties) String() string            { return proto.CompactTextString(m) }
func (*JobServiceProperties) ProtoMessage()               {}
func (*JobServiceProperties) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *JobServiceProperties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type DescribeJobsInput struct {
	Jobs    []string `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
	Limit   int32    `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset  int32    `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Status  []string `protobuf:"bytes,4,rep,name=status" json:"status,omitempty"`
	Verbose int32    `protobuf:"varint,5,opt,name=verbose" json:"verbose,omitempty"`
}

func (m *DescribeJobsInput) Reset()                    { *m = DescribeJobsInput{} }
func (m *DescribeJobsInput) String() string            { return proto.CompactTextString(m) }
func (*DescribeJobsInput) ProtoMessage()               {}
func (*DescribeJobsInput) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *DescribeJobsInput) GetJobs() []string {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *DescribeJobsInput) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeJobsInput) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeJobsInput) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeJobsInput) GetVerbose() int32 {
	if m != nil {
		return m.Verbose
	}
	return 0
}

type DescribeJobsOutput struct {
	Action     string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode    int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	JobSet     []*Job `protobuf:"bytes,4,rep,name=job_set,json=jobSet" json:"job_set,omitempty"`
	TotalCount int32  `protobuf:"varint,5,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
}

func (m *DescribeJobsOutput) Reset()                    { *m = DescribeJobsOutput{} }
func (m *DescribeJobsOutput) String() string            { return proto.CompactTextString(m) }
func (*DescribeJobsOutput) ProtoMessage()               {}
func (*DescribeJobsOutput) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *DescribeJobsOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DescribeJobsOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DescribeJobsOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DescribeJobsOutput) GetJobSet() []*Job {
	if m != nil {
		return m.JobSet
	}
	return nil
}

func (m *DescribeJobsOutput) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*JobServiceProperties)(nil), "spec.JobServiceProperties")
	proto.RegisterType((*DescribeJobsInput)(nil), "spec.DescribeJobsInput")
	proto.RegisterType((*DescribeJobsOutput)(nil), "spec.DescribeJobsOutput")
}

type JobServiceInterface interface {
	DescribeJobs(in *DescribeJobsInput) (out *DescribeJobsOutput, err error)
}

type JobService struct {
	Config     *config.Config
	Properties *JobServiceProperties
}

func NewJobService(conf *config.Config, zone string) (p *JobService, err error) {
	return &JobService{
		Config:     conf,
		Properties: &JobServiceProperties{Zone: zone},
	}, nil
}

func (p *JobService) DescribeJobs(in *DescribeJobsInput) (out *DescribeJobsOutput, err error) {
	if in == nil {
		in = &DescribeJobsInput{}
	}
	o := &request.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeJobs",
		RequestMethod: "GET", // GET or POST
	}

	x := &DescribeJobsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DescribeJobsInput) Validate() error {
	return nil
}

func init() { proto.RegisterFile("job.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x6e, 0xf2, 0x30,
	0x10, 0x85, 0x95, 0x1f, 0x08, 0x7f, 0x86, 0x6e, 0x6a, 0x21, 0xea, 0xb2, 0x29, 0xca, 0x0a, 0x75,
	0xc1, 0x82, 0x9e, 0xa0, 0xa2, 0x9b, 0xb2, 0xa1, 0x4a, 0x0f, 0x80, 0xe2, 0x30, 0x54, 0x89, 0x20,
	0x13, 0x79, 0x26, 0x48, 0xed, 0x05, 0x7a, 0x93, 0x9e, 0xb3, 0xb2, 0x63, 0x54, 0x24, 0x76, 0xf3,
	0x9e, 0xc7, 0xe3, 0xcf, 0x6f, 0x20, 0xa9, 0xc8, 0x2c, 0x1a, 0x4b, 0x42, 0xaa, 0xcf, 0x0d, 0x16,
	0xd3, 0x91, 0x7c, 0x36, 0xc8, 0x9d, 0x95, 0x3e, 0xc2, 0x78, 0x4d, 0xe6, 0x1d, 0xed, 0xa9, 0x2c,
	0xf0, 0xcd, 0x52, 0x83, 0x56, 0x4a, 0x64, 0xa5, 0xa0, 0xff, 0x45, 0x35, 0xea, 0x68, 0x16, 0xcd,
	0x93, 0xcc, 0xd7, 0xe9, 0x77, 0x04, 0xb7, 0x2f, 0xc8, 0x85, 0x2d, 0x0d, 0xae, 0xc9, 0xf0, 0x6b,
	0xdd, 0xb4, 0xe2, 0x3a, 0x2b, 0x32, 0xac, 0xa3, 0x59, 0xcf, 0x75, 0xba, 0x5a, 0x8d, 0x61, 0x70,
	0x28, 0x8f, 0xa5, 0xe8, 0x7f, 0xb3, 0x68, 0x3e, 0xc8, 0x3a, 0xa1, 0x26, 0x10, 0xd3, 0x7e, 0xcf,
	0x28, 0xba, 0xe7, 0xed, 0xa0, 0x9c, 0xcf, 0x92, 0x4b, 0xcb, 0xba, 0xef, 0x67, 0x04, 0xa5, 0x34,
	0x0c, 0x4f, 0x68, 0x0d, 0x31, 0xea, 0x81, 0xbf, 0x70, 0x96, 0xe9, 0x4f, 0x04, 0xea, 0x92, 0x64,
	0xd3, 0x8a, 0x43, 0x99, 0x40, 0x9c, 0x17, 0x52, 0x52, 0x1d, 0xb0, 0x83, 0x52, 0xf7, 0xf0, 0xdf,
	0xa2, 0x6c, 0x0b, 0xda, 0x61, 0x20, 0x1a, 0x5a, 0x94, 0x15, 0xed, 0xd0, 0xbd, 0x71, 0x44, 0xe6,
	0xfc, 0x03, 0x3d, 0x54, 0x92, 0x9d, 0xa5, 0x4a, 0x61, 0x58, 0x91, 0xd9, 0x3a, 0x5c, 0x87, 0x35,
	0x5a, 0x26, 0x0b, 0x17, 0xdf, 0x62, 0x4d, 0x26, 0x8b, 0x2b, 0x97, 0x99, 0xa8, 0x07, 0x18, 0x09,
	0x49, 0x7e, 0xd8, 0x16, 0xd4, 0xd6, 0x12, 0x28, 0xc1, 0x5b, 0x2b, 0xe7, 0x2c, 0x37, 0x00, 0x7f,
	0xf1, 0xaa, 0x67, 0xb8, 0xb9, 0xa4, 0x56, 0x77, 0xdd, 0xc4, 0xab, 0x4c, 0xa7, 0xfa, 0xfa, 0xa0,
	0xfb, 0xa2, 0x89, 0xfd, 0xda, 0x9e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x18, 0x37, 0xe5, 0x3a,
	0xd6, 0x01, 0x00, 0x00,
}
