// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mongo.proto

package spec

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import "github.com/chai2010/qingcloud-go/config"
import "github.com/chai2010/qingcloud-go/request"
import request_data_pkg "github.com/chai2010/qingcloud-go/request/data"
import "github.com/chai2010/qingcloud-go/request/errors"

var _ = config.Config{}
var _ = request.Request{}
var _ = request_data_pkg.Operation{}
var _ = errors.ParameterRequiredError{}

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MongoServiceProperties struct {
	Zone string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
}

func (m *MongoServiceProperties) Reset()                    { *m = MongoServiceProperties{} }
func (m *MongoServiceProperties) String() string            { return proto.CompactTextString(m) }
func (*MongoServiceProperties) ProtoMessage()               {}
func (*MongoServiceProperties) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *MongoServiceProperties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type DescribeMongosInput struct {
	Limit     int32    `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	MongoName string   `protobuf:"bytes,2,opt,name=mongo_name,json=mongoName" json:"mongo_name,omitempty"`
	Mongos    []string `protobuf:"bytes,3,rep,name=mongos" json:"mongos,omitempty"`
	Offset    int32    `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	Status    []string `protobuf:"bytes,5,rep,name=status" json:"status,omitempty"`
	Tags      []string `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
	Verbose   int32    `protobuf:"varint,7,opt,name=verbose" json:"verbose,omitempty"`
}

func (m *DescribeMongosInput) Reset()                    { *m = DescribeMongosInput{} }
func (m *DescribeMongosInput) String() string            { return proto.CompactTextString(m) }
func (*DescribeMongosInput) ProtoMessage()               {}
func (*DescribeMongosInput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *DescribeMongosInput) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeMongosInput) GetMongoName() string {
	if m != nil {
		return m.MongoName
	}
	return ""
}

func (m *DescribeMongosInput) GetMongos() []string {
	if m != nil {
		return m.Mongos
	}
	return nil
}

func (m *DescribeMongosInput) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeMongosInput) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeMongosInput) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DescribeMongosInput) GetVerbose() int32 {
	if m != nil {
		return m.Verbose
	}
	return 0
}

type DescribeMongosOutput struct {
	Action     string   `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode    int32    `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message    string   `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	TotalCount int32    `protobuf:"varint,4,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	MongoSet   []*Mongo `protobuf:"bytes,5,rep,name=mongo_set,json=mongoSet" json:"mongo_set,omitempty"`
}

func (m *DescribeMongosOutput) Reset()                    { *m = DescribeMongosOutput{} }
func (m *DescribeMongosOutput) String() string            { return proto.CompactTextString(m) }
func (*DescribeMongosOutput) ProtoMessage()               {}
func (*DescribeMongosOutput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *DescribeMongosOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DescribeMongosOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DescribeMongosOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DescribeMongosOutput) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *DescribeMongosOutput) GetMongoSet() []*Mongo {
	if m != nil {
		return m.MongoSet
	}
	return nil
}

type Mongo struct {
	AlarmStatus         string `protobuf:"bytes,1,opt,name=alarm_status,json=alarmStatus" json:"alarm_status,omitempty"`
	AutoBackupTime      int32  `protobuf:"varint,2,opt,name=auto_backup_time,json=autoBackupTime" json:"auto_backup_time,omitempty"`
	AutoMinorVerUpgrade int32  `protobuf:"varint,3,opt,name=auto_minor_ver_upgrade,json=autoMinorVerUpgrade" json:"auto_minor_ver_upgrade,omitempty"`
}

func (m *Mongo) Reset()                    { *m = Mongo{} }
func (m *Mongo) String() string            { return proto.CompactTextString(m) }
func (*Mongo) ProtoMessage()               {}
func (*Mongo) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

func (m *Mongo) GetAlarmStatus() string {
	if m != nil {
		return m.AlarmStatus
	}
	return ""
}

func (m *Mongo) GetAutoBackupTime() int32 {
	if m != nil {
		return m.AutoBackupTime
	}
	return 0
}

func (m *Mongo) GetAutoMinorVerUpgrade() int32 {
	if m != nil {
		return m.AutoMinorVerUpgrade
	}
	return 0
}

func init() {
	proto.RegisterType((*MongoServiceProperties)(nil), "spec.MongoServiceProperties")
	proto.RegisterType((*DescribeMongosInput)(nil), "spec.DescribeMongosInput")
	proto.RegisterType((*DescribeMongosOutput)(nil), "spec.DescribeMongosOutput")
	proto.RegisterType((*Mongo)(nil), "spec.Mongo")
}

type MongoServiceInterface interface {
	DescribeMongoNodes(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	DescribeMongoParameters(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	ResizeMongos(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	CreateMongo(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	StopMongos(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	StartMongos(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	DescribeMongos(in *DescribeMongosInput) (out *DescribeMongosOutput, err error)
	DeleteMongos(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	CreateMongoFromSnapshot(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	ChangeMongoVxnet(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	AddMongoInstances(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	RemoveMongoInstances(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	ModifyMongoAttributes(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	ModifyMongoInstances(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
	GetMongoMonitor(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error)
}

type MongoService struct {
	Config     *config.Config
	Properties *MongoServiceProperties
}

func NewMongoService(conf *config.Config, zone string) (p *MongoService, err error) {
	return &MongoService{
		Config:     conf,
		Properties: &MongoServiceProperties{Zone: zone},
	}, nil
}

func (p *MongoService) DescribeMongoNodes(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeMongoNodes",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) DescribeMongoParameters(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeMongoParameters",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) ResizeMongos(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ResizeMongos",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) CreateMongo(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateMongo",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) StopMongos(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "StopMongos",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) StartMongos(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "StartMongos",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) DescribeMongos(in *DescribeMongosInput) (out *DescribeMongosOutput, err error) {
	if in == nil {
		in = &DescribeMongosInput{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeMongos",
		RequestMethod: "GET", // GET or POST
	}

	x := &DescribeMongosOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) DeleteMongos(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteMongos",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) CreateMongoFromSnapshot(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateMongoFromSnapshot",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) ChangeMongoVxnet(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ChangeMongoVxnet",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) AddMongoInstances(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "AddMongoInstances",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) RemoveMongoInstances(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "RemoveMongoInstances",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) ModifyMongoAttributes(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyMongoAttributes",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) ModifyMongoInstances(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyMongoInstances",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}
func (p *MongoService) GetMongoMonitor(in *google_protobuf.Empty) (out *google_protobuf.Empty, err error) {
	if in == nil {
		in = &google_protobuf.Empty{}
	}
	o := &request_data_pkg.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "GetMongoMonitor",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func init() { proto.RegisterFile("mongo.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x4e, 0x1b, 0x3b,
	0x14, 0x55, 0x1e, 0x24, 0xc0, 0x4d, 0xc4, 0xe3, 0x19, 0x5e, 0x18, 0x52, 0x55, 0xa5, 0x59, 0x65,
	0x51, 0x05, 0x09, 0xb6, 0x2d, 0x12, 0x84, 0x82, 0xb2, 0x08, 0x45, 0x93, 0x96, 0xed, 0xc8, 0x99,
	0xb9, 0x19, 0xac, 0xc6, 0xf6, 0xc8, 0xbe, 0x13, 0x15, 0xfe, 0xa0, 0xfb, 0x7e, 0x47, 0xbf, 0xa1,
	0x9f, 0x56, 0xd9, 0x9e, 0x48, 0x44, 0xa2, 0x8b, 0xa4, 0xbb, 0x39, 0xc7, 0xf7, 0x9e, 0xb9, 0xe7,
	0xfa, 0x18, 0x9a, 0x52, 0xab, 0x5c, 0xf7, 0x0b, 0xa3, 0x49, 0xb3, 0x4d, 0x5b, 0x60, 0xda, 0x79,
	0x95, 0x6b, 0x9d, 0xcf, 0xf0, 0xc4, 0x73, 0x93, 0x72, 0x7a, 0x82, 0xb2, 0xa0, 0xc7, 0x50, 0xd2,
	0x7d, 0x07, 0xed, 0x91, 0xeb, 0x18, 0xa3, 0x99, 0x8b, 0x14, 0xef, 0x8c, 0x2e, 0xd0, 0x90, 0x40,
	0xcb, 0x18, 0x6c, 0x3e, 0x69, 0x85, 0x51, 0xed, 0xb8, 0xd6, 0xdb, 0x89, 0xfd, 0x77, 0xf7, 0x57,
	0x0d, 0xf6, 0xaf, 0xd0, 0xa6, 0x46, 0x4c, 0xd0, 0xb7, 0xd9, 0xa1, 0x2a, 0x4a, 0x62, 0x07, 0x50,
	0x9f, 0x09, 0x29, 0xc8, 0x17, 0xd7, 0xe3, 0x00, 0xd8, 0x6b, 0x00, 0x3f, 0x4d, 0xa2, 0xb8, 0xc4,
	0xe8, 0x1f, 0xaf, 0xb3, 0xe3, 0x99, 0x5b, 0x2e, 0x91, 0xb5, 0xa1, 0xe1, 0x81, 0x8d, 0x36, 0x8e,
	0x37, 0x7a, 0x3b, 0x71, 0x85, 0x1c, 0xaf, 0xa7, 0x53, 0x8b, 0x14, 0x6d, 0x7a, 0xb5, 0x0a, 0x39,
	0xde, 0x12, 0xa7, 0xd2, 0x46, 0xf5, 0x50, 0x1f, 0x90, 0x1b, 0x94, 0x78, 0x6e, 0xa3, 0x86, 0x67,
	0xfd, 0x37, 0x8b, 0x60, 0x6b, 0x8e, 0x66, 0xa2, 0x2d, 0x46, 0x5b, 0x5e, 0x64, 0x01, 0xbb, 0x3f,
	0x6b, 0x70, 0xb0, 0x6c, 0xe1, 0x53, 0x49, 0xce, 0x43, 0x1b, 0x1a, 0x3c, 0x25, 0xa1, 0x55, 0xe5,
	0xb8, 0x42, 0xec, 0x08, 0xb6, 0x0d, 0x52, 0x92, 0xea, 0x2c, 0x78, 0xa8, 0xc7, 0x5b, 0x06, 0x69,
	0xa0, 0x33, 0x74, 0x7f, 0x91, 0x68, 0x2d, 0xcf, 0x31, 0xda, 0xf0, 0x3d, 0x0b, 0xc8, 0xde, 0x40,
	0x93, 0x34, 0xf1, 0x59, 0x92, 0xea, 0x52, 0x2d, 0x8c, 0x80, 0xa7, 0x06, 0x8e, 0x61, 0x3d, 0x08,
	0x9b, 0x48, 0x9c, 0x4f, 0xe7, 0xa7, 0x79, 0xda, 0xec, 0xbb, 0xeb, 0xea, 0xfb, 0xa1, 0xe2, 0x6d,
	0x19, 0x6e, 0x85, 0xba, 0xdf, 0x6b, 0x50, 0xf7, 0x1c, 0x7b, 0x0b, 0x2d, 0x3e, 0xe3, 0x46, 0x26,
	0xd5, 0x1a, 0xc2, 0x9c, 0x4d, 0xcf, 0x8d, 0xc3, 0x2e, 0x7a, 0xb0, 0xc7, 0x4b, 0xd2, 0xc9, 0x84,
	0xa7, 0x5f, 0xcb, 0x22, 0x21, 0x21, 0x17, 0x43, 0xef, 0x3a, 0xfe, 0xd2, 0xd3, 0x9f, 0x85, 0x44,
	0x76, 0x06, 0x6d, 0x5f, 0x29, 0x85, 0xd2, 0x26, 0x99, 0xa3, 0x49, 0xca, 0x22, 0x37, 0x3c, 0x0b,
	0x56, 0xea, 0xf1, 0xbe, 0x3b, 0x1d, 0xb9, 0xc3, 0x7b, 0x34, 0x5f, 0xc2, 0xd1, 0xe9, 0x8f, 0x6d,
	0x68, 0x3d, 0x8f, 0x0b, 0xbb, 0x02, 0xb6, 0xb4, 0xcc, 0x5b, 0x9d, 0xa1, 0x65, 0xed, 0x7e, 0x88,
	0x5c, 0x7f, 0x11, 0xb9, 0xfe, 0x47, 0x17, 0xb9, 0xce, 0x1f, 0x78, 0x36, 0x84, 0xc3, 0x25, 0x95,
	0x3b, 0x6e, 0xb8, 0x44, 0x42, 0xb3, 0xba, 0xd4, 0x39, 0xb4, 0x62, 0xb4, 0xe2, 0xa9, 0xba, 0xdb,
	0x95, 0xfb, 0x3f, 0x40, 0x73, 0x60, 0x90, 0x53, 0xe8, 0x5f, 0xb9, 0xfd, 0x3d, 0xc0, 0x98, 0x74,
	0xb1, 0xfe, 0xcf, 0xc7, 0xc4, 0x0d, 0xad, 0xd9, 0x7e, 0x03, 0xbb, 0xcb, 0xc9, 0x66, 0x47, 0x21,
	0x52, 0x2f, 0x3c, 0xd9, 0x4e, 0xe7, 0xa5, 0xa3, 0xea, 0x29, 0x9c, 0x43, 0xeb, 0x0a, 0x67, 0x48,
	0xeb, 0x2e, 0x71, 0x08, 0x87, 0xcf, 0x96, 0x78, 0x6d, 0xb4, 0x1c, 0x2b, 0x5e, 0xd8, 0x07, 0x4d,
	0x2b, 0x4b, 0x5d, 0xc2, 0xde, 0xe0, 0x81, 0xab, 0x3c, 0x48, 0xdd, 0x7f, 0x53, 0xb8, 0xba, 0xc6,
	0x00, 0xfe, 0xbb, 0xc8, 0x32, 0x2f, 0x30, 0x54, 0x96, 0xb8, 0x4a, 0xd7, 0xc8, 0xe8, 0x35, 0x1c,
	0xc4, 0x28, 0xf5, 0x1c, 0xff, 0x52, 0xe7, 0x06, 0xfe, 0x1f, 0xe9, 0x4c, 0x4c, 0x1f, 0xbd, 0xce,
	0x05, 0x91, 0x11, 0x93, 0x92, 0xd6, 0x1b, 0xe8, 0x99, 0xd0, 0xfa, 0x03, 0x5d, 0xc0, 0xbf, 0x37,
	0x18, 0x22, 0x37, 0xd2, 0x4a, 0x90, 0x36, 0xab, 0x4a, 0x4c, 0x1a, 0x1e, 0x9f, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x70, 0x50, 0x98, 0x45, 0x7d, 0x06, 0x00, 0x00,
}
