// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tag.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/chai2010/qingcloud-go/pkg/api/spec_metadata"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TagServiceProperties struct {
	Zone             *string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TagServiceProperties) Reset()                    { *m = TagServiceProperties{} }
func (m *TagServiceProperties) String() string            { return proto.CompactTextString(m) }
func (*TagServiceProperties) ProtoMessage()               {}
func (*TagServiceProperties) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{0} }

func (m *TagServiceProperties) GetZone() string {
	if m != nil && m.Zone != nil {
		return *m.Zone
	}
	return ""
}

type DescribeTagsInput struct {
	Tags             []string `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	SearchWord       *string  `protobuf:"bytes,2,opt,name=search_word,json=searchWord" json:"search_word,omitempty"`
	Verbose          *int32   `protobuf:"varint,3,opt,name=verbose" json:"verbose,omitempty"`
	Offset           *int32   `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	Limit            *int32   `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DescribeTagsInput) Reset()                    { *m = DescribeTagsInput{} }
func (m *DescribeTagsInput) String() string            { return proto.CompactTextString(m) }
func (*DescribeTagsInput) ProtoMessage()               {}
func (*DescribeTagsInput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{1} }

func (m *DescribeTagsInput) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DescribeTagsInput) GetSearchWord() string {
	if m != nil && m.SearchWord != nil {
		return *m.SearchWord
	}
	return ""
}

func (m *DescribeTagsInput) GetVerbose() int32 {
	if m != nil && m.Verbose != nil {
		return *m.Verbose
	}
	return 0
}

func (m *DescribeTagsInput) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *DescribeTagsInput) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

type DescribeTagsOutput struct {
	Action           *string                            `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode          *int32                             `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message          *string                            `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	TagSet           []*DescribeTagsOutput_ResponseItem `protobuf:"bytes,4,rep,name=tag_set,json=tagSet" json:"tag_set,omitempty"`
	TotalCount       *int32                             `protobuf:"varint,5,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *DescribeTagsOutput) Reset()                    { *m = DescribeTagsOutput{} }
func (m *DescribeTagsOutput) String() string            { return proto.CompactTextString(m) }
func (*DescribeTagsOutput) ProtoMessage()               {}
func (*DescribeTagsOutput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{2} }

func (m *DescribeTagsOutput) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *DescribeTagsOutput) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *DescribeTagsOutput) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *DescribeTagsOutput) GetTagSet() []*DescribeTagsOutput_ResponseItem {
	if m != nil {
		return m.TagSet
	}
	return nil
}

func (m *DescribeTagsOutput) GetTotalCount() int32 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type DescribeTagsOutput_ResponseItem struct {
	TagId             *string  `protobuf:"bytes,1,opt,name=tag_id,json=tagId" json:"tag_id,omitempty"`
	TagName           *string  `protobuf:"bytes,2,opt,name=tag_name,json=tagName" json:"tag_name,omitempty"`
	Description       *string  `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ResourceCount     *int32   `protobuf:"varint,4,opt,name=resource_count,json=resourceCount" json:"resource_count,omitempty"`
	ResourceTypeCount *int32   `protobuf:"varint,5,opt,name=resource_type_count,json=resourceTypeCount" json:"resource_type_count,omitempty"`
	ResourceTagPairs  []string `protobuf:"bytes,6,rep,name=resource_tag_pairs,json=resourceTagPairs" json:"resource_tag_pairs,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *DescribeTagsOutput_ResponseItem) Reset()         { *m = DescribeTagsOutput_ResponseItem{} }
func (m *DescribeTagsOutput_ResponseItem) String() string { return proto.CompactTextString(m) }
func (*DescribeTagsOutput_ResponseItem) ProtoMessage()    {}
func (*DescribeTagsOutput_ResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor25, []int{2, 0}
}

func (m *DescribeTagsOutput_ResponseItem) GetTagId() string {
	if m != nil && m.TagId != nil {
		return *m.TagId
	}
	return ""
}

func (m *DescribeTagsOutput_ResponseItem) GetTagName() string {
	if m != nil && m.TagName != nil {
		return *m.TagName
	}
	return ""
}

func (m *DescribeTagsOutput_ResponseItem) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *DescribeTagsOutput_ResponseItem) GetResourceCount() int32 {
	if m != nil && m.ResourceCount != nil {
		return *m.ResourceCount
	}
	return 0
}

func (m *DescribeTagsOutput_ResponseItem) GetResourceTypeCount() int32 {
	if m != nil && m.ResourceTypeCount != nil {
		return *m.ResourceTypeCount
	}
	return 0
}

func (m *DescribeTagsOutput_ResponseItem) GetResourceTagPairs() []string {
	if m != nil {
		return m.ResourceTagPairs
	}
	return nil
}

type CreateTagInput struct {
	TagName          *string `protobuf:"bytes,1,opt,name=tag_name,json=tagName" json:"tag_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateTagInput) Reset()                    { *m = CreateTagInput{} }
func (m *CreateTagInput) String() string            { return proto.CompactTextString(m) }
func (*CreateTagInput) ProtoMessage()               {}
func (*CreateTagInput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{3} }

func (m *CreateTagInput) GetTagName() string {
	if m != nil && m.TagName != nil {
		return *m.TagName
	}
	return ""
}

type CreateTagOutput struct {
	Action           *string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode          *int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message          *string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	TagId            *string `protobuf:"bytes,4,opt,name=tag_id,json=tagId" json:"tag_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateTagOutput) Reset()                    { *m = CreateTagOutput{} }
func (m *CreateTagOutput) String() string            { return proto.CompactTextString(m) }
func (*CreateTagOutput) ProtoMessage()               {}
func (*CreateTagOutput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{4} }

func (m *CreateTagOutput) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *CreateTagOutput) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *CreateTagOutput) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *CreateTagOutput) GetTagId() string {
	if m != nil && m.TagId != nil {
		return *m.TagId
	}
	return ""
}

type DeleteTagsInput struct {
	Tags             []string `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DeleteTagsInput) Reset()                    { *m = DeleteTagsInput{} }
func (m *DeleteTagsInput) String() string            { return proto.CompactTextString(m) }
func (*DeleteTagsInput) ProtoMessage()               {}
func (*DeleteTagsInput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{5} }

func (m *DeleteTagsInput) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type DeleteTagsOutput struct {
	Action           *string  `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode          *int32   `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message          *string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Tags             []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DeleteTagsOutput) Reset()                    { *m = DeleteTagsOutput{} }
func (m *DeleteTagsOutput) String() string            { return proto.CompactTextString(m) }
func (*DeleteTagsOutput) ProtoMessage()               {}
func (*DeleteTagsOutput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{6} }

func (m *DeleteTagsOutput) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *DeleteTagsOutput) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *DeleteTagsOutput) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *DeleteTagsOutput) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ModifyTagAttributesInput struct {
	Tag              *string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	TagName          *string `protobuf:"bytes,2,opt,name=tag_name,json=tagName" json:"tag_name,omitempty"`
	Description      *string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModifyTagAttributesInput) Reset()                    { *m = ModifyTagAttributesInput{} }
func (m *ModifyTagAttributesInput) String() string            { return proto.CompactTextString(m) }
func (*ModifyTagAttributesInput) ProtoMessage()               {}
func (*ModifyTagAttributesInput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{7} }

func (m *ModifyTagAttributesInput) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *ModifyTagAttributesInput) GetTagName() string {
	if m != nil && m.TagName != nil {
		return *m.TagName
	}
	return ""
}

func (m *ModifyTagAttributesInput) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type ModifyTagAttributesOutput struct {
	Action           *string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode          *int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message          *string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModifyTagAttributesOutput) Reset()                    { *m = ModifyTagAttributesOutput{} }
func (m *ModifyTagAttributesOutput) String() string            { return proto.CompactTextString(m) }
func (*ModifyTagAttributesOutput) ProtoMessage()               {}
func (*ModifyTagAttributesOutput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{8} }

func (m *ModifyTagAttributesOutput) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *ModifyTagAttributesOutput) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *ModifyTagAttributesOutput) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type AttachTagsInput struct {
	ResourceTagPairs []*ResourceTagPair `protobuf:"bytes,1,rep,name=resource_tag_pairs,json=resourceTagPairs" json:"resource_tag_pairs,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AttachTagsInput) Reset()                    { *m = AttachTagsInput{} }
func (m *AttachTagsInput) String() string            { return proto.CompactTextString(m) }
func (*AttachTagsInput) ProtoMessage()               {}
func (*AttachTagsInput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{9} }

func (m *AttachTagsInput) GetResourceTagPairs() []*ResourceTagPair {
	if m != nil {
		return m.ResourceTagPairs
	}
	return nil
}

type AttachTagsOutput struct {
	Action           *string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode          *int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message          *string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AttachTagsOutput) Reset()                    { *m = AttachTagsOutput{} }
func (m *AttachTagsOutput) String() string            { return proto.CompactTextString(m) }
func (*AttachTagsOutput) ProtoMessage()               {}
func (*AttachTagsOutput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{10} }

func (m *AttachTagsOutput) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *AttachTagsOutput) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *AttachTagsOutput) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type DetachTagsInput struct {
	ResourceTagPairs []*ResourceTagPair `protobuf:"bytes,1,rep,name=resource_tag_pairs,json=resourceTagPairs" json:"resource_tag_pairs,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *DetachTagsInput) Reset()                    { *m = DetachTagsInput{} }
func (m *DetachTagsInput) String() string            { return proto.CompactTextString(m) }
func (*DetachTagsInput) ProtoMessage()               {}
func (*DetachTagsInput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{11} }

func (m *DetachTagsInput) GetResourceTagPairs() []*ResourceTagPair {
	if m != nil {
		return m.ResourceTagPairs
	}
	return nil
}

type DetachTagsOutput struct {
	Action           *string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode          *int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message          *string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DetachTagsOutput) Reset()                    { *m = DetachTagsOutput{} }
func (m *DetachTagsOutput) String() string            { return proto.CompactTextString(m) }
func (*DetachTagsOutput) ProtoMessage()               {}
func (*DetachTagsOutput) Descriptor() ([]byte, []int) { return fileDescriptor25, []int{12} }

func (m *DetachTagsOutput) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *DetachTagsOutput) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *DetachTagsOutput) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TagServiceProperties)(nil), "service.TagServiceProperties")
	proto.RegisterType((*DescribeTagsInput)(nil), "service.DescribeTagsInput")
	proto.RegisterType((*DescribeTagsOutput)(nil), "service.DescribeTagsOutput")
	proto.RegisterType((*DescribeTagsOutput_ResponseItem)(nil), "service.DescribeTagsOutput.ResponseItem")
	proto.RegisterType((*CreateTagInput)(nil), "service.CreateTagInput")
	proto.RegisterType((*CreateTagOutput)(nil), "service.CreateTagOutput")
	proto.RegisterType((*DeleteTagsInput)(nil), "service.DeleteTagsInput")
	proto.RegisterType((*DeleteTagsOutput)(nil), "service.DeleteTagsOutput")
	proto.RegisterType((*ModifyTagAttributesInput)(nil), "service.ModifyTagAttributesInput")
	proto.RegisterType((*ModifyTagAttributesOutput)(nil), "service.ModifyTagAttributesOutput")
	proto.RegisterType((*AttachTagsInput)(nil), "service.AttachTagsInput")
	proto.RegisterType((*AttachTagsOutput)(nil), "service.AttachTagsOutput")
	proto.RegisterType((*DetachTagsInput)(nil), "service.DetachTagsInput")
	proto.RegisterType((*DetachTagsOutput)(nil), "service.DetachTagsOutput")
}

func init() { proto.RegisterFile("tag.proto", fileDescriptor25) }

var fileDescriptor25 = []byte{
	// 707 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x96, 0xdf, 0x7c, 0xbd, 0x99, 0xf4, 0x6d, 0xd3, 0x6d, 0xdf, 0xe2, 0x9a, 0x03, 0xc1, 0x52,
	0xa5, 0x88, 0x0f, 0x47, 0xf4, 0xc0, 0x81, 0x03, 0x52, 0xd4, 0x0a, 0x54, 0x89, 0x8f, 0x2a, 0x44,
	0x42, 0x48, 0x48, 0xd6, 0xd6, 0x9e, 0x3a, 0x2b, 0xc5, 0x5e, 0xb3, 0x3b, 0x29, 0x94, 0x5f, 0xc1,
	0x89, 0xbf, 0xc1, 0x9d, 0x3f, 0xc4, 0x1f, 0xe0, 0xc2, 0x0d, 0xad, 0xed, 0xc4, 0x4e, 0x1b, 0x7a,
	0x41, 0xb9, 0x79, 0x66, 0x9f, 0x9d, 0x79, 0x9e, 0xf1, 0x33, 0x0b, 0x6d, 0xe2, 0x91, 0x97, 0x2a,
	0x49, 0x92, 0xb5, 0x34, 0xaa, 0x0b, 0x11, 0xa0, 0xd3, 0xa1, 0xcb, 0x14, 0x75, 0x9e, 0x75, 0x6c,
	0x9d, 0x62, 0xe0, 0xc7, 0x48, 0x3c, 0xe4, 0xc4, 0x07, 0x26, 0xca, 0x4f, 0xdc, 0x7b, 0xb0, 0x3b,
	0xe6, 0xd1, 0x9b, 0xfc, 0xd2, 0xa9, 0x92, 0x29, 0x2a, 0x12, 0xa8, 0x19, 0x83, 0xfa, 0x67, 0x99,
	0xa0, 0x6d, 0xf5, 0xac, 0x7e, 0x7b, 0x94, 0x7d, 0xbb, 0x5f, 0x2c, 0xd8, 0x3e, 0x46, 0x1d, 0x28,
	0x71, 0x86, 0x63, 0x1e, 0xe9, 0x93, 0x24, 0x9d, 0x91, 0x41, 0x12, 0x8f, 0xb4, 0x6d, 0xf5, 0x6a,
	0x06, 0x69, 0xbe, 0xd9, 0x1d, 0xe8, 0x68, 0xe4, 0x2a, 0x98, 0xf8, 0x1f, 0xa5, 0x0a, 0xed, 0x7f,
	0xb2, 0x22, 0x90, 0xa7, 0xde, 0x4a, 0x15, 0x32, 0x1b, 0x5a, 0x17, 0xa8, 0xce, 0xa4, 0x46, 0xbb,
	0xd6, 0xb3, 0xfa, 0x8d, 0xd1, 0x3c, 0x64, 0x7b, 0xd0, 0x94, 0xe7, 0xe7, 0x1a, 0xc9, 0xae, 0x67,
	0x07, 0x45, 0xc4, 0x76, 0xa1, 0x31, 0x15, 0xb1, 0x20, 0xbb, 0x91, 0xa5, 0xf3, 0xc0, 0xfd, 0x56,
	0x03, 0x56, 0xa5, 0xf4, 0x7a, 0x46, 0x86, 0xd3, 0x1e, 0x34, 0x79, 0x40, 0x42, 0x26, 0x05, 0xff,
	0x22, 0x62, 0xfb, 0xf0, 0xaf, 0x42, 0xf2, 0x03, 0x19, 0x62, 0x46, 0xaa, 0x31, 0x6a, 0x29, 0xa4,
	0x23, 0x19, 0xa2, 0x61, 0x14, 0xa3, 0xd6, 0x3c, 0xca, 0x19, 0xb5, 0x47, 0xf3, 0x90, 0x0d, 0xa1,
	0x45, 0x3c, 0xf2, 0x73, 0x4a, 0xb5, 0x7e, 0xe7, 0xb0, 0xef, 0x15, 0x43, 0xf6, 0xae, 0xb7, 0xf6,
	0x46, 0xa8, 0x53, 0x99, 0x68, 0x3c, 0x21, 0x8c, 0x47, 0x4d, 0x32, 0xb3, 0x25, 0x33, 0x0f, 0x92,
	0xc4, 0xa7, 0x7e, 0x20, 0x67, 0xc9, 0x5c, 0x02, 0x64, 0xa9, 0x23, 0x93, 0x71, 0x7e, 0x58, 0xb0,
	0x51, 0xbd, 0xc9, 0xfe, 0x07, 0x73, 0xd7, 0x17, 0x61, 0xa1, 0xa0, 0x41, 0x3c, 0x3a, 0x09, 0x8d,
	0x00, 0x93, 0x4e, 0x78, 0x8c, 0xc5, 0x54, 0x0d, 0xb7, 0x57, 0x3c, 0x46, 0xd6, 0x83, 0x4e, 0x98,
	0xd1, 0x49, 0x33, 0xe1, 0xb9, 0x88, 0x6a, 0x8a, 0x1d, 0xc0, 0xa6, 0x42, 0x2d, 0x67, 0x2a, 0xc0,
	0x82, 0x48, 0x3e, 0xe2, 0xff, 0xe6, 0xd9, 0x8c, 0x0b, 0xf3, 0x60, 0x67, 0x01, 0x33, 0x26, 0x5a,
	0x22, 0xbd, 0x3d, 0x3f, 0x1a, 0x5f, 0xa6, 0x05, 0xfe, 0x01, 0xb0, 0x12, 0xcf, 0x23, 0x3f, 0xe5,
	0x42, 0x69, 0xbb, 0x99, 0xd9, 0xa1, 0xbb, 0x80, 0xf3, 0xe8, 0xd4, 0xe4, 0xdd, 0xfb, 0xb0, 0x79,
	0xa4, 0x90, 0x93, 0xc9, 0xe4, 0x06, 0xaa, 0x6a, 0xb2, 0x96, 0x34, 0xb9, 0x33, 0xd8, 0x5a, 0x80,
	0xd7, 0xf1, 0x6b, 0xcb, 0x29, 0xd7, 0x2b, 0x53, 0x76, 0x0f, 0x60, 0xeb, 0x18, 0xa7, 0x48, 0x37,
	0xbb, 0xdc, 0xd5, 0xd0, 0x2d, 0x61, 0xeb, 0xa0, 0x37, 0x6f, 0x5a, 0xaf, 0x34, 0x15, 0x60, 0xbf,
	0x94, 0xa1, 0x38, 0xbf, 0x1c, 0xf3, 0x68, 0x48, 0xa4, 0xc4, 0xd9, 0x8c, 0xb0, 0x20, 0xd9, 0x85,
	0x1a, 0xf1, 0xa8, 0xe8, 0x6c, 0x3e, 0xff, 0xca, 0x2f, 0xee, 0x04, 0xf6, 0x57, 0xb4, 0x5a, 0x83,
	0x50, 0xf7, 0x1d, 0x6c, 0x0d, 0x89, 0x78, 0x30, 0x29, 0x07, 0xfe, 0x6c, 0xa5, 0xab, 0xac, 0x6c,
	0x01, 0xed, 0xc5, 0x02, 0x8e, 0x96, 0xed, 0xb5, 0xc2, 0x6f, 0x3e, 0x74, 0xcb, 0xd2, 0x6b, 0xe2,
	0x7e, 0x8c, 0x6b, 0xe3, 0x5e, 0x96, 0x5e, 0x03, 0xf7, 0xc3, 0x9f, 0x35, 0x80, 0xf2, 0xf9, 0x67,
	0xcf, 0x61, 0xa3, 0xfa, 0xa2, 0x31, 0x67, 0xe5, 0x43, 0x97, 0x69, 0x74, 0x6e, 0xdf, 0xf0, 0x08,
	0xb2, 0xa7, 0xd0, 0x5e, 0xec, 0x2d, 0xbb, 0xb5, 0x40, 0x2e, 0x2f, 0xbe, 0x63, 0x5f, 0x3f, 0x28,
	0xee, 0x0f, 0x01, 0xca, 0xcd, 0x62, 0x76, 0xa5, 0xd5, 0xd2, 0x56, 0x3a, 0xfb, 0x2b, 0x4e, 0x8a,
	0x12, 0xef, 0x61, 0x67, 0x85, 0x79, 0xd9, 0xdd, 0xc5, 0x8d, 0x3f, 0x6d, 0x91, 0xe3, 0xde, 0x04,
	0x29, 0x09, 0x96, 0xae, 0xaa, 0x10, 0xbc, 0xe2, 0xe2, 0x0a, 0xc1, 0x6b, 0x26, 0xcc, 0x34, 0xae,
	0x28, 0x71, 0xc5, 0x4c, 0x4b, 0x1a, 0x97, 0x4b, 0x38, 0x8f, 0xbf, 0x7f, 0xfd, 0xf5, 0xe2, 0x11,
	0x0c, 0x9c, 0x87, 0x13, 0xa2, 0x54, 0x3f, 0x19, 0x0c, 0x42, 0x19, 0x68, 0xef, 0x83, 0x48, 0xa2,
	0x60, 0x2a, 0x67, 0xa1, 0x17, 0xc8, 0x78, 0xc0, 0x53, 0x31, 0x20, 0x1e, 0x0d, 0x44, 0x12, 0xe2,
	0x27, 0x6f, 0x42, 0xf1, 0xf4, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x19, 0xf8, 0x65, 0x30,
	0x08, 0x00, 0x00,
}
