// Code generated by protoc-gen-qingcloud. DO NOT EDIT.
// plugin: https://github.com/chai2010/qingcloud-go/tree/master/pkg/cmd/protoc-gen-qingcloud
// plugin: https://github.com/chai2010/qingcloud-go/tree/master/pkg/cmd/protoc-gen-qingcloud/generator/go-sdk
// source: zone.proto

package service

import proto "github.com/golang/protobuf/proto"
import "fmt"

import "github.com/chai2010/qingcloud-go/pkg/client"
import "github.com/chai2010/qingcloud-go/pkg/config"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = proto.Marshal

var _ = config.Config{}
var _ = client.NewClient

type ZoneServiceInterface interface {
	DescribeZones(in *DescribeZonesInput) (out *DescribeZonesOutput, err error)
}

type ZoneService struct {
	Config           *config.Config
	Properties       *ZoneServiceProperties
	LastResponseBody string
}

func NewZoneService(conf *config.Config, zone string) (p *ZoneService) {
	return &ZoneService{
		Config:     conf,
		Properties: &ZoneServiceProperties{Zone: proto.String(zone)},
	}
}

func (p *ZoneService) DescribeZones(input *DescribeZonesInput) (output *DescribeZonesOutput, err error) {
	client := client.NewClient("", "", nil)
	output = new(DescribeZonesOutput)

	err = client.CallMethod(nil, "DescribeZones", input, output, nil)
	if err != nil {
		return nil, err
	}

	return
}
