// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qingcloud_sdk_rule/rule.proto

/*
Package qingcloud_sdk_rule is a generated protocol buffer package.

It is generated from these files:
	qingcloud_sdk_rule/rule.proto

It has these top-level messages:
	ServiceOptionsRule
	MethodOptionsRule
	MessageOptionsRule
	FieldOptionsRule
*/
package qingcloud_sdk_rule

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 服务规则
// 有主服务和子服务之分, 子服务隶属于某个主服务
type ServiceOptionsRule struct {
	DocUrl      string `protobuf:"bytes,1,opt,name=doc_url,json=docUrl" json:"doc_url,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *ServiceOptionsRule) Reset()                    { *m = ServiceOptionsRule{} }
func (m *ServiceOptionsRule) String() string            { return proto.CompactTextString(m) }
func (*ServiceOptionsRule) ProtoMessage()               {}
func (*ServiceOptionsRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceOptionsRule) GetDocUrl() string {
	if m != nil {
		return m.DocUrl
	}
	return ""
}

func (m *ServiceOptionsRule) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

// 方法规则
type MethodOptionsRule struct {
	DocUrl     string `protobuf:"bytes,1,opt,name=doc_url,json=docUrl" json:"doc_url,omitempty"`
	HttpMethod string `protobuf:"bytes,2,opt,name=http_method,json=httpMethod" json:"http_method,omitempty"`
	InputType  string `protobuf:"bytes,3,opt,name=input_type,json=inputType" json:"input_type,omitempty"`
	OutputType string `protobuf:"bytes,4,opt,name=output_type,json=outputType" json:"output_type,omitempty"`
}

func (m *MethodOptionsRule) Reset()                    { *m = MethodOptionsRule{} }
func (m *MethodOptionsRule) String() string            { return proto.CompactTextString(m) }
func (*MethodOptionsRule) ProtoMessage()               {}
func (*MethodOptionsRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MethodOptionsRule) GetDocUrl() string {
	if m != nil {
		return m.DocUrl
	}
	return ""
}

func (m *MethodOptionsRule) GetHttpMethod() string {
	if m != nil {
		return m.HttpMethod
	}
	return ""
}

func (m *MethodOptionsRule) GetInputType() string {
	if m != nil {
		return m.InputType
	}
	return ""
}

func (m *MethodOptionsRule) GetOutputType() string {
	if m != nil {
		return m.OutputType
	}
	return ""
}

// 输入参数规则
// 输入参数成员只有数值类型和字符串, 以及对应的数组, 不含嵌套结构
// 元信息部分只能包含 字符串/数字/链接符号 等普通的字符
type MessageOptionsRule struct {
	RequiredFileds  string `protobuf:"bytes,1,opt,name=required_fileds,json=requiredFileds" json:"required_fileds,omitempty"`
	DefaultValue    string `protobuf:"bytes,2,opt,name=default_value,json=defaultValue" json:"default_value,omitempty"`
	EnumValue       string `protobuf:"bytes,3,opt,name=enum_value,json=enumValue" json:"enum_value,omitempty"`
	MinValue        string `protobuf:"bytes,4,opt,name=min_value,json=minValue" json:"min_value,omitempty"`
	MaxValue        string `protobuf:"bytes,5,opt,name=max_value,json=maxValue" json:"max_value,omitempty"`
	MultipleOfValue string `protobuf:"bytes,6,opt,name=multiple_of_value,json=multipleOfValue" json:"multiple_of_value,omitempty"`
	RegexpValue     string `protobuf:"bytes,7,opt,name=regexp_value,json=regexpValue" json:"regexp_value,omitempty"`
}

func (m *MessageOptionsRule) Reset()                    { *m = MessageOptionsRule{} }
func (m *MessageOptionsRule) String() string            { return proto.CompactTextString(m) }
func (*MessageOptionsRule) ProtoMessage()               {}
func (*MessageOptionsRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MessageOptionsRule) GetRequiredFileds() string {
	if m != nil {
		return m.RequiredFileds
	}
	return ""
}

func (m *MessageOptionsRule) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

func (m *MessageOptionsRule) GetEnumValue() string {
	if m != nil {
		return m.EnumValue
	}
	return ""
}

func (m *MessageOptionsRule) GetMinValue() string {
	if m != nil {
		return m.MinValue
	}
	return ""
}

func (m *MessageOptionsRule) GetMaxValue() string {
	if m != nil {
		return m.MaxValue
	}
	return ""
}

func (m *MessageOptionsRule) GetMultipleOfValue() string {
	if m != nil {
		return m.MultipleOfValue
	}
	return ""
}

func (m *MessageOptionsRule) GetRegexpValue() string {
	if m != nil {
		return m.RegexpValue
	}
	return ""
}

// Message成员规则
type FieldOptionsRule struct {
	MinValue          string   `protobuf:"bytes,1,opt,name=min_value,json=minValue" json:"min_value,omitempty"`
	MaxValue          string   `protobuf:"bytes,2,opt,name=max_value,json=maxValue" json:"max_value,omitempty"`
	MultipleOfValue   string   `protobuf:"bytes,3,opt,name=multiple_of_value,json=multipleOfValue" json:"multiple_of_value,omitempty"`
	ExclusiveMinValue string   `protobuf:"bytes,4,opt,name=exclusive_min_value,json=exclusiveMinValue" json:"exclusive_min_value,omitempty"`
	ExclusiveMaxValue string   `protobuf:"bytes,5,opt,name=exclusive_max_value,json=exclusiveMaxValue" json:"exclusive_max_value,omitempty"`
	MaxLength         string   `protobuf:"bytes,6,opt,name=max_length,json=maxLength" json:"max_length,omitempty"`
	MinLength         string   `protobuf:"bytes,7,opt,name=min_length,json=minLength" json:"min_length,omitempty"`
	RegexpValue       string   `protobuf:"bytes,8,opt,name=regexp_value,json=regexpValue" json:"regexp_value,omitempty"`
	EnumValue         []string `protobuf:"bytes,9,rep,name=enum_value,json=enumValue" json:"enum_value,omitempty"`
}

func (m *FieldOptionsRule) Reset()                    { *m = FieldOptionsRule{} }
func (m *FieldOptionsRule) String() string            { return proto.CompactTextString(m) }
func (*FieldOptionsRule) ProtoMessage()               {}
func (*FieldOptionsRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FieldOptionsRule) GetMinValue() string {
	if m != nil {
		return m.MinValue
	}
	return ""
}

func (m *FieldOptionsRule) GetMaxValue() string {
	if m != nil {
		return m.MaxValue
	}
	return ""
}

func (m *FieldOptionsRule) GetMultipleOfValue() string {
	if m != nil {
		return m.MultipleOfValue
	}
	return ""
}

func (m *FieldOptionsRule) GetExclusiveMinValue() string {
	if m != nil {
		return m.ExclusiveMinValue
	}
	return ""
}

func (m *FieldOptionsRule) GetExclusiveMaxValue() string {
	if m != nil {
		return m.ExclusiveMaxValue
	}
	return ""
}

func (m *FieldOptionsRule) GetMaxLength() string {
	if m != nil {
		return m.MaxLength
	}
	return ""
}

func (m *FieldOptionsRule) GetMinLength() string {
	if m != nil {
		return m.MinLength
	}
	return ""
}

func (m *FieldOptionsRule) GetRegexpValue() string {
	if m != nil {
		return m.RegexpValue
	}
	return ""
}

func (m *FieldOptionsRule) GetEnumValue() []string {
	if m != nil {
		return m.EnumValue
	}
	return nil
}

var E_ServiceRule = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*ServiceOptionsRule)(nil),
	Field:         10001,
	Name:          "qingcloud.sdk.rule.service_rule",
	Tag:           "bytes,10001,opt,name=service_rule,json=serviceRule",
	Filename:      "qingcloud_sdk_rule/rule.proto",
}

var E_MethodRule = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*MethodOptionsRule)(nil),
	Field:         10001,
	Name:          "qingcloud.sdk.rule.method_rule",
	Tag:           "bytes,10001,opt,name=method_rule,json=methodRule",
	Filename:      "qingcloud_sdk_rule/rule.proto",
}

var E_MessageRule = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*MessageOptionsRule)(nil),
	Field:         10001,
	Name:          "qingcloud.sdk.rule.message_rule",
	Tag:           "bytes,10001,opt,name=message_rule,json=messageRule",
	Filename:      "qingcloud_sdk_rule/rule.proto",
}

var E_FieldRule = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*FieldOptionsRule)(nil),
	Field:         10001,
	Name:          "qingcloud.sdk.rule.field_rule",
	Tag:           "bytes,10001,opt,name=field_rule,json=fieldRule",
	Filename:      "qingcloud_sdk_rule/rule.proto",
}

func init() {
	proto.RegisterType((*ServiceOptionsRule)(nil), "qingcloud.sdk.rule.ServiceOptionsRule")
	proto.RegisterType((*MethodOptionsRule)(nil), "qingcloud.sdk.rule.MethodOptionsRule")
	proto.RegisterType((*MessageOptionsRule)(nil), "qingcloud.sdk.rule.MessageOptionsRule")
	proto.RegisterType((*FieldOptionsRule)(nil), "qingcloud.sdk.rule.FieldOptionsRule")
	proto.RegisterExtension(E_ServiceRule)
	proto.RegisterExtension(E_MethodRule)
	proto.RegisterExtension(E_MessageRule)
	proto.RegisterExtension(E_FieldRule)
}

func init() { proto.RegisterFile("qingcloud_sdk_rule/rule.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0x54, 0x52, 0x48, 0x9a, 0x2f, 0x81, 0x12, 0x73, 0x20, 0x02, 0x85, 0xa6, 0xe1, 0xaf, 0x42,
	0xc2, 0x2e, 0xe5, 0x56, 0x6e, 0x1c, 0x7a, 0x22, 0x2d, 0x0a, 0x14, 0x24, 0x2e, 0x96, 0x63, 0x7f,
	0x76, 0x56, 0x59, 0x7b, 0xb7, 0xf6, 0x6e, 0x94, 0xbe, 0x02, 0x12, 0x07, 0xde, 0x8e, 0xc7, 0x41,
	0xfb, 0xe3, 0xb4, 0x8e, 0x43, 0xd5, 0x4b, 0x94, 0xcc, 0xcc, 0x7e, 0x33, 0xfb, 0x33, 0x81, 0xe1,
	0x25, 0xc9, 0x92, 0x90, 0x32, 0x19, 0xf9, 0x45, 0xb4, 0xf0, 0x73, 0x49, 0xd1, 0x53, 0x1f, 0x2e,
	0xcf, 0x99, 0x60, 0x8e, 0xb3, 0xa6, 0xdd, 0x22, 0x5a, 0xb8, 0x8a, 0x79, 0x3a, 0x4a, 0x18, 0x4b,
	0x28, 0x7a, 0x5a, 0x31, 0x93, 0xb1, 0x17, 0x61, 0x11, 0xe6, 0x84, 0x0b, 0x96, 0x9b, 0x55, 0xe3,
	0x2f, 0xe0, 0x7c, 0xc5, 0x7c, 0x49, 0x42, 0x3c, 0xe7, 0x82, 0xb0, 0xac, 0x98, 0x4a, 0x8a, 0xce,
	0x13, 0x68, 0x47, 0x2c, 0xf4, 0x65, 0x4e, 0x07, 0x8d, 0x51, 0xe3, 0xb0, 0x33, 0x6d, 0x45, 0x2c,
	0xbc, 0xc8, 0xa9, 0x73, 0x00, 0xbd, 0xc2, 0xc8, 0xfd, 0x2c, 0x48, 0x71, 0xd0, 0xd4, 0x6c, 0xd7,
	0x62, 0x67, 0x41, 0x8a, 0xe3, 0xdf, 0x0d, 0xe8, 0x4f, 0x50, 0xcc, 0x59, 0x74, 0xa7, 0x89, 0xfb,
	0xd0, 0x9d, 0x0b, 0xc1, 0xfd, 0x54, 0x2f, 0xb1, 0x03, 0x41, 0x41, 0x66, 0x88, 0x33, 0x04, 0x20,
	0x19, 0x97, 0xc2, 0x17, 0x57, 0x1c, 0x07, 0x3b, 0x9a, 0xef, 0x68, 0xe4, 0xdb, 0x15, 0x47, 0xb5,
	0x9e, 0x49, 0xb1, 0xe6, 0xef, 0x99, 0xf5, 0x06, 0x52, 0x82, 0xf1, 0xaf, 0x26, 0x38, 0x13, 0x2c,
	0x8a, 0x20, 0xa9, 0x6c, 0xf1, 0x0d, 0xec, 0xe5, 0x78, 0x29, 0x49, 0x8e, 0x91, 0x1f, 0x13, 0x8a,
	0x51, 0x61, 0x83, 0x3d, 0x2c, 0xe1, 0x53, 0x8d, 0x3a, 0x2f, 0xe0, 0x41, 0x84, 0x71, 0x20, 0xa9,
	0xf0, 0x97, 0x01, 0x95, 0xe5, 0x9e, 0x7b, 0x16, 0xfc, 0xae, 0x30, 0x15, 0x12, 0x33, 0x99, 0x5a,
	0x85, 0x0d, 0xa9, 0x10, 0x43, 0x3f, 0x83, 0x4e, 0x4a, 0x32, 0xcb, 0x9a, 0x88, 0xbb, 0x29, 0xc9,
	0xae, 0xc9, 0x60, 0x65, 0xc9, 0xfb, 0x96, 0x0c, 0x56, 0x86, 0x7c, 0x0b, 0xfd, 0x54, 0x52, 0x41,
	0x38, 0x45, 0x9f, 0xc5, 0x56, 0xd4, 0xd2, 0xa2, 0xbd, 0x92, 0x38, 0x8f, 0x8d, 0xf6, 0x00, 0x7a,
	0x39, 0x26, 0xb8, 0xe2, 0x56, 0xd6, 0x36, 0x97, 0x63, 0x30, 0x2d, 0x19, 0xff, 0x6d, 0xc2, 0xa3,
	0x53, 0x82, 0xb4, 0x72, 0x37, 0x95, 0x74, 0x8d, 0xdb, 0xd2, 0x35, 0xef, 0x92, 0x6e, 0x67, 0x7b,
	0x3a, 0x17, 0x1e, 0xe3, 0x2a, 0xa4, 0xb2, 0x20, 0x4b, 0xf4, 0x37, 0x4f, 0xa3, 0xbf, 0xa6, 0x26,
	0xa5, 0x71, 0x55, 0xbf, 0x71, 0x40, 0x37, 0xf4, 0x65, 0x96, 0x21, 0x80, 0x52, 0x51, 0xcc, 0x12,
	0x31, 0xb7, 0x47, 0xa4, 0xa2, 0x7f, 0xd6, 0x80, 0xa6, 0x49, 0x56, 0xd2, 0x6d, 0x4b, 0x93, 0xcc,
	0xd2, 0x9b, 0x67, 0xb7, 0x5b, 0x3b, 0xbb, 0x8d, 0x3b, 0xee, 0x8c, 0x76, 0x2a, 0x77, 0x7c, 0xb2,
	0xb8, 0xae, 0x86, 0xea, 0x9e, 0xb3, 0xef, 0x9a, 0xf2, 0xb9, 0x65, 0xf9, 0xdc, 0x6a, 0xd1, 0x06,
	0x7f, 0xce, 0x46, 0x8d, 0xc3, 0xee, 0xf1, 0x6b, 0xb7, 0x5e, 0x5c, 0xb7, 0xde, 0xc9, 0x75, 0xc9,
	0xd4, 0x8f, 0x93, 0x04, 0xba, 0xa6, 0x30, 0xc6, 0xeb, 0x79, 0xcd, 0xab, 0xd2, 0xc0, 0xd2, 0xea,
	0xd5, 0x36, 0xab, 0x5a, 0x57, 0xa7, 0x60, 0x46, 0x6b, 0xa3, 0x05, 0xf4, 0x52, 0x53, 0x9e, 0xff,
	0xed, 0xaa, 0xda, 0xad, 0x5b, 0x77, 0x55, 0xaf, 0xe1, 0xb4, 0x6b, 0xa7, 0x6b, 0xb3, 0x10, 0x20,
	0x56, 0x8f, 0xd3, 0x58, 0x0d, 0x6b, 0x56, 0x37, 0x5f, 0x6e, 0x69, 0xf4, 0x72, 0x9b, 0xd1, 0xe6,
	0x13, 0x9f, 0x76, 0xf4, 0x5c, 0xf5, 0xf5, 0xd3, 0x8f, 0x9f, 0x17, 0x09, 0x11, 0x73, 0x39, 0x73,
	0x43, 0x96, 0x7a, 0xe1, 0x3c, 0x20, 0xc7, 0x47, 0xef, 0x8f, 0xbc, 0xf5, 0x94, 0x77, 0x09, 0xf3,
	0xf8, 0x22, 0xf1, 0xec, 0x71, 0xbb, 0x7c, 0xe6, 0xd5, 0xff, 0x78, 0x3f, 0xd6, 0xa1, 0x59, 0x4b,
	0xe7, 0xfc, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x24, 0x87, 0x83, 0xbc, 0xa8, 0x05, 0x00, 0x00,
}
