// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/chai2010/qingcloud-go/spec.pb/qingcloud_sdk_rule"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import "github.com/chai2010/qingcloud-go/config"
import "github.com/chai2010/qingcloud-go/request"
import "github.com/chai2010/qingcloud-go/request/data"

var _ = config.Config{}
var _ = request.Request{}
var _ = data.Operation{}

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CacheServiceProperties struct {
	Zone string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
}

func (m *CacheServiceProperties) Reset()                    { *m = CacheServiceProperties{} }
func (m *CacheServiceProperties) String() string            { return proto.CompactTextString(m) }
func (*CacheServiceProperties) ProtoMessage()               {}
func (*CacheServiceProperties) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CacheServiceProperties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type DescribeCachesInput struct {
	Caches     []string `protobuf:"bytes,1,rep,name=caches" json:"caches,omitempty"`
	Status     []string `protobuf:"bytes,2,rep,name=status" json:"status,omitempty"`
	CacheType  []string `protobuf:"bytes,3,rep,name=cache_type,json=cacheType" json:"cache_type,omitempty"`
	SearchWord string   `protobuf:"bytes,4,opt,name=search_word,json=searchWord" json:"search_word,omitempty"`
	Tags       []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Verbose    int32    `protobuf:"varint,6,opt,name=verbose" json:"verbose,omitempty"`
	Offset     int32    `protobuf:"varint,7,opt,name=offset" json:"offset,omitempty"`
	Limit      int32    `protobuf:"varint,8,opt,name=limit" json:"limit,omitempty"`
}

func (m *DescribeCachesInput) Reset()                    { *m = DescribeCachesInput{} }
func (m *DescribeCachesInput) String() string            { return proto.CompactTextString(m) }
func (*DescribeCachesInput) ProtoMessage()               {}
func (*DescribeCachesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *DescribeCachesInput) GetCaches() []string {
	if m != nil {
		return m.Caches
	}
	return nil
}

func (m *DescribeCachesInput) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeCachesInput) GetCacheType() []string {
	if m != nil {
		return m.CacheType
	}
	return nil
}

func (m *DescribeCachesInput) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *DescribeCachesInput) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DescribeCachesInput) GetVerbose() int32 {
	if m != nil {
		return m.Verbose
	}
	return 0
}

func (m *DescribeCachesInput) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeCachesInput) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type DescribeCachesOutput struct {
	Action     string                               `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode    int32                                `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message    string                               `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	CacheSet   []*DescribeCachesOutput_ResponseItem `protobuf:"bytes,4,rep,name=cache_set,json=cacheSet" json:"cache_set,omitempty"`
	TotalCount int32                                `protobuf:"varint,5,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
}

func (m *DescribeCachesOutput) Reset()                    { *m = DescribeCachesOutput{} }
func (m *DescribeCachesOutput) String() string            { return proto.CompactTextString(m) }
func (*DescribeCachesOutput) ProtoMessage()               {}
func (*DescribeCachesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DescribeCachesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DescribeCachesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DescribeCachesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DescribeCachesOutput) GetCacheSet() []*DescribeCachesOutput_ResponseItem {
	if m != nil {
		return m.CacheSet
	}
	return nil
}

func (m *DescribeCachesOutput) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type DescribeCachesOutput_ResponseItem struct {
	CacheId               string                      `protobuf:"bytes,1,opt,name=cache_id,json=cacheId" json:"cache_id,omitempty"`
	CacheName             string                      `protobuf:"bytes,2,opt,name=cache_name,json=cacheName" json:"cache_name,omitempty"`
	CacheType             string                      `protobuf:"bytes,3,opt,name=cache_type,json=cacheType" json:"cache_type,omitempty"`
	CachePort             int32                       `protobuf:"varint,4,opt,name=cache_port,json=cachePort" json:"cache_port,omitempty"`
	CacheSize             int32                       `protobuf:"varint,5,opt,name=cache_size,json=cacheSize" json:"cache_size,omitempty"`
	NodeCount             int32                       `protobuf:"varint,6,opt,name=node_count,json=nodeCount" json:"node_count,omitempty"`
	Description           int32                       `protobuf:"varint,7,opt,name=description" json:"description,omitempty"`
	Nodes                 []*CacheNode                `protobuf:"bytes,8,rep,name=nodes" json:"nodes,omitempty"`
	AutoBackupTime        int32                       `protobuf:"varint,9,opt,name=auto_backup_time,json=autoBackupTime" json:"auto_backup_time,omitempty"`
	IsApplied             int32                       `protobuf:"varint,10,opt,name=is_applied,json=isApplied" json:"is_applied,omitempty"`
	Status                string                      `protobuf:"bytes,11,opt,name=status" json:"status,omitempty"`
	TransitionStatus      string                      `protobuf:"bytes,12,opt,name=transition_status,json=transitionStatus" json:"transition_status,omitempty"`
	Vxnet                 map[string]string           `protobuf:"bytes,13,rep,name=vxnet" json:"vxnet,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreateTime            *google_protobuf1.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	StatusTime            *google_protobuf1.Timestamp `protobuf:"bytes,15,opt,name=status_time,json=statusTime" json:"status_time,omitempty"`
	SecurityGroupId       string                      `protobuf:"bytes,16,opt,name=security_group_id,json=securityGroupId" json:"security_group_id,omitempty"`
	CacheParameterGroupId string                      `protobuf:"bytes,17,opt,name=cache_parameter_group_id,json=cacheParameterGroupId" json:"cache_parameter_group_id,omitempty"`
	MaxMemory             float64                     `protobuf:"fixed64,18,opt,name=max_memory,json=maxMemory" json:"max_memory,omitempty"`
}

func (m *DescribeCachesOutput_ResponseItem) Reset()         { *m = DescribeCachesOutput_ResponseItem{} }
func (m *DescribeCachesOutput_ResponseItem) String() string { return proto.CompactTextString(m) }
func (*DescribeCachesOutput_ResponseItem) ProtoMessage()    {}
func (*DescribeCachesOutput_ResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{2, 0}
}

func (m *DescribeCachesOutput_ResponseItem) GetCacheId() string {
	if m != nil {
		return m.CacheId
	}
	return ""
}

func (m *DescribeCachesOutput_ResponseItem) GetCacheName() string {
	if m != nil {
		return m.CacheName
	}
	return ""
}

func (m *DescribeCachesOutput_ResponseItem) GetCacheType() string {
	if m != nil {
		return m.CacheType
	}
	return ""
}

func (m *DescribeCachesOutput_ResponseItem) GetCachePort() int32 {
	if m != nil {
		return m.CachePort
	}
	return 0
}

func (m *DescribeCachesOutput_ResponseItem) GetCacheSize() int32 {
	if m != nil {
		return m.CacheSize
	}
	return 0
}

func (m *DescribeCachesOutput_ResponseItem) GetNodeCount() int32 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func (m *DescribeCachesOutput_ResponseItem) GetDescription() int32 {
	if m != nil {
		return m.Description
	}
	return 0
}

func (m *DescribeCachesOutput_ResponseItem) GetNodes() []*CacheNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *DescribeCachesOutput_ResponseItem) GetAutoBackupTime() int32 {
	if m != nil {
		return m.AutoBackupTime
	}
	return 0
}

func (m *DescribeCachesOutput_ResponseItem) GetIsApplied() int32 {
	if m != nil {
		return m.IsApplied
	}
	return 0
}

func (m *DescribeCachesOutput_ResponseItem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DescribeCachesOutput_ResponseItem) GetTransitionStatus() string {
	if m != nil {
		return m.TransitionStatus
	}
	return ""
}

func (m *DescribeCachesOutput_ResponseItem) GetVxnet() map[string]string {
	if m != nil {
		return m.Vxnet
	}
	return nil
}

func (m *DescribeCachesOutput_ResponseItem) GetCreateTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *DescribeCachesOutput_ResponseItem) GetStatusTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

func (m *DescribeCachesOutput_ResponseItem) GetSecurityGroupId() string {
	if m != nil {
		return m.SecurityGroupId
	}
	return ""
}

func (m *DescribeCachesOutput_ResponseItem) GetCacheParameterGroupId() string {
	if m != nil {
		return m.CacheParameterGroupId
	}
	return ""
}

func (m *DescribeCachesOutput_ResponseItem) GetMaxMemory() float64 {
	if m != nil {
		return m.MaxMemory
	}
	return 0
}

type CreateCacheInput struct {
}

func (m *CreateCacheInput) Reset()                    { *m = CreateCacheInput{} }
func (m *CreateCacheInput) String() string            { return proto.CompactTextString(m) }
func (*CreateCacheInput) ProtoMessage()               {}
func (*CreateCacheInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type CreateCacheOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *CreateCacheOutput) Reset()                    { *m = CreateCacheOutput{} }
func (m *CreateCacheOutput) String() string            { return proto.CompactTextString(m) }
func (*CreateCacheOutput) ProtoMessage()               {}
func (*CreateCacheOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *CreateCacheOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *CreateCacheOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *CreateCacheOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StopCachesInput struct {
}

func (m *StopCachesInput) Reset()                    { *m = StopCachesInput{} }
func (m *StopCachesInput) String() string            { return proto.CompactTextString(m) }
func (*StopCachesInput) ProtoMessage()               {}
func (*StopCachesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type StopCachesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *StopCachesOutput) Reset()                    { *m = StopCachesOutput{} }
func (m *StopCachesOutput) String() string            { return proto.CompactTextString(m) }
func (*StopCachesOutput) ProtoMessage()               {}
func (*StopCachesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *StopCachesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *StopCachesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *StopCachesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StartCachesInput struct {
}

func (m *StartCachesInput) Reset()                    { *m = StartCachesInput{} }
func (m *StartCachesInput) String() string            { return proto.CompactTextString(m) }
func (*StartCachesInput) ProtoMessage()               {}
func (*StartCachesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type StartCachesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *StartCachesOutput) Reset()                    { *m = StartCachesOutput{} }
func (m *StartCachesOutput) String() string            { return proto.CompactTextString(m) }
func (*StartCachesOutput) ProtoMessage()               {}
func (*StartCachesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *StartCachesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *StartCachesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *StartCachesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RestartCachesInput struct {
}

func (m *RestartCachesInput) Reset()                    { *m = RestartCachesInput{} }
func (m *RestartCachesInput) String() string            { return proto.CompactTextString(m) }
func (*RestartCachesInput) ProtoMessage()               {}
func (*RestartCachesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type RestartCachesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *RestartCachesOutput) Reset()                    { *m = RestartCachesOutput{} }
func (m *RestartCachesOutput) String() string            { return proto.CompactTextString(m) }
func (*RestartCachesOutput) ProtoMessage()               {}
func (*RestartCachesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *RestartCachesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *RestartCachesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *RestartCachesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteCachesInput struct {
}

func (m *DeleteCachesInput) Reset()                    { *m = DeleteCachesInput{} }
func (m *DeleteCachesInput) String() string            { return proto.CompactTextString(m) }
func (*DeleteCachesInput) ProtoMessage()               {}
func (*DeleteCachesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type DeleteCachesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *DeleteCachesOutput) Reset()                    { *m = DeleteCachesOutput{} }
func (m *DeleteCachesOutput) String() string            { return proto.CompactTextString(m) }
func (*DeleteCachesOutput) ProtoMessage()               {}
func (*DeleteCachesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *DeleteCachesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DeleteCachesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DeleteCachesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResizeCachesInput struct {
}

func (m *ResizeCachesInput) Reset()                    { *m = ResizeCachesInput{} }
func (m *ResizeCachesInput) String() string            { return proto.CompactTextString(m) }
func (*ResizeCachesInput) ProtoMessage()               {}
func (*ResizeCachesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type ResizeCachesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ResizeCachesOutput) Reset()                    { *m = ResizeCachesOutput{} }
func (m *ResizeCachesOutput) String() string            { return proto.CompactTextString(m) }
func (*ResizeCachesOutput) ProtoMessage()               {}
func (*ResizeCachesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *ResizeCachesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ResizeCachesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ResizeCachesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateCacheInput struct {
}

func (m *UpdateCacheInput) Reset()                    { *m = UpdateCacheInput{} }
func (m *UpdateCacheInput) String() string            { return proto.CompactTextString(m) }
func (*UpdateCacheInput) ProtoMessage()               {}
func (*UpdateCacheInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type UpdateCacheOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *UpdateCacheOutput) Reset()                    { *m = UpdateCacheOutput{} }
func (m *UpdateCacheOutput) String() string            { return proto.CompactTextString(m) }
func (*UpdateCacheOutput) ProtoMessage()               {}
func (*UpdateCacheOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *UpdateCacheOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UpdateCacheOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *UpdateCacheOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChangeCacheVxnetInput struct {
}

func (m *ChangeCacheVxnetInput) Reset()                    { *m = ChangeCacheVxnetInput{} }
func (m *ChangeCacheVxnetInput) String() string            { return proto.CompactTextString(m) }
func (*ChangeCacheVxnetInput) ProtoMessage()               {}
func (*ChangeCacheVxnetInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

type ChangeCacheVxnetOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ChangeCacheVxnetOutput) Reset()                    { *m = ChangeCacheVxnetOutput{} }
func (m *ChangeCacheVxnetOutput) String() string            { return proto.CompactTextString(m) }
func (*ChangeCacheVxnetOutput) ProtoMessage()               {}
func (*ChangeCacheVxnetOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *ChangeCacheVxnetOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ChangeCacheVxnetOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ChangeCacheVxnetOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ModifyCacheAttributesInput struct {
}

func (m *ModifyCacheAttributesInput) Reset()                    { *m = ModifyCacheAttributesInput{} }
func (m *ModifyCacheAttributesInput) String() string            { return proto.CompactTextString(m) }
func (*ModifyCacheAttributesInput) ProtoMessage()               {}
func (*ModifyCacheAttributesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

type ModifyCacheAttributesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ModifyCacheAttributesOutput) Reset()                    { *m = ModifyCacheAttributesOutput{} }
func (m *ModifyCacheAttributesOutput) String() string            { return proto.CompactTextString(m) }
func (*ModifyCacheAttributesOutput) ProtoMessage()               {}
func (*ModifyCacheAttributesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *ModifyCacheAttributesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ModifyCacheAttributesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ModifyCacheAttributesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DescribeCacheNodesInput struct {
}

func (m *DescribeCacheNodesInput) Reset()                    { *m = DescribeCacheNodesInput{} }
func (m *DescribeCacheNodesInput) String() string            { return proto.CompactTextString(m) }
func (*DescribeCacheNodesInput) ProtoMessage()               {}
func (*DescribeCacheNodesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

type DescribeCacheNodesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *DescribeCacheNodesOutput) Reset()                    { *m = DescribeCacheNodesOutput{} }
func (m *DescribeCacheNodesOutput) String() string            { return proto.CompactTextString(m) }
func (*DescribeCacheNodesOutput) ProtoMessage()               {}
func (*DescribeCacheNodesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *DescribeCacheNodesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DescribeCacheNodesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DescribeCacheNodesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddCacheNodesInput struct {
}

func (m *AddCacheNodesInput) Reset()                    { *m = AddCacheNodesInput{} }
func (m *AddCacheNodesInput) String() string            { return proto.CompactTextString(m) }
func (*AddCacheNodesInput) ProtoMessage()               {}
func (*AddCacheNodesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

type AddCacheNodesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *AddCacheNodesOutput) Reset()                    { *m = AddCacheNodesOutput{} }
func (m *AddCacheNodesOutput) String() string            { return proto.CompactTextString(m) }
func (*AddCacheNodesOutput) ProtoMessage()               {}
func (*AddCacheNodesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *AddCacheNodesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AddCacheNodesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *AddCacheNodesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteCacheNodesInput struct {
}

func (m *DeleteCacheNodesInput) Reset()                    { *m = DeleteCacheNodesInput{} }
func (m *DeleteCacheNodesInput) String() string            { return proto.CompactTextString(m) }
func (*DeleteCacheNodesInput) ProtoMessage()               {}
func (*DeleteCacheNodesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

type DeleteCacheNodesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *DeleteCacheNodesOutput) Reset()                    { *m = DeleteCacheNodesOutput{} }
func (m *DeleteCacheNodesOutput) String() string            { return proto.CompactTextString(m) }
func (*DeleteCacheNodesOutput) ProtoMessage()               {}
func (*DeleteCacheNodesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *DeleteCacheNodesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DeleteCacheNodesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DeleteCacheNodesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RestartCacheNodesInput struct {
}

func (m *RestartCacheNodesInput) Reset()                    { *m = RestartCacheNodesInput{} }
func (m *RestartCacheNodesInput) String() string            { return proto.CompactTextString(m) }
func (*RestartCacheNodesInput) ProtoMessage()               {}
func (*RestartCacheNodesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

type RestartCacheNodesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *RestartCacheNodesOutput) Reset()                    { *m = RestartCacheNodesOutput{} }
func (m *RestartCacheNodesOutput) String() string            { return proto.CompactTextString(m) }
func (*RestartCacheNodesOutput) ProtoMessage()               {}
func (*RestartCacheNodesOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *RestartCacheNodesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *RestartCacheNodesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *RestartCacheNodesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ModifyCacheNodeAttributesInput struct {
}

func (m *ModifyCacheNodeAttributesInput) Reset()                    { *m = ModifyCacheNodeAttributesInput{} }
func (m *ModifyCacheNodeAttributesInput) String() string            { return proto.CompactTextString(m) }
func (*ModifyCacheNodeAttributesInput) ProtoMessage()               {}
func (*ModifyCacheNodeAttributesInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

type ModifyCacheNodeAttributesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ModifyCacheNodeAttributesOutput) Reset()         { *m = ModifyCacheNodeAttributesOutput{} }
func (m *ModifyCacheNodeAttributesOutput) String() string { return proto.CompactTextString(m) }
func (*ModifyCacheNodeAttributesOutput) ProtoMessage()    {}
func (*ModifyCacheNodeAttributesOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{30}
}

func (m *ModifyCacheNodeAttributesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ModifyCacheNodeAttributesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ModifyCacheNodeAttributesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateCacheFromSnapshotInput struct {
}

func (m *CreateCacheFromSnapshotInput) Reset()                    { *m = CreateCacheFromSnapshotInput{} }
func (m *CreateCacheFromSnapshotInput) String() string            { return proto.CompactTextString(m) }
func (*CreateCacheFromSnapshotInput) ProtoMessage()               {}
func (*CreateCacheFromSnapshotInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

type CreateCacheFromSnapshotOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *CreateCacheFromSnapshotOutput) Reset()                    { *m = CreateCacheFromSnapshotOutput{} }
func (m *CreateCacheFromSnapshotOutput) String() string            { return proto.CompactTextString(m) }
func (*CreateCacheFromSnapshotOutput) ProtoMessage()               {}
func (*CreateCacheFromSnapshotOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{32} }

func (m *CreateCacheFromSnapshotOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *CreateCacheFromSnapshotOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *CreateCacheFromSnapshotOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DescribeCacheParameterGroupsInput struct {
}

func (m *DescribeCacheParameterGroupsInput) Reset()         { *m = DescribeCacheParameterGroupsInput{} }
func (m *DescribeCacheParameterGroupsInput) String() string { return proto.CompactTextString(m) }
func (*DescribeCacheParameterGroupsInput) ProtoMessage()    {}
func (*DescribeCacheParameterGroupsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{33}
}

type DescribeCacheParameterGroupsOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *DescribeCacheParameterGroupsOutput) Reset()         { *m = DescribeCacheParameterGroupsOutput{} }
func (m *DescribeCacheParameterGroupsOutput) String() string { return proto.CompactTextString(m) }
func (*DescribeCacheParameterGroupsOutput) ProtoMessage()    {}
func (*DescribeCacheParameterGroupsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{34}
}

func (m *DescribeCacheParameterGroupsOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DescribeCacheParameterGroupsOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DescribeCacheParameterGroupsOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateCacheParameterGroupInput struct {
}

func (m *CreateCacheParameterGroupInput) Reset()                    { *m = CreateCacheParameterGroupInput{} }
func (m *CreateCacheParameterGroupInput) String() string            { return proto.CompactTextString(m) }
func (*CreateCacheParameterGroupInput) ProtoMessage()               {}
func (*CreateCacheParameterGroupInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{35} }

type CreateCacheParameterGroupOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *CreateCacheParameterGroupOutput) Reset()         { *m = CreateCacheParameterGroupOutput{} }
func (m *CreateCacheParameterGroupOutput) String() string { return proto.CompactTextString(m) }
func (*CreateCacheParameterGroupOutput) ProtoMessage()    {}
func (*CreateCacheParameterGroupOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{36}
}

func (m *CreateCacheParameterGroupOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *CreateCacheParameterGroupOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *CreateCacheParameterGroupOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ApplyCacheParameterGroupInput struct {
}

func (m *ApplyCacheParameterGroupInput) Reset()                    { *m = ApplyCacheParameterGroupInput{} }
func (m *ApplyCacheParameterGroupInput) String() string            { return proto.CompactTextString(m) }
func (*ApplyCacheParameterGroupInput) ProtoMessage()               {}
func (*ApplyCacheParameterGroupInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{37} }

type ApplyCacheParameterGroupOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ApplyCacheParameterGroupOutput) Reset()                    { *m = ApplyCacheParameterGroupOutput{} }
func (m *ApplyCacheParameterGroupOutput) String() string            { return proto.CompactTextString(m) }
func (*ApplyCacheParameterGroupOutput) ProtoMessage()               {}
func (*ApplyCacheParameterGroupOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{38} }

func (m *ApplyCacheParameterGroupOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ApplyCacheParameterGroupOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ApplyCacheParameterGroupOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteCacheParameterGroupsInput struct {
}

func (m *DeleteCacheParameterGroupsInput) Reset()         { *m = DeleteCacheParameterGroupsInput{} }
func (m *DeleteCacheParameterGroupsInput) String() string { return proto.CompactTextString(m) }
func (*DeleteCacheParameterGroupsInput) ProtoMessage()    {}
func (*DeleteCacheParameterGroupsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{39}
}

type DeleteCacheParameterGroupsOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *DeleteCacheParameterGroupsOutput) Reset()         { *m = DeleteCacheParameterGroupsOutput{} }
func (m *DeleteCacheParameterGroupsOutput) String() string { return proto.CompactTextString(m) }
func (*DeleteCacheParameterGroupsOutput) ProtoMessage()    {}
func (*DeleteCacheParameterGroupsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{40}
}

func (m *DeleteCacheParameterGroupsOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DeleteCacheParameterGroupsOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DeleteCacheParameterGroupsOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ModifyCacheParameterGroupAttributesInput struct {
}

func (m *ModifyCacheParameterGroupAttributesInput) Reset() {
	*m = ModifyCacheParameterGroupAttributesInput{}
}
func (m *ModifyCacheParameterGroupAttributesInput) String() string { return proto.CompactTextString(m) }
func (*ModifyCacheParameterGroupAttributesInput) ProtoMessage()    {}
func (*ModifyCacheParameterGroupAttributesInput) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{41}
}

type ModifyCacheParameterGroupAttributesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ModifyCacheParameterGroupAttributesOutput) Reset() {
	*m = ModifyCacheParameterGroupAttributesOutput{}
}
func (m *ModifyCacheParameterGroupAttributesOutput) String() string { return proto.CompactTextString(m) }
func (*ModifyCacheParameterGroupAttributesOutput) ProtoMessage()    {}
func (*ModifyCacheParameterGroupAttributesOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{42}
}

func (m *ModifyCacheParameterGroupAttributesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ModifyCacheParameterGroupAttributesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ModifyCacheParameterGroupAttributesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DescribeCacheParametersInput struct {
}

func (m *DescribeCacheParametersInput) Reset()                    { *m = DescribeCacheParametersInput{} }
func (m *DescribeCacheParametersInput) String() string            { return proto.CompactTextString(m) }
func (*DescribeCacheParametersInput) ProtoMessage()               {}
func (*DescribeCacheParametersInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{43} }

type DescribeCacheParametersOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *DescribeCacheParametersOutput) Reset()                    { *m = DescribeCacheParametersOutput{} }
func (m *DescribeCacheParametersOutput) String() string            { return proto.CompactTextString(m) }
func (*DescribeCacheParametersOutput) ProtoMessage()               {}
func (*DescribeCacheParametersOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{44} }

func (m *DescribeCacheParametersOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DescribeCacheParametersOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DescribeCacheParametersOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateCacheParametersInput struct {
}

func (m *UpdateCacheParametersInput) Reset()                    { *m = UpdateCacheParametersInput{} }
func (m *UpdateCacheParametersInput) String() string            { return proto.CompactTextString(m) }
func (*UpdateCacheParametersInput) ProtoMessage()               {}
func (*UpdateCacheParametersInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{45} }

type UpdateCacheParametersOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *UpdateCacheParametersOutput) Reset()                    { *m = UpdateCacheParametersOutput{} }
func (m *UpdateCacheParametersOutput) String() string            { return proto.CompactTextString(m) }
func (*UpdateCacheParametersOutput) ProtoMessage()               {}
func (*UpdateCacheParametersOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{46} }

func (m *UpdateCacheParametersOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UpdateCacheParametersOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *UpdateCacheParametersOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResetCacheParametersInput struct {
}

func (m *ResetCacheParametersInput) Reset()                    { *m = ResetCacheParametersInput{} }
func (m *ResetCacheParametersInput) String() string            { return proto.CompactTextString(m) }
func (*ResetCacheParametersInput) ProtoMessage()               {}
func (*ResetCacheParametersInput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{47} }

type ResetCacheParametersOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ResetCacheParametersOutput) Reset()                    { *m = ResetCacheParametersOutput{} }
func (m *ResetCacheParametersOutput) String() string            { return proto.CompactTextString(m) }
func (*ResetCacheParametersOutput) ProtoMessage()               {}
func (*ResetCacheParametersOutput) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{48} }

func (m *ResetCacheParametersOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ResetCacheParametersOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ResetCacheParametersOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CacheServiceProperties)(nil), "service.CacheServiceProperties")
	proto.RegisterType((*DescribeCachesInput)(nil), "service.DescribeCachesInput")
	proto.RegisterType((*DescribeCachesOutput)(nil), "service.DescribeCachesOutput")
	proto.RegisterType((*DescribeCachesOutput_ResponseItem)(nil), "service.DescribeCachesOutput.ResponseItem")
	proto.RegisterType((*CreateCacheInput)(nil), "service.CreateCacheInput")
	proto.RegisterType((*CreateCacheOutput)(nil), "service.CreateCacheOutput")
	proto.RegisterType((*StopCachesInput)(nil), "service.StopCachesInput")
	proto.RegisterType((*StopCachesOutput)(nil), "service.StopCachesOutput")
	proto.RegisterType((*StartCachesInput)(nil), "service.StartCachesInput")
	proto.RegisterType((*StartCachesOutput)(nil), "service.StartCachesOutput")
	proto.RegisterType((*RestartCachesInput)(nil), "service.RestartCachesInput")
	proto.RegisterType((*RestartCachesOutput)(nil), "service.RestartCachesOutput")
	proto.RegisterType((*DeleteCachesInput)(nil), "service.DeleteCachesInput")
	proto.RegisterType((*DeleteCachesOutput)(nil), "service.DeleteCachesOutput")
	proto.RegisterType((*ResizeCachesInput)(nil), "service.ResizeCachesInput")
	proto.RegisterType((*ResizeCachesOutput)(nil), "service.ResizeCachesOutput")
	proto.RegisterType((*UpdateCacheInput)(nil), "service.UpdateCacheInput")
	proto.RegisterType((*UpdateCacheOutput)(nil), "service.UpdateCacheOutput")
	proto.RegisterType((*ChangeCacheVxnetInput)(nil), "service.ChangeCacheVxnetInput")
	proto.RegisterType((*ChangeCacheVxnetOutput)(nil), "service.ChangeCacheVxnetOutput")
	proto.RegisterType((*ModifyCacheAttributesInput)(nil), "service.ModifyCacheAttributesInput")
	proto.RegisterType((*ModifyCacheAttributesOutput)(nil), "service.ModifyCacheAttributesOutput")
	proto.RegisterType((*DescribeCacheNodesInput)(nil), "service.DescribeCacheNodesInput")
	proto.RegisterType((*DescribeCacheNodesOutput)(nil), "service.DescribeCacheNodesOutput")
	proto.RegisterType((*AddCacheNodesInput)(nil), "service.AddCacheNodesInput")
	proto.RegisterType((*AddCacheNodesOutput)(nil), "service.AddCacheNodesOutput")
	proto.RegisterType((*DeleteCacheNodesInput)(nil), "service.DeleteCacheNodesInput")
	proto.RegisterType((*DeleteCacheNodesOutput)(nil), "service.DeleteCacheNodesOutput")
	proto.RegisterType((*RestartCacheNodesInput)(nil), "service.RestartCacheNodesInput")
	proto.RegisterType((*RestartCacheNodesOutput)(nil), "service.RestartCacheNodesOutput")
	proto.RegisterType((*ModifyCacheNodeAttributesInput)(nil), "service.ModifyCacheNodeAttributesInput")
	proto.RegisterType((*ModifyCacheNodeAttributesOutput)(nil), "service.ModifyCacheNodeAttributesOutput")
	proto.RegisterType((*CreateCacheFromSnapshotInput)(nil), "service.CreateCacheFromSnapshotInput")
	proto.RegisterType((*CreateCacheFromSnapshotOutput)(nil), "service.CreateCacheFromSnapshotOutput")
	proto.RegisterType((*DescribeCacheParameterGroupsInput)(nil), "service.DescribeCacheParameterGroupsInput")
	proto.RegisterType((*DescribeCacheParameterGroupsOutput)(nil), "service.DescribeCacheParameterGroupsOutput")
	proto.RegisterType((*CreateCacheParameterGroupInput)(nil), "service.CreateCacheParameterGroupInput")
	proto.RegisterType((*CreateCacheParameterGroupOutput)(nil), "service.CreateCacheParameterGroupOutput")
	proto.RegisterType((*ApplyCacheParameterGroupInput)(nil), "service.ApplyCacheParameterGroupInput")
	proto.RegisterType((*ApplyCacheParameterGroupOutput)(nil), "service.ApplyCacheParameterGroupOutput")
	proto.RegisterType((*DeleteCacheParameterGroupsInput)(nil), "service.DeleteCacheParameterGroupsInput")
	proto.RegisterType((*DeleteCacheParameterGroupsOutput)(nil), "service.DeleteCacheParameterGroupsOutput")
	proto.RegisterType((*ModifyCacheParameterGroupAttributesInput)(nil), "service.ModifyCacheParameterGroupAttributesInput")
	proto.RegisterType((*ModifyCacheParameterGroupAttributesOutput)(nil), "service.ModifyCacheParameterGroupAttributesOutput")
	proto.RegisterType((*DescribeCacheParametersInput)(nil), "service.DescribeCacheParametersInput")
	proto.RegisterType((*DescribeCacheParametersOutput)(nil), "service.DescribeCacheParametersOutput")
	proto.RegisterType((*UpdateCacheParametersInput)(nil), "service.UpdateCacheParametersInput")
	proto.RegisterType((*UpdateCacheParametersOutput)(nil), "service.UpdateCacheParametersOutput")
	proto.RegisterType((*ResetCacheParametersInput)(nil), "service.ResetCacheParametersInput")
	proto.RegisterType((*ResetCacheParametersOutput)(nil), "service.ResetCacheParametersOutput")
}

type CacheServiceInterface interface {
	DescribeCaches(in *DescribeCachesInput) (out *DescribeCachesOutput, err error)
	CreateCache(in *CreateCacheInput) (out *CreateCacheOutput, err error)
	StopCaches(in *StopCachesInput) (out *StopCachesOutput, err error)
	StartCaches(in *StartCachesInput) (out *StartCachesOutput, err error)
	RestartCaches(in *RestartCachesInput) (out *RestartCachesOutput, err error)
	DeleteCaches(in *DeleteCachesInput) (out *DeleteCachesOutput, err error)
	ResizeCaches(in *ResizeCachesInput) (out *ResizeCachesOutput, err error)
	UpdateCache(in *UpdateCacheInput) (out *UpdateCacheOutput, err error)
	ChangeCacheVxnet(in *ChangeCacheVxnetInput) (out *ChangeCacheVxnetOutput, err error)
	ModifyCacheAttributes(in *ModifyCacheAttributesInput) (out *ModifyCacheAttributesOutput, err error)
	DescribeCacheNodes(in *DescribeCacheNodesInput) (out *DescribeCacheNodesOutput, err error)
	AddCacheNodes(in *AddCacheNodesInput) (out *AddCacheNodesOutput, err error)
	DeleteCacheNodes(in *DeleteCacheNodesInput) (out *DeleteCacheNodesOutput, err error)
	RestartCacheNodes(in *RestartCacheNodesInput) (out *RestartCacheNodesOutput, err error)
	ModifyCacheNodeAttributes(in *ModifyCacheNodeAttributesInput) (out *ModifyCacheNodeAttributesOutput, err error)
	CreateCacheFromSnapshot(in *CreateCacheFromSnapshotInput) (out *CreateCacheFromSnapshotOutput, err error)
	DescribeCacheParameterGroups(in *DescribeCacheParameterGroupsInput) (out *DescribeCacheParameterGroupsOutput, err error)
	CreateCacheParameterGroup(in *CreateCacheParameterGroupInput) (out *CreateCacheParameterGroupOutput, err error)
	ApplyCacheParameterGroup(in *ApplyCacheParameterGroupInput) (out *ApplyCacheParameterGroupOutput, err error)
	DeleteCacheParameterGroups(in *DeleteCacheParameterGroupsInput) (out *DeleteCacheParameterGroupsOutput, err error)
	ModifyCacheParameterGroupAttributes(in *ModifyCacheParameterGroupAttributesInput) (out *ModifyCacheParameterGroupAttributesOutput, err error)
	DescribeCacheParameters(in *DescribeCacheParametersInput) (out *DescribeCacheParametersOutput, err error)
	UpdateCacheParameters(in *UpdateCacheParametersInput) (out *UpdateCacheParametersOutput, err error)
	ResetCacheParameters(in *ResetCacheParametersInput) (out *ResetCacheParametersOutput, err error)
}

type CacheService struct {
	Config           *config.Config
	Properties       *CacheServiceProperties
	LastResponseBody string
}

func NewCacheService(conf *config.Config, zone string) (p *CacheService) {
	return &CacheService{
		Config:     conf,
		Properties: &CacheServiceProperties{Zone: zone},
	}
}

func (s *QingCloudService) Cache(zone string) (*CacheService, error) {
	properties := &CacheServiceProperties{
		Zone: zone,
	}

	return &CacheService{Config: s.Config, Properties: properties}, nil
}

func (p *CacheService) DescribeCaches(in *DescribeCachesInput) (out *DescribeCachesOutput, err error) {
	if in == nil {
		in = &DescribeCachesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeCaches",
		RequestMethod: "GET", // GET or POST
	}

	x := &DescribeCachesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DescribeCachesInput) Validate() error {
	return nil
}

func (p *CacheService) CreateCache(in *CreateCacheInput) (out *CreateCacheOutput, err error) {
	if in == nil {
		in = &CreateCacheInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateCache",
		RequestMethod: "GET", // GET or POST
	}

	x := &CreateCacheOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *CreateCacheInput) Validate() error {
	return nil
}

func (p *CacheService) StopCaches(in *StopCachesInput) (out *StopCachesOutput, err error) {
	if in == nil {
		in = &StopCachesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "StopCaches",
		RequestMethod: "GET", // GET or POST
	}

	x := &StopCachesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *StopCachesInput) Validate() error {
	return nil
}

func (p *CacheService) StartCaches(in *StartCachesInput) (out *StartCachesOutput, err error) {
	if in == nil {
		in = &StartCachesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "StartCaches",
		RequestMethod: "GET", // GET or POST
	}

	x := &StartCachesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *StartCachesInput) Validate() error {
	return nil
}

func (p *CacheService) RestartCaches(in *RestartCachesInput) (out *RestartCachesOutput, err error) {
	if in == nil {
		in = &RestartCachesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "RestartCaches",
		RequestMethod: "GET", // GET or POST
	}

	x := &RestartCachesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *RestartCachesInput) Validate() error {
	return nil
}

func (p *CacheService) DeleteCaches(in *DeleteCachesInput) (out *DeleteCachesOutput, err error) {
	if in == nil {
		in = &DeleteCachesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteCaches",
		RequestMethod: "GET", // GET or POST
	}

	x := &DeleteCachesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DeleteCachesInput) Validate() error {
	return nil
}

func (p *CacheService) ResizeCaches(in *ResizeCachesInput) (out *ResizeCachesOutput, err error) {
	if in == nil {
		in = &ResizeCachesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ResizeCaches",
		RequestMethod: "GET", // GET or POST
	}

	x := &ResizeCachesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ResizeCachesInput) Validate() error {
	return nil
}

func (p *CacheService) UpdateCache(in *UpdateCacheInput) (out *UpdateCacheOutput, err error) {
	if in == nil {
		in = &UpdateCacheInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "UpdateCache",
		RequestMethod: "GET", // GET or POST
	}

	x := &UpdateCacheOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *UpdateCacheInput) Validate() error {
	return nil
}

func (p *CacheService) ChangeCacheVxnet(in *ChangeCacheVxnetInput) (out *ChangeCacheVxnetOutput, err error) {
	if in == nil {
		in = &ChangeCacheVxnetInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ChangeCacheVxnet",
		RequestMethod: "GET", // GET or POST
	}

	x := &ChangeCacheVxnetOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ChangeCacheVxnetInput) Validate() error {
	return nil
}

func (p *CacheService) ModifyCacheAttributes(in *ModifyCacheAttributesInput) (out *ModifyCacheAttributesOutput, err error) {
	if in == nil {
		in = &ModifyCacheAttributesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyCacheAttributes",
		RequestMethod: "GET", // GET or POST
	}

	x := &ModifyCacheAttributesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ModifyCacheAttributesInput) Validate() error {
	return nil
}

func (p *CacheService) DescribeCacheNodes(in *DescribeCacheNodesInput) (out *DescribeCacheNodesOutput, err error) {
	if in == nil {
		in = &DescribeCacheNodesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeCacheNodes",
		RequestMethod: "GET", // GET or POST
	}

	x := &DescribeCacheNodesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DescribeCacheNodesInput) Validate() error {
	return nil
}

func (p *CacheService) AddCacheNodes(in *AddCacheNodesInput) (out *AddCacheNodesOutput, err error) {
	if in == nil {
		in = &AddCacheNodesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "AddCacheNodes",
		RequestMethod: "GET", // GET or POST
	}

	x := &AddCacheNodesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *AddCacheNodesInput) Validate() error {
	return nil
}

func (p *CacheService) DeleteCacheNodes(in *DeleteCacheNodesInput) (out *DeleteCacheNodesOutput, err error) {
	if in == nil {
		in = &DeleteCacheNodesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteCacheNodes",
		RequestMethod: "GET", // GET or POST
	}

	x := &DeleteCacheNodesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DeleteCacheNodesInput) Validate() error {
	return nil
}

func (p *CacheService) RestartCacheNodes(in *RestartCacheNodesInput) (out *RestartCacheNodesOutput, err error) {
	if in == nil {
		in = &RestartCacheNodesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "RestartCacheNodes",
		RequestMethod: "GET", // GET or POST
	}

	x := &RestartCacheNodesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *RestartCacheNodesInput) Validate() error {
	return nil
}

func (p *CacheService) ModifyCacheNodeAttributes(in *ModifyCacheNodeAttributesInput) (out *ModifyCacheNodeAttributesOutput, err error) {
	if in == nil {
		in = &ModifyCacheNodeAttributesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyCacheNodeAttributes",
		RequestMethod: "GET", // GET or POST
	}

	x := &ModifyCacheNodeAttributesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ModifyCacheNodeAttributesInput) Validate() error {
	return nil
}

func (p *CacheService) CreateCacheFromSnapshot(in *CreateCacheFromSnapshotInput) (out *CreateCacheFromSnapshotOutput, err error) {
	if in == nil {
		in = &CreateCacheFromSnapshotInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateCacheFromSnapshot",
		RequestMethod: "GET", // GET or POST
	}

	x := &CreateCacheFromSnapshotOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *CreateCacheFromSnapshotInput) Validate() error {
	return nil
}

func (p *CacheService) DescribeCacheParameterGroups(in *DescribeCacheParameterGroupsInput) (out *DescribeCacheParameterGroupsOutput, err error) {
	if in == nil {
		in = &DescribeCacheParameterGroupsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeCacheParameterGroups",
		RequestMethod: "GET", // GET or POST
	}

	x := &DescribeCacheParameterGroupsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DescribeCacheParameterGroupsInput) Validate() error {
	return nil
}

func (p *CacheService) CreateCacheParameterGroup(in *CreateCacheParameterGroupInput) (out *CreateCacheParameterGroupOutput, err error) {
	if in == nil {
		in = &CreateCacheParameterGroupInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateCacheParameterGroup",
		RequestMethod: "GET", // GET or POST
	}

	x := &CreateCacheParameterGroupOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *CreateCacheParameterGroupInput) Validate() error {
	return nil
}

func (p *CacheService) ApplyCacheParameterGroup(in *ApplyCacheParameterGroupInput) (out *ApplyCacheParameterGroupOutput, err error) {
	if in == nil {
		in = &ApplyCacheParameterGroupInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ApplyCacheParameterGroup",
		RequestMethod: "GET", // GET or POST
	}

	x := &ApplyCacheParameterGroupOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ApplyCacheParameterGroupInput) Validate() error {
	return nil
}

func (p *CacheService) DeleteCacheParameterGroups(in *DeleteCacheParameterGroupsInput) (out *DeleteCacheParameterGroupsOutput, err error) {
	if in == nil {
		in = &DeleteCacheParameterGroupsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteCacheParameterGroups",
		RequestMethod: "GET", // GET or POST
	}

	x := &DeleteCacheParameterGroupsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DeleteCacheParameterGroupsInput) Validate() error {
	return nil
}

func (p *CacheService) ModifyCacheParameterGroupAttributes(in *ModifyCacheParameterGroupAttributesInput) (out *ModifyCacheParameterGroupAttributesOutput, err error) {
	if in == nil {
		in = &ModifyCacheParameterGroupAttributesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyCacheParameterGroupAttributes",
		RequestMethod: "GET", // GET or POST
	}

	x := &ModifyCacheParameterGroupAttributesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ModifyCacheParameterGroupAttributesInput) Validate() error {
	return nil
}

func (p *CacheService) DescribeCacheParameters(in *DescribeCacheParametersInput) (out *DescribeCacheParametersOutput, err error) {
	if in == nil {
		in = &DescribeCacheParametersInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeCacheParameters",
		RequestMethod: "GET", // GET or POST
	}

	x := &DescribeCacheParametersOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DescribeCacheParametersInput) Validate() error {
	return nil
}

func (p *CacheService) UpdateCacheParameters(in *UpdateCacheParametersInput) (out *UpdateCacheParametersOutput, err error) {
	if in == nil {
		in = &UpdateCacheParametersInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "UpdateCacheParameters",
		RequestMethod: "GET", // GET or POST
	}

	x := &UpdateCacheParametersOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *UpdateCacheParametersInput) Validate() error {
	return nil
}

func (p *CacheService) ResetCacheParameters(in *ResetCacheParametersInput) (out *ResetCacheParametersOutput, err error) {
	if in == nil {
		in = &ResetCacheParametersInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ResetCacheParameters",
		RequestMethod: "GET", // GET or POST
	}

	x := &ResetCacheParametersOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ResetCacheParametersInput) Validate() error {
	return nil
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdb, 0x72, 0xdb, 0x36,
	0x10, 0x1d, 0xc5, 0x96, 0x2f, 0x2b, 0x27, 0x91, 0xe0, 0x1b, 0x4d, 0xdf, 0x14, 0xb9, 0x6d, 0x94,
	0xa4, 0xa3, 0x4c, 0xdd, 0xe9, 0x34, 0xd3, 0x3c, 0xb9, 0x4e, 0x9b, 0x71, 0x3b, 0x49, 0x53, 0x29,
	0x4d, 0xa7, 0x4f, 0x0c, 0x25, 0xc2, 0x32, 0x63, 0x91, 0x60, 0x08, 0xd0, 0xb1, 0xf2, 0x09, 0x9d,
	0xfe, 0x45, 0xff, 0xa9, 0xef, 0xfd, 0x84, 0x4e, 0x7f, 0xa0, 0x83, 0x8b, 0x4c, 0x90, 0x02, 0x65,
	0xf7, 0x81, 0x2f, 0x1e, 0x63, 0x77, 0x81, 0x73, 0xb0, 0xbb, 0x00, 0x0f, 0x04, 0xb5, 0x81, 0x3b,
	0x38, 0xc3, 0x9d, 0x28, 0x26, 0x8c, 0xa0, 0x45, 0x8a, 0xe3, 0x0b, 0x7f, 0x80, 0xed, 0x1a, 0x1b,
	0x47, 0x98, 0x4a, 0xab, 0xbd, 0xfb, 0xde, 0x0f, 0x87, 0x83, 0x11, 0x49, 0x3c, 0x87, 0x7a, 0xe7,
	0x4e, 0x9c, 0x8c, 0xf0, 0x63, 0xfe, 0x47, 0xb9, 0xf7, 0x87, 0x84, 0x0c, 0x47, 0xf8, 0xb1, 0x18,
	0xf5, 0x93, 0xd3, 0xc7, 0xcc, 0x0f, 0x30, 0x65, 0x6e, 0x10, 0xc9, 0x80, 0xd6, 0xe7, 0xb0, 0x71,
	0xcc, 0x41, 0x7a, 0x72, 0xf1, 0x57, 0x31, 0x89, 0x70, 0xcc, 0x7c, 0x4c, 0x11, 0x82, 0xf9, 0x8f,
	0x24, 0xc4, 0x56, 0xa5, 0x59, 0x69, 0x2f, 0x77, 0xc5, 0xff, 0xad, 0xbf, 0x2b, 0xb0, 0xfa, 0x0c,
	0xd3, 0x41, 0xec, 0xf7, 0xb1, 0x98, 0x46, 0x4f, 0xc2, 0x28, 0x61, 0x68, 0x03, 0x16, 0x04, 0x55,
	0x6a, 0x55, 0x9a, 0x73, 0xed, 0xe5, 0xae, 0x1a, 0x71, 0x3b, 0x65, 0x2e, 0x4b, 0xa8, 0x75, 0x4b,
	0xda, 0xe5, 0x08, 0xed, 0x02, 0x88, 0x08, 0x87, 0x6f, 0xc5, 0x9a, 0x13, 0xbe, 0x65, 0x61, 0x79,
	0x3d, 0x8e, 0x30, 0xda, 0x87, 0x1a, 0xc5, 0x6e, 0x3c, 0x38, 0x73, 0x3e, 0x90, 0xd8, 0xb3, 0xe6,
	0x05, 0x03, 0x90, 0xa6, 0x5f, 0x49, 0xec, 0x71, 0x6e, 0xcc, 0x1d, 0x52, 0xab, 0x2a, 0x66, 0x8a,
	0xff, 0x91, 0x05, 0x8b, 0x17, 0x38, 0xee, 0x13, 0x8a, 0xad, 0x85, 0x66, 0xa5, 0x5d, 0xed, 0x4e,
	0x86, 0x9c, 0x05, 0x39, 0x3d, 0xa5, 0x98, 0x59, 0x8b, 0xc2, 0xa1, 0x46, 0x68, 0x0d, 0xaa, 0x23,
	0x3f, 0xf0, 0x99, 0xb5, 0x24, 0xcc, 0x72, 0xd0, 0xfa, 0x77, 0x11, 0xd6, 0xb2, 0x7b, 0xfc, 0x29,
	0x61, 0x6a, 0x93, 0xee, 0x80, 0xf9, 0x24, 0x54, 0x29, 0x51, 0x23, 0xb4, 0x05, 0x4b, 0x31, 0x66,
	0xce, 0x80, 0x78, 0xd8, 0xba, 0x25, 0x91, 0x63, 0xcc, 0x8e, 0x89, 0x87, 0x39, 0xa7, 0x00, 0x53,
	0xea, 0x0e, 0xf9, 0x26, 0xf9, 0x9c, 0xc9, 0x10, 0x3d, 0x07, 0xb9, 0x5f, 0x87, 0xd3, 0x9a, 0x6f,
	0xce, 0xb5, 0x6b, 0x87, 0x0f, 0x3b, 0xaa, 0xc2, 0x1d, 0x13, 0x7c, 0xa7, 0x8b, 0x69, 0x44, 0x42,
	0x8a, 0x4f, 0x18, 0x0e, 0xba, 0x4b, 0x03, 0x59, 0x34, 0xc6, 0x73, 0xc5, 0x08, 0x73, 0x47, 0xce,
	0x80, 0x24, 0x21, 0xb3, 0xaa, 0x82, 0x00, 0x08, 0xd3, 0x31, 0xb7, 0xd8, 0x7f, 0x2e, 0xc0, 0x8a,
	0x3e, 0x97, 0xf3, 0x95, 0xd0, 0xbe, 0xa7, 0x76, 0xb2, 0x28, 0xc6, 0x27, 0x5e, 0x5a, 0x97, 0xd0,
	0x0d, 0xe4, 0x66, 0x26, 0x75, 0x79, 0xe9, 0x06, 0x78, 0xaa, 0x6c, 0x95, 0x6c, 0xd9, 0xae, 0xdc,
	0x11, 0x89, 0x99, 0xa8, 0x5a, 0x55, 0xb9, 0x5f, 0x91, 0x98, 0xa5, 0x6e, 0xea, 0x7f, 0xc4, 0x8a,
	0xa8, 0x74, 0xf7, 0xfc, 0x8f, 0x62, 0x76, 0x48, 0x3c, 0xac, 0xf6, 0x21, 0x4b, 0xb8, 0xcc, 0x2d,
	0x62, 0x1b, 0xa8, 0x09, 0x35, 0x4f, 0xa4, 0x25, 0x12, 0x25, 0x90, 0x95, 0xd4, 0x4d, 0xa8, 0x0d,
	0x55, 0x1e, 0x4e, 0xad, 0x25, 0x91, 0x4e, 0x74, 0x95, 0x4e, 0x91, 0xc6, 0x97, 0xc4, 0xc3, 0x5d,
	0x19, 0x80, 0xda, 0x50, 0x77, 0x13, 0x46, 0x9c, 0xbe, 0x3b, 0x38, 0x4f, 0x22, 0x87, 0x9f, 0x09,
	0x6b, 0x59, 0x2c, 0x78, 0x87, 0xdb, 0xbf, 0x15, 0xe6, 0xd7, 0xbe, 0xdc, 0xb1, 0x4f, 0x1d, 0x37,
	0x8a, 0x46, 0x3e, 0xf6, 0x2c, 0x90, 0xa4, 0x7c, 0x7a, 0x24, 0x0d, 0x5a, 0x7f, 0xd7, 0x64, 0x4b,
	0xa8, 0xfe, 0x7e, 0x04, 0x0d, 0x16, 0xbb, 0x21, 0xf5, 0x39, 0x31, 0x47, 0x85, 0xac, 0x88, 0x90,
	0x7a, 0xea, 0xe8, 0xc9, 0xe0, 0x1f, 0xa1, 0x7a, 0x71, 0x19, 0x62, 0x66, 0xdd, 0x16, 0xbc, 0xbf,
	0xba, 0x79, 0x1b, 0x74, 0xde, 0xf0, 0x79, 0xdf, 0x85, 0x2c, 0x1e, 0x77, 0xe5, 0x1a, 0xe8, 0x29,
	0xd4, 0x06, 0x31, 0x76, 0x19, 0x96, 0xbb, 0xba, 0xd3, 0xac, 0xb4, 0x6b, 0x87, 0x76, 0x47, 0x5e,
	0x03, 0x9d, 0xc9, 0x35, 0xd0, 0x79, 0x3d, 0xb9, 0x06, 0xba, 0x20, 0xc3, 0xc5, 0x6e, 0x9f, 0x42,
	0x4d, 0x72, 0x95, 0x93, 0xef, 0x5e, 0x3f, 0x59, 0x86, 0x8b, 0xc9, 0x0f, 0xa1, 0x41, 0xf1, 0x20,
	0x89, 0x7d, 0x36, 0x76, 0x86, 0x31, 0x49, 0x22, 0xde, 0x5f, 0x75, 0xb1, 0xe7, 0xbb, 0x13, 0xc7,
	0x73, 0x6e, 0x3f, 0xf1, 0xd0, 0xd7, 0x60, 0xa9, 0x4e, 0x71, 0x63, 0x37, 0xc0, 0x0c, 0xc7, 0xe9,
	0x94, 0x86, 0x98, 0xb2, 0x2e, 0xfb, 0x66, 0xe2, 0x9e, 0x4c, 0xdc, 0x05, 0x08, 0xdc, 0x4b, 0x27,
	0xc0, 0x01, 0x89, 0xc7, 0x16, 0x6a, 0x56, 0xda, 0x95, 0xee, 0x72, 0xe0, 0x5e, 0xbe, 0x10, 0x06,
	0xfb, 0x09, 0x40, 0x9a, 0x12, 0x54, 0x87, 0xb9, 0x73, 0x3c, 0x56, 0x3d, 0xce, 0xff, 0xe5, 0x27,
	0xfe, 0xc2, 0x1d, 0x25, 0x93, 0xd6, 0x96, 0x83, 0x6f, 0x6e, 0x3d, 0xa9, 0xb4, 0x10, 0xd4, 0x8f,
	0x45, 0x22, 0x44, 0xb2, 0xc5, 0xad, 0xd6, 0x7a, 0x0b, 0x0d, 0xcd, 0x56, 0xc2, 0x2d, 0xd0, 0x6a,
	0xc0, 0xdd, 0x1e, 0x23, 0x91, 0x76, 0x95, 0xb6, 0x1c, 0xa8, 0xa7, 0xa6, 0x32, 0x30, 0x11, 0x07,
	0x70, 0x63, 0xa6, 0x83, 0xbe, 0x85, 0x86, 0x66, 0x2b, 0x03, 0x75, 0x0d, 0x50, 0x97, 0x37, 0x4d,
	0x16, 0xb7, 0x0f, 0xab, 0x19, 0x6b, 0x19, 0xc8, 0xab, 0xd0, 0x78, 0x86, 0x47, 0x98, 0xe9, 0x1f,
	0xac, 0x96, 0x0b, 0x48, 0x37, 0x96, 0x84, 0xdb, 0xc5, 0xfc, 0xaa, 0xcb, 0xe1, 0xea, 0xc6, 0x92,
	0xea, 0xfb, 0x4b, 0xe4, 0x4d, 0x75, 0xb2, 0x66, 0x2b, 0x03, 0x75, 0x13, 0xd6, 0x8f, 0xcf, 0xdc,
	0x70, 0x28, 0x11, 0xc4, 0x21, 0x94, 0xd0, 0x18, 0x36, 0xf2, 0x8e, 0x32, 0xf0, 0x77, 0xc0, 0x7e,
	0x41, 0x3c, 0xff, 0x74, 0x2c, 0x60, 0x8e, 0x18, 0x8b, 0xfd, 0x7e, 0xc2, 0x26, 0x69, 0x7f, 0x07,
	0xdb, 0x46, 0x6f, 0x19, 0x4c, 0xb6, 0x60, 0x33, 0x73, 0x71, 0xf3, 0x0f, 0x8f, 0xa2, 0x31, 0x04,
	0x6b, 0xda, 0x55, 0xd2, 0x69, 0x3b, 0xf2, 0xbc, 0x3c, 0x7c, 0x1f, 0x56, 0x33, 0xd6, 0x92, 0xfa,
	0x40, 0x3b, 0x58, 0x1a, 0x38, 0x86, 0x8d, 0xbc, 0xa3, 0x0c, 0x7c, 0x0b, 0x36, 0xf4, 0x1b, 0x45,
	0x23, 0x70, 0x0a, 0x9b, 0x53, 0x9e, 0x32, 0x18, 0x34, 0x61, 0x4f, 0xeb, 0x35, 0x0e, 0x93, 0xef,
	0xc6, 0x10, 0xf6, 0x0b, 0x23, 0xca, 0x60, 0xb4, 0x07, 0x3b, 0xda, 0x77, 0xec, 0xfb, 0x98, 0x04,
	0xbd, 0xd0, 0x8d, 0xe8, 0x19, 0x51, 0x47, 0x74, 0x04, 0xbb, 0x05, 0xfe, 0x32, 0xd8, 0x1c, 0xc0,
	0xbd, 0xcc, 0x21, 0xc8, 0x7e, 0xe3, 0x55, 0x8a, 0xde, 0x43, 0x6b, 0x56, 0x50, 0x49, 0x75, 0xd3,
	0xb2, 0x90, 0x53, 0x1e, 0x93, 0xba, 0x15, 0x46, 0x94, 0xc1, 0x68, 0x1f, 0x76, 0xb9, 0xd0, 0x1c,
	0x17, 0x12, 0x0a, 0x60, 0xaf, 0x28, 0xa0, 0x0c, 0x3e, 0xf7, 0x60, 0x5f, 0x3b, 0xc2, 0xc6, 0xba,
	0x11, 0x68, 0x16, 0x87, 0x94, 0xc1, 0xe9, 0x21, 0xb4, 0xb5, 0xb3, 0x94, 0x05, 0xcc, 0x9f, 0xbb,
	0x4b, 0x78, 0x70, 0x83, 0xd8, 0x92, 0x4e, 0xa0, 0xb9, 0x9d, 0xe9, 0xd5, 0x09, 0x2c, 0xf0, 0x97,
	0xf4, 0xad, 0xd4, 0xd4, 0x40, 0x9e, 0xcb, 0x3b, 0xd8, 0x36, 0x7a, 0xcb, 0x60, 0xb2, 0x0d, 0x5b,
	0x5d, 0x4c, 0x31, 0x33, 0x12, 0xf1, 0xc1, 0x36, 0x39, 0x4b, 0xe0, 0x71, 0xf8, 0x57, 0x03, 0x56,
	0xf4, 0x9f, 0x41, 0xd0, 0x0b, 0xb8, 0x93, 0x7d, 0x7d, 0xa1, 0x9d, 0x82, 0x67, 0x99, 0xe0, 0x6a,
	0xef, 0xce, 0x7c, 0xb4, 0xa1, 0x67, 0x50, 0xd3, 0x6e, 0x0e, 0xb4, 0x95, 0x3e, 0x4d, 0x73, 0x6f,
	0x0e, 0xdb, 0x36, 0xb9, 0xd4, 0x2a, 0x47, 0x00, 0xe9, 0xd3, 0x00, 0x59, 0x57, 0x91, 0xb9, 0x27,
	0x84, 0xbd, 0x65, 0xf0, 0xa4, 0x44, 0x34, 0xa1, 0x8f, 0xf4, 0xc8, 0xac, 0x34, 0xd7, 0x88, 0x4c,
	0xbf, 0x0c, 0x7e, 0x80, 0xdb, 0x19, 0xd9, 0x8e, 0xb6, 0xaf, 0x82, 0xa7, 0x45, 0xbe, 0xbd, 0x63,
	0x76, 0xaa, 0xb5, 0x9e, 0xc3, 0x8a, 0xae, 0xc4, 0x91, 0xad, 0x65, 0x32, 0xa7, 0xda, 0xed, 0x6d,
	0xa3, 0x2f, 0x5d, 0x48, 0x97, 0xd6, 0xda, 0x42, 0x53, 0x32, 0xdc, 0xde, 0x36, 0xfa, 0xd2, 0x1c,
	0x69, 0x07, 0x40, 0xcb, 0x51, 0x5e, 0x56, 0x6b, 0x39, 0x9a, 0x56, 0xd7, 0x3d, 0xa8, 0xe7, 0x75,
	0x2f, 0xda, 0x4b, 0x8b, 0x6b, 0xd2, 0xca, 0xf6, 0x7e, 0xa1, 0x5f, 0x2d, 0xda, 0x87, 0x75, 0xa3,
	0x8e, 0x45, 0x07, 0x57, 0x33, 0x8b, 0x55, 0xb0, 0xfd, 0xc9, 0xec, 0x20, 0x85, 0xf1, 0x1b, 0x7f,
	0x1a, 0xe5, 0x45, 0x2a, 0x6a, 0x9a, 0x1b, 0x3c, 0xd5, 0x57, 0xf6, 0xbd, 0x19, 0x11, 0x69, 0xdf,
	0x64, 0x04, 0xa8, 0xd6, 0x37, 0xd3, 0x72, 0x55, 0xeb, 0x1b, 0x93, 0x6a, 0xed, 0x41, 0x3d, 0xaf,
	0x27, 0xb5, 0xfc, 0x1a, 0x35, 0xa8, 0x96, 0xdf, 0x02, 0x29, 0xfa, 0x46, 0xbc, 0xd9, 0xb2, 0x1a,
	0x11, 0xed, 0x1b, 0xfb, 0x57, 0x5b, 0xb6, 0x59, 0x1c, 0xa0, 0xd6, 0x0d, 0x61, 0xab, 0x50, 0xf1,
	0xa1, 0xfb, 0xa6, 0xb2, 0x18, 0x74, 0xa3, 0xdd, 0xbe, 0x3e, 0x50, 0xe1, 0x9d, 0xc1, 0x66, 0x81,
	0xa2, 0x43, 0x9f, 0x9a, 0x2e, 0x98, 0x29, 0x4d, 0x68, 0x7f, 0x76, 0x5d, 0x98, 0x42, 0xfa, 0x50,
	0xf4, 0x65, 0x93, 0x9f, 0x7c, 0x54, 0xf0, 0xa3, 0xa6, 0x49, 0x3c, 0xd8, 0x8f, 0x6e, 0x14, 0x9b,
	0xa6, 0xb4, 0x50, 0x8c, 0x69, 0x29, 0x9d, 0x2d, 0xe9, 0xb4, 0x94, 0x5e, 0xa7, 0xec, 0xce, 0xc1,
	0x2a, 0xd2, 0x5a, 0x28, 0x4d, 0xd6, 0x4c, 0xbd, 0x66, 0xdf, 0xbf, 0x36, 0x4e, 0x81, 0xbd, 0x07,
	0xbb, 0x58, 0x46, 0xa1, 0xb6, 0xa9, 0x8d, 0x8d, 0x19, 0x7d, 0x70, 0x83, 0x48, 0x05, 0xf9, 0x47,
	0x05, 0x0e, 0x6e, 0xa0, 0x8e, 0xd0, 0x17, 0xa6, 0x26, 0x9c, 0xa9, 0xbb, 0xec, 0xc3, 0xff, 0x33,
	0x25, 0xed, 0xe0, 0x02, 0x45, 0xa4, 0x75, 0xf0, 0x2c, 0x4d, 0xa5, 0x75, 0xf0, 0x6c, 0x69, 0xd5,
	0x87, 0x75, 0xa3, 0xde, 0xd1, 0xee, 0xd4, 0x62, 0xb5, 0xa4, 0xdd, 0xa9, 0xb3, 0x44, 0x93, 0x03,
	0x6b, 0x26, 0x29, 0x83, 0x5a, 0xfa, 0xcd, 0x61, 0x96, 0x41, 0xf6, 0xc1, 0xcc, 0x18, 0x09, 0x60,
	0x6f, 0xfc, 0xfe, 0xcf, 0x3c, 0x42, 0xcb, 0x3f, 0xfb, 0xe1, 0xf0, 0x78, 0x44, 0x12, 0xcf, 0xae,
	0x8a, 0xb8, 0xfe, 0x82, 0xf8, 0xd1, 0xf6, 0xcb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x58,
	0xee, 0x33, 0x4a, 0x1a, 0x00, 0x00,
}
