// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eip.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/chai2010/qingcloud-go/spec.pb/qingcloud_sdk_rule"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import "github.com/chai2010/qingcloud-go/config"
import "github.com/chai2010/qingcloud-go/request"
import "github.com/chai2010/qingcloud-go/request/data"

var _ = config.Config{}
var _ = request.Request{}
var _ = data.Operation{}

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EipServiceProperties struct {
	Zone string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
}

func (m *EipServiceProperties) Reset()                    { *m = EipServiceProperties{} }
func (m *EipServiceProperties) String() string            { return proto.CompactTextString(m) }
func (*EipServiceProperties) ProtoMessage()               {}
func (*EipServiceProperties) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *EipServiceProperties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type DescribeEipsInput struct {
	Eips       []string `protobuf:"bytes,1,rep,name=eips" json:"eips,omitempty"`
	InstanceId string   `protobuf:"bytes,2,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	Status     string   `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	SearchWord string   `protobuf:"bytes,4,opt,name=search_word,json=searchWord" json:"search_word,omitempty"`
	Tags       []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Verbose    int32    `protobuf:"varint,6,opt,name=verbose" json:"verbose,omitempty"`
	Offset     int32    `protobuf:"varint,7,opt,name=offset" json:"offset,omitempty"`
	Limit      int32    `protobuf:"varint,8,opt,name=limit" json:"limit,omitempty"`
}

func (m *DescribeEipsInput) Reset()                    { *m = DescribeEipsInput{} }
func (m *DescribeEipsInput) String() string            { return proto.CompactTextString(m) }
func (*DescribeEipsInput) ProtoMessage()               {}
func (*DescribeEipsInput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *DescribeEipsInput) GetEips() []string {
	if m != nil {
		return m.Eips
	}
	return nil
}

func (m *DescribeEipsInput) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *DescribeEipsInput) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DescribeEipsInput) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *DescribeEipsInput) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DescribeEipsInput) GetVerbose() int32 {
	if m != nil {
		return m.Verbose
	}
	return 0
}

func (m *DescribeEipsInput) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeEipsInput) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type DescribeEipsOutput struct {
	Action     string                             `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode    int32                              `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message    string                             `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	EipSet     []*DescribeEipsOutput_ResponseItem `protobuf:"bytes,4,rep,name=eip_set,json=eipSet" json:"eip_set,omitempty"`
	TotalCount int32                              `protobuf:"varint,5,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
}

func (m *DescribeEipsOutput) Reset()                    { *m = DescribeEipsOutput{} }
func (m *DescribeEipsOutput) String() string            { return proto.CompactTextString(m) }
func (*DescribeEipsOutput) ProtoMessage()               {}
func (*DescribeEipsOutput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *DescribeEipsOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DescribeEipsOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DescribeEipsOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DescribeEipsOutput) GetEipSet() []*DescribeEipsOutput_ResponseItem {
	if m != nil {
		return m.EipSet
	}
	return nil
}

func (m *DescribeEipsOutput) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type DescribeEipsOutput_ResponseItem struct {
	EipId            string                      `protobuf:"bytes,1,opt,name=eip_id,json=eipId" json:"eip_id,omitempty"`
	EipName          string                      `protobuf:"bytes,2,opt,name=eip_name,json=eipName" json:"eip_name,omitempty"`
	Description      string                      `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Bandwidth        int32                       `protobuf:"varint,4,opt,name=bandwidth" json:"bandwidth,omitempty"`
	BillingMode      string                      `protobuf:"bytes,5,opt,name=billing_mode,json=billingMode" json:"billing_mode,omitempty"`
	Status           string                      `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	TransitionStatus string                      `protobuf:"bytes,7,opt,name=transition_status,json=transitionStatus" json:"transition_status,omitempty"`
	IcpCodes         string                      `protobuf:"bytes,8,opt,name=icp_codes,json=icpCodes" json:"icp_codes,omitempty"`
	CreateTime       *google_protobuf1.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	StatusTime       *google_protobuf1.Timestamp `protobuf:"bytes,10,opt,name=status_time,json=statusTime" json:"status_time,omitempty"`
	Resource         *Resource                   `protobuf:"bytes,11,opt,name=resource" json:"resource,omitempty"`
	EipGroup         *EIPGroup                   `protobuf:"bytes,12,opt,name=eip_group,json=eipGroup" json:"eip_group,omitempty"`
	EipAddr          string                      `protobuf:"bytes,13,opt,name=eip_addr,json=eipAddr" json:"eip_addr,omitempty"`
}

func (m *DescribeEipsOutput_ResponseItem) Reset()         { *m = DescribeEipsOutput_ResponseItem{} }
func (m *DescribeEipsOutput_ResponseItem) String() string { return proto.CompactTextString(m) }
func (*DescribeEipsOutput_ResponseItem) ProtoMessage()    {}
func (*DescribeEipsOutput_ResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{2, 0}
}

func (m *DescribeEipsOutput_ResponseItem) GetEipId() string {
	if m != nil {
		return m.EipId
	}
	return ""
}

func (m *DescribeEipsOutput_ResponseItem) GetEipName() string {
	if m != nil {
		return m.EipName
	}
	return ""
}

func (m *DescribeEipsOutput_ResponseItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DescribeEipsOutput_ResponseItem) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *DescribeEipsOutput_ResponseItem) GetBillingMode() string {
	if m != nil {
		return m.BillingMode
	}
	return ""
}

func (m *DescribeEipsOutput_ResponseItem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DescribeEipsOutput_ResponseItem) GetTransitionStatus() string {
	if m != nil {
		return m.TransitionStatus
	}
	return ""
}

func (m *DescribeEipsOutput_ResponseItem) GetIcpCodes() string {
	if m != nil {
		return m.IcpCodes
	}
	return ""
}

func (m *DescribeEipsOutput_ResponseItem) GetCreateTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *DescribeEipsOutput_ResponseItem) GetStatusTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

func (m *DescribeEipsOutput_ResponseItem) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *DescribeEipsOutput_ResponseItem) GetEipGroup() *EIPGroup {
	if m != nil {
		return m.EipGroup
	}
	return nil
}

func (m *DescribeEipsOutput_ResponseItem) GetEipAddr() string {
	if m != nil {
		return m.EipAddr
	}
	return ""
}

type AllocateEipsInput struct {
	Bandwidth   int32  `protobuf:"varint,1,opt,name=bandwidth" json:"bandwidth,omitempty"`
	BillingMode string `protobuf:"bytes,2,opt,name=billing_mode,json=billingMode" json:"billing_mode,omitempty"`
	EipName     string `protobuf:"bytes,3,opt,name=eip_name,json=eipName" json:"eip_name,omitempty"`
	Count       int32  `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	NeedIcp     int32  `protobuf:"varint,5,opt,name=need_icp,json=needIcp" json:"need_icp,omitempty"`
	TargetUser  string `protobuf:"bytes,6,opt,name=target_user,json=targetUser" json:"target_user,omitempty"`
}

func (m *AllocateEipsInput) Reset()                    { *m = AllocateEipsInput{} }
func (m *AllocateEipsInput) String() string            { return proto.CompactTextString(m) }
func (*AllocateEipsInput) ProtoMessage()               {}
func (*AllocateEipsInput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *AllocateEipsInput) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *AllocateEipsInput) GetBillingMode() string {
	if m != nil {
		return m.BillingMode
	}
	return ""
}

func (m *AllocateEipsInput) GetEipName() string {
	if m != nil {
		return m.EipName
	}
	return ""
}

func (m *AllocateEipsInput) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AllocateEipsInput) GetNeedIcp() int32 {
	if m != nil {
		return m.NeedIcp
	}
	return 0
}

func (m *AllocateEipsInput) GetTargetUser() string {
	if m != nil {
		return m.TargetUser
	}
	return ""
}

type AllocateEipsOutput struct {
	Action  string   `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32    `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string   `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Eips    []string `protobuf:"bytes,4,rep,name=eips" json:"eips,omitempty"`
}

func (m *AllocateEipsOutput) Reset()                    { *m = AllocateEipsOutput{} }
func (m *AllocateEipsOutput) String() string            { return proto.CompactTextString(m) }
func (*AllocateEipsOutput) ProtoMessage()               {}
func (*AllocateEipsOutput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *AllocateEipsOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AllocateEipsOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *AllocateEipsOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AllocateEipsOutput) GetEips() []string {
	if m != nil {
		return m.Eips
	}
	return nil
}

type ReleaseEipsInput struct {
	Eips []string `protobuf:"bytes,1,rep,name=eips" json:"eips,omitempty"`
}

func (m *ReleaseEipsInput) Reset()                    { *m = ReleaseEipsInput{} }
func (m *ReleaseEipsInput) String() string            { return proto.CompactTextString(m) }
func (*ReleaseEipsInput) ProtoMessage()               {}
func (*ReleaseEipsInput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *ReleaseEipsInput) GetEips() []string {
	if m != nil {
		return m.Eips
	}
	return nil
}

type ReleaseEipsOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	JobId   string `protobuf:"bytes,4,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (m *ReleaseEipsOutput) Reset()                    { *m = ReleaseEipsOutput{} }
func (m *ReleaseEipsOutput) String() string            { return proto.CompactTextString(m) }
func (*ReleaseEipsOutput) ProtoMessage()               {}
func (*ReleaseEipsOutput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *ReleaseEipsOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ReleaseEipsOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ReleaseEipsOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReleaseEipsOutput) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type AssociateEipInput struct {
	Eip      string `protobuf:"bytes,1,opt,name=eip" json:"eip,omitempty"`
	Instance string `protobuf:"bytes,2,opt,name=instance" json:"instance,omitempty"`
}

func (m *AssociateEipInput) Reset()                    { *m = AssociateEipInput{} }
func (m *AssociateEipInput) String() string            { return proto.CompactTextString(m) }
func (*AssociateEipInput) ProtoMessage()               {}
func (*AssociateEipInput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *AssociateEipInput) GetEip() string {
	if m != nil {
		return m.Eip
	}
	return ""
}

func (m *AssociateEipInput) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

type AssociateEipOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	JobId   string `protobuf:"bytes,4,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (m *AssociateEipOutput) Reset()                    { *m = AssociateEipOutput{} }
func (m *AssociateEipOutput) String() string            { return proto.CompactTextString(m) }
func (*AssociateEipOutput) ProtoMessage()               {}
func (*AssociateEipOutput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *AssociateEipOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AssociateEipOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *AssociateEipOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AssociateEipOutput) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type DissociateEipsInput struct {
	Eips []string `protobuf:"bytes,1,rep,name=eips" json:"eips,omitempty"`
}

func (m *DissociateEipsInput) Reset()                    { *m = DissociateEipsInput{} }
func (m *DissociateEipsInput) String() string            { return proto.CompactTextString(m) }
func (*DissociateEipsInput) ProtoMessage()               {}
func (*DissociateEipsInput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *DissociateEipsInput) GetEips() []string {
	if m != nil {
		return m.Eips
	}
	return nil
}

type DissociateEipsOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	JobId   string `protobuf:"bytes,4,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (m *DissociateEipsOutput) Reset()                    { *m = DissociateEipsOutput{} }
func (m *DissociateEipsOutput) String() string            { return proto.CompactTextString(m) }
func (*DissociateEipsOutput) ProtoMessage()               {}
func (*DissociateEipsOutput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *DissociateEipsOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DissociateEipsOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DissociateEipsOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DissociateEipsOutput) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type ChangeEipsBandwidthInput struct {
	Eips      []string `protobuf:"bytes,1,rep,name=eips" json:"eips,omitempty"`
	Bandwidth int32    `protobuf:"varint,2,opt,name=bandwidth" json:"bandwidth,omitempty"`
}

func (m *ChangeEipsBandwidthInput) Reset()                    { *m = ChangeEipsBandwidthInput{} }
func (m *ChangeEipsBandwidthInput) String() string            { return proto.CompactTextString(m) }
func (*ChangeEipsBandwidthInput) ProtoMessage()               {}
func (*ChangeEipsBandwidthInput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *ChangeEipsBandwidthInput) GetEips() []string {
	if m != nil {
		return m.Eips
	}
	return nil
}

func (m *ChangeEipsBandwidthInput) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

type ChangeEipsBandwidthOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	JobId   string `protobuf:"bytes,4,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (m *ChangeEipsBandwidthOutput) Reset()                    { *m = ChangeEipsBandwidthOutput{} }
func (m *ChangeEipsBandwidthOutput) String() string            { return proto.CompactTextString(m) }
func (*ChangeEipsBandwidthOutput) ProtoMessage()               {}
func (*ChangeEipsBandwidthOutput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

func (m *ChangeEipsBandwidthOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ChangeEipsBandwidthOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ChangeEipsBandwidthOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChangeEipsBandwidthOutput) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type ChangeEipsBillingModeInput struct {
	Eips        []string `protobuf:"bytes,1,rep,name=eips" json:"eips,omitempty"`
	BillingMode string   `protobuf:"bytes,2,opt,name=billing_mode,json=billingMode" json:"billing_mode,omitempty"`
}

func (m *ChangeEipsBillingModeInput) Reset()                    { *m = ChangeEipsBillingModeInput{} }
func (m *ChangeEipsBillingModeInput) String() string            { return proto.CompactTextString(m) }
func (*ChangeEipsBillingModeInput) ProtoMessage()               {}
func (*ChangeEipsBillingModeInput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *ChangeEipsBillingModeInput) GetEips() []string {
	if m != nil {
		return m.Eips
	}
	return nil
}

func (m *ChangeEipsBillingModeInput) GetBillingMode() string {
	if m != nil {
		return m.BillingMode
	}
	return ""
}

type ChangeEipsBillingModeOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	JobId   string `protobuf:"bytes,4,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (m *ChangeEipsBillingModeOutput) Reset()                    { *m = ChangeEipsBillingModeOutput{} }
func (m *ChangeEipsBillingModeOutput) String() string            { return proto.CompactTextString(m) }
func (*ChangeEipsBillingModeOutput) ProtoMessage()               {}
func (*ChangeEipsBillingModeOutput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *ChangeEipsBillingModeOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ChangeEipsBillingModeOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ChangeEipsBillingModeOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChangeEipsBillingModeOutput) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type ModifyEipAttributesInput struct {
	Eip         string `protobuf:"bytes,1,opt,name=eip" json:"eip,omitempty"`
	EipName     string `protobuf:"bytes,2,opt,name=eip_name,json=eipName" json:"eip_name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *ModifyEipAttributesInput) Reset()                    { *m = ModifyEipAttributesInput{} }
func (m *ModifyEipAttributesInput) String() string            { return proto.CompactTextString(m) }
func (*ModifyEipAttributesInput) ProtoMessage()               {}
func (*ModifyEipAttributesInput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *ModifyEipAttributesInput) GetEip() string {
	if m != nil {
		return m.Eip
	}
	return ""
}

func (m *ModifyEipAttributesInput) GetEipName() string {
	if m != nil {
		return m.EipName
	}
	return ""
}

func (m *ModifyEipAttributesInput) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ModifyEipAttributesOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ModifyEipAttributesOutput) Reset()                    { *m = ModifyEipAttributesOutput{} }
func (m *ModifyEipAttributesOutput) String() string            { return proto.CompactTextString(m) }
func (*ModifyEipAttributesOutput) ProtoMessage()               {}
func (*ModifyEipAttributesOutput) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{16} }

func (m *ModifyEipAttributesOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ModifyEipAttributesOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ModifyEipAttributesOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EipServiceProperties)(nil), "service.EipServiceProperties")
	proto.RegisterType((*DescribeEipsInput)(nil), "service.DescribeEipsInput")
	proto.RegisterType((*DescribeEipsOutput)(nil), "service.DescribeEipsOutput")
	proto.RegisterType((*DescribeEipsOutput_ResponseItem)(nil), "service.DescribeEipsOutput.ResponseItem")
	proto.RegisterType((*AllocateEipsInput)(nil), "service.AllocateEipsInput")
	proto.RegisterType((*AllocateEipsOutput)(nil), "service.AllocateEipsOutput")
	proto.RegisterType((*ReleaseEipsInput)(nil), "service.ReleaseEipsInput")
	proto.RegisterType((*ReleaseEipsOutput)(nil), "service.ReleaseEipsOutput")
	proto.RegisterType((*AssociateEipInput)(nil), "service.AssociateEipInput")
	proto.RegisterType((*AssociateEipOutput)(nil), "service.AssociateEipOutput")
	proto.RegisterType((*DissociateEipsInput)(nil), "service.DissociateEipsInput")
	proto.RegisterType((*DissociateEipsOutput)(nil), "service.DissociateEipsOutput")
	proto.RegisterType((*ChangeEipsBandwidthInput)(nil), "service.ChangeEipsBandwidthInput")
	proto.RegisterType((*ChangeEipsBandwidthOutput)(nil), "service.ChangeEipsBandwidthOutput")
	proto.RegisterType((*ChangeEipsBillingModeInput)(nil), "service.ChangeEipsBillingModeInput")
	proto.RegisterType((*ChangeEipsBillingModeOutput)(nil), "service.ChangeEipsBillingModeOutput")
	proto.RegisterType((*ModifyEipAttributesInput)(nil), "service.ModifyEipAttributesInput")
	proto.RegisterType((*ModifyEipAttributesOutput)(nil), "service.ModifyEipAttributesOutput")
}

type EipServiceInterface interface {
	DescribeEips(in *DescribeEipsInput) (out *DescribeEipsOutput, err error)
	AllocateEips(in *AllocateEipsInput) (out *AllocateEipsOutput, err error)
	ReleaseEips(in *ReleaseEipsInput) (out *ReleaseEipsOutput, err error)
	AssociateEip(in *AssociateEipInput) (out *AssociateEipOutput, err error)
	DissociateEips(in *DissociateEipsInput) (out *DissociateEipsOutput, err error)
	ChangeEipsBandwidth(in *ChangeEipsBandwidthInput) (out *ChangeEipsBandwidthOutput, err error)
	ChangeEipsBillingMode(in *ChangeEipsBillingModeInput) (out *ChangeEipsBillingModeOutput, err error)
	ModifyEipAttributes(in *ModifyEipAttributesInput) (out *ModifyEipAttributesOutput, err error)
}

type EipService struct {
	Config           *config.Config
	Properties       *EipServiceProperties
	LastResponseBody string
}

func NewEipService(conf *config.Config, zone string) (p *EipService) {
	return &EipService{
		Config:     conf,
		Properties: &EipServiceProperties{Zone: zone},
	}
}

func (s *QingCloudService) Eip(zone string) (*EipService, error) {
	properties := &EipServiceProperties{
		Zone: zone,
	}

	return &EipService{Config: s.Config, Properties: properties}, nil
}

func (p *EipService) DescribeEips(in *DescribeEipsInput) (out *DescribeEipsOutput, err error) {
	if in == nil {
		in = &DescribeEipsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeEips",
		RequestMethod: "GET", // GET or POST
	}

	x := &DescribeEipsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DescribeEipsInput) Validate() error {
	return nil
}

func (p *EipService) AllocateEips(in *AllocateEipsInput) (out *AllocateEipsOutput, err error) {
	if in == nil {
		in = &AllocateEipsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "AllocateEips",
		RequestMethod: "GET", // GET or POST
	}

	x := &AllocateEipsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *AllocateEipsInput) Validate() error {
	return nil
}

func (p *EipService) ReleaseEips(in *ReleaseEipsInput) (out *ReleaseEipsOutput, err error) {
	if in == nil {
		in = &ReleaseEipsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ReleaseEips",
		RequestMethod: "GET", // GET or POST
	}

	x := &ReleaseEipsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ReleaseEipsInput) Validate() error {
	return nil
}

func (p *EipService) AssociateEip(in *AssociateEipInput) (out *AssociateEipOutput, err error) {
	if in == nil {
		in = &AssociateEipInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "AssociateEip",
		RequestMethod: "GET", // GET or POST
	}

	x := &AssociateEipOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *AssociateEipInput) Validate() error {
	return nil
}

func (p *EipService) DissociateEips(in *DissociateEipsInput) (out *DissociateEipsOutput, err error) {
	if in == nil {
		in = &DissociateEipsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DissociateEips",
		RequestMethod: "GET", // GET or POST
	}

	x := &DissociateEipsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DissociateEipsInput) Validate() error {
	return nil
}

func (p *EipService) ChangeEipsBandwidth(in *ChangeEipsBandwidthInput) (out *ChangeEipsBandwidthOutput, err error) {
	if in == nil {
		in = &ChangeEipsBandwidthInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ChangeEipsBandwidth",
		RequestMethod: "GET", // GET or POST
	}

	x := &ChangeEipsBandwidthOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ChangeEipsBandwidthInput) Validate() error {
	return nil
}

func (p *EipService) ChangeEipsBillingMode(in *ChangeEipsBillingModeInput) (out *ChangeEipsBillingModeOutput, err error) {
	if in == nil {
		in = &ChangeEipsBillingModeInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ChangeEipsBillingMode",
		RequestMethod: "GET", // GET or POST
	}

	x := &ChangeEipsBillingModeOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ChangeEipsBillingModeInput) Validate() error {
	return nil
}

func (p *EipService) ModifyEipAttributes(in *ModifyEipAttributesInput) (out *ModifyEipAttributesOutput, err error) {
	if in == nil {
		in = &ModifyEipAttributesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyEipAttributes",
		RequestMethod: "GET", // GET or POST
	}

	x := &ModifyEipAttributesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ModifyEipAttributesInput) Validate() error {
	return nil
}

func init() { proto.RegisterFile("eip.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 1021 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x57, 0x36, 0x75, 0xd2, 0xbc, 0x14, 0xd4, 0xcc, 0xb6, 0x2b, 0xd7, 0xdd, 0xd5, 0x66, 0x0d,
	0x42, 0x05, 0x44, 0x2a, 0x95, 0x23, 0xa7, 0xd0, 0x56, 0xab, 0x48, 0x14, 0x16, 0x17, 0xc4, 0x05,
	0xc9, 0x72, 0xec, 0x57, 0x77, 0x16, 0xc7, 0x33, 0xcc, 0x8c, 0xb7, 0xec, 0x5e, 0x10, 0x57, 0x3e,
	0x0e, 0xdf, 0x60, 0x3f, 0x08, 0x1f, 0x82, 0x23, 0x37, 0x34, 0x33, 0x4e, 0x33, 0x69, 0x9d, 0xf4,
	0x80, 0xda, 0x4b, 0x34, 0xef, 0xff, 0x7b, 0xf3, 0xde, 0xef, 0x79, 0x02, 0x3d, 0xa4, 0x7c, 0xc4,
	0x05, 0x53, 0x8c, 0x74, 0x25, 0x8a, 0x37, 0x34, 0xc5, 0xa0, 0xaf, 0xde, 0x72, 0x94, 0x96, 0x1b,
	0x3c, 0xfb, 0x95, 0x96, 0x79, 0x5a, 0xb0, 0x2a, 0x8b, 0x65, 0xf6, 0x4b, 0x2c, 0xaa, 0x02, 0x0f,
	0xf5, 0x4f, 0x2d, 0x7e, 0x9e, 0x33, 0x96, 0x17, 0x78, 0x68, 0xa8, 0x69, 0x75, 0x71, 0xa8, 0xe8,
	0x0c, 0xa5, 0x4a, 0x66, 0xb5, 0xd7, 0xf0, 0x33, 0xd8, 0x39, 0xa5, 0xfc, 0xdc, 0xba, 0x7e, 0x25,
	0x18, 0x47, 0xa1, 0x28, 0x4a, 0x42, 0x60, 0xe3, 0x1d, 0x2b, 0xd1, 0x6f, 0x0d, 0x5b, 0x07, 0xbd,
	0xc8, 0x9c, 0xc3, 0xbf, 0x5b, 0x30, 0x38, 0x41, 0x99, 0x0a, 0x3a, 0xc5, 0x53, 0xca, 0xe5, 0xa4,
	0xe4, 0x95, 0xd2, 0x9a, 0x48, 0xb9, 0xf4, 0x5b, 0xc3, 0xb6, 0xd6, 0xd4, 0x67, 0xf2, 0x1c, 0xfa,
	0xb4, 0x94, 0x2a, 0x29, 0x53, 0x8c, 0x69, 0xe6, 0x3f, 0x32, 0x4e, 0x60, 0xce, 0x9a, 0x64, 0xe4,
	0x09, 0x74, 0xa4, 0x4a, 0x54, 0x25, 0xfd, 0xb6, 0x91, 0xd5, 0x94, 0x36, 0x94, 0x98, 0x88, 0xf4,
	0x32, 0xbe, 0x62, 0x22, 0xf3, 0x37, 0xac, 0xa1, 0x65, 0xfd, 0xc4, 0x44, 0xa6, 0xa3, 0xa9, 0x24,
	0x97, 0xbe, 0x67, 0xa3, 0xe9, 0x33, 0xf1, 0xa1, 0xfb, 0x06, 0xc5, 0x94, 0x49, 0xf4, 0x3b, 0xc3,
	0xd6, 0x81, 0x17, 0xcd, 0x49, 0x1d, 0x86, 0x5d, 0x5c, 0x48, 0x54, 0x7e, 0xd7, 0x08, 0x6a, 0x8a,
	0xec, 0x80, 0x57, 0xd0, 0x19, 0x55, 0xfe, 0xa6, 0x61, 0x5b, 0x22, 0x7c, 0xef, 0x01, 0x71, 0xeb,
	0xfb, 0xae, 0x52, 0xba, 0xc0, 0x27, 0xd0, 0x49, 0x52, 0x45, 0x59, 0x59, 0x5f, 0x46, 0x4d, 0x91,
	0x3d, 0xd8, 0x14, 0xa8, 0xe2, 0x94, 0x65, 0x68, 0x2a, 0xf4, 0xa2, 0xae, 0x40, 0x75, 0xcc, 0x32,
	0xd4, 0x19, 0xcd, 0x50, 0xca, 0x24, 0xc7, 0xba, 0xbe, 0x39, 0x49, 0xc6, 0xd0, 0x45, 0xca, 0x63,
	0x9d, 0xd2, 0xc6, 0xb0, 0x7d, 0xd0, 0x3f, 0x3a, 0x18, 0xd5, 0x7d, 0x1d, 0xdd, 0x0e, 0x3d, 0x8a,
	0x50, 0x72, 0x56, 0x4a, 0x9c, 0x28, 0x9c, 0x45, 0x1d, 0xd4, 0x8d, 0x52, 0xfa, 0x8e, 0x14, 0x53,
	0x49, 0x11, 0xa7, 0xac, 0x2a, 0x95, 0xef, 0x99, 0xd0, 0x60, 0x58, 0xc7, 0x9a, 0x13, 0xfc, 0xdb,
	0x86, 0x2d, 0xd7, 0x92, 0xec, 0x82, 0xb6, 0xd5, 0x9d, 0xb0, 0x15, 0x78, 0x48, 0xf9, 0x24, 0xd3,
	0x05, 0x68, 0x76, 0x99, 0xcc, 0xb0, 0x6e, 0x91, 0xce, 0xed, 0xdb, 0x64, 0x86, 0x64, 0x08, 0xfd,
	0xcc, 0xa4, 0xc3, 0x4d, 0xe1, 0xb6, 0x08, 0x97, 0x45, 0x9e, 0x42, 0x6f, 0x9a, 0x94, 0xd9, 0x15,
	0xcd, 0xd4, 0xa5, 0xe9, 0x93, 0x17, 0x2d, 0x18, 0xe4, 0x05, 0x6c, 0x4d, 0x69, 0x51, 0xd0, 0x32,
	0x8f, 0x67, 0xfa, 0x7e, 0x3c, 0xeb, 0xa0, 0xe6, 0x9d, 0xe9, 0x3b, 0x5a, 0x8c, 0x40, 0x67, 0x69,
	0x04, 0x3e, 0x87, 0x81, 0x12, 0x49, 0x29, 0xa9, 0x0e, 0x13, 0xd7, 0x2a, 0x5d, 0xa3, 0xb2, 0xbd,
	0x10, 0x9c, 0x5b, 0xe5, 0x7d, 0xe8, 0xd1, 0x94, 0x9b, 0x1e, 0x48, 0xd3, 0xcc, 0x5e, 0xb4, 0x49,
	0x53, 0xae, 0x9b, 0x20, 0xc9, 0x57, 0xd0, 0x4f, 0x05, 0x26, 0x0a, 0x63, 0x3d, 0xf5, 0x7e, 0x6f,
	0xd8, 0x3a, 0xe8, 0x1f, 0x05, 0x23, 0x0b, 0x89, 0xd1, 0x1c, 0x12, 0xa3, 0x1f, 0xe6, 0x90, 0x88,
	0xc0, 0xaa, 0x6b, 0x86, 0x36, 0xb6, 0xb1, 0xad, 0x31, 0xdc, 0x6d, 0x6c, 0xd5, 0x8d, 0xf1, 0x17,
	0x7a, 0x34, 0x24, 0xab, 0x44, 0x8a, 0x7e, 0xdf, 0x58, 0x0e, 0xae, 0xdb, 0x1c, 0xd5, 0x82, 0xe8,
	0x5a, 0x85, 0x8c, 0x0c, 0xce, 0xe3, 0x5c, 0xb0, 0x8a, 0xfb, 0x5b, 0x37, 0xf4, 0x4f, 0x27, 0xaf,
	0x5e, 0x6a, 0x41, 0xa4, 0x9b, 0x65, 0x4e, 0xf3, 0xc6, 0x25, 0x59, 0x26, 0xfc, 0x0f, 0xae, 0x1b,
	0x37, 0xce, 0x32, 0x11, 0xbe, 0x6f, 0xc1, 0x60, 0x5c, 0x14, 0x2c, 0x4d, 0x94, 0x83, 0xd1, 0xa5,
	0x66, 0xb5, 0xee, 0x6a, 0xd6, 0xa3, 0xdb, 0xcd, 0x72, 0x47, 0xa5, 0xbd, 0x3c, 0x2a, 0x3b, 0xe0,
	0xd9, 0x41, 0xb4, 0x43, 0x60, 0x09, 0x6d, 0x50, 0x22, 0x66, 0x31, 0x4d, 0x79, 0x3d, 0xa1, 0x5d,
	0x4d, 0x4f, 0x52, 0x6e, 0xe6, 0x37, 0x11, 0x39, 0xaa, 0xb8, 0x92, 0x28, 0xea, 0xee, 0x83, 0x65,
	0xfd, 0x28, 0x51, 0x84, 0x15, 0x10, 0xb7, 0x84, 0xfb, 0x80, 0xe1, 0x7c, 0x69, 0x6d, 0x2c, 0x96,
	0x56, 0xf8, 0x09, 0x6c, 0x47, 0x58, 0x60, 0x22, 0xd7, 0x2f, 0xb7, 0xf0, 0x0a, 0x06, 0x8e, 0xde,
	0x7d, 0x64, 0xb7, 0x0b, 0x9d, 0xd7, 0x6c, 0xaa, 0xf1, 0x6a, 0x17, 0xa0, 0xf7, 0x9a, 0x4d, 0x27,
	0x59, 0x38, 0x86, 0xc1, 0x58, 0x4a, 0x96, 0x52, 0x7b, 0x31, 0x36, 0xc3, 0x6d, 0x68, 0x23, 0xe5,
	0x75, 0x54, 0x7d, 0x24, 0x01, 0x6c, 0xce, 0x37, 0x6d, 0xdd, 0xca, 0x6b, 0x3a, 0xfc, 0x0d, 0x88,
	0xeb, 0xe2, 0x01, 0x93, 0xff, 0x14, 0x1e, 0x9f, 0x50, 0x27, 0xf4, 0x9a, 0x0b, 0x7e, 0x07, 0x3b,
	0xcb, 0xaa, 0x0f, 0x98, 0xe6, 0x37, 0xe0, 0x1f, 0x5f, 0x26, 0x65, 0x6e, 0xe2, 0x7e, 0x3d, 0x87,
	0xc8, 0xea, 0x2f, 0xdd, 0x12, 0xb2, 0x1e, 0xdd, 0x40, 0x56, 0xf8, 0x3b, 0xec, 0x35, 0x78, 0x7b,
	0xc0, 0x72, 0xce, 0x21, 0x70, 0x12, 0x58, 0x00, 0x7a, 0x75, 0x41, 0x77, 0x2f, 0x83, 0xf0, 0x8f,
	0x16, 0xec, 0x37, 0x7a, 0x7d, 0xc0, 0xc2, 0x28, 0xf8, 0x67, 0x2c, 0xa3, 0x17, 0x6f, 0x4f, 0x29,
	0x1f, 0x2b, 0x25, 0xe8, 0xb4, 0x52, 0x28, 0x57, 0x41, 0xe2, 0xff, 0x7c, 0xe9, 0xc2, 0x4b, 0xd8,
	0x6b, 0x08, 0x75, 0x0f, 0xb5, 0x1e, 0xfd, 0xe5, 0x01, 0x2c, 0x5e, 0x63, 0xe4, 0x25, 0x6c, 0xb9,
	0x6f, 0x02, 0x12, 0x34, 0x3e, 0x15, 0x4c, 0xcd, 0xc1, 0xfe, 0x9a, 0x67, 0x84, 0x76, 0xe4, 0x2e,
	0x54, 0xc7, 0xd1, 0xad, 0x4f, 0x85, 0xe3, 0xa8, 0x61, 0x07, 0x9f, 0x40, 0xdf, 0x59, 0x7d, 0x64,
	0xcf, 0xf9, 0xa8, 0x2d, 0x2f, 0xce, 0x20, 0x68, 0x12, 0x39, 0xe9, 0x38, 0xf0, 0x76, 0xd3, 0xb9,
	0xb9, 0xde, 0xdc, 0x74, 0x6e, 0xef, 0xad, 0x33, 0xf8, 0x70, 0x79, 0x51, 0x90, 0xa7, 0x8b, 0x6b,
	0xb8, 0xbd, 0x6c, 0x82, 0x67, 0x2b, 0xa4, 0xb5, 0xbb, 0x9f, 0xe1, 0x71, 0x03, 0x5a, 0xc9, 0x8b,
	0x6b, 0xab, 0x55, 0x9b, 0x21, 0x08, 0xd7, 0xa9, 0xd4, 0xde, 0xa7, 0xb0, 0xdb, 0x08, 0x1a, 0xf2,
	0x51, 0x93, 0xf1, 0x0d, 0xa8, 0x06, 0x1f, 0xaf, 0x57, 0x5a, 0x54, 0xd0, 0x30, 0xaa, 0x4e, 0x05,
	0xab, 0x30, 0xe3, 0x54, 0xb0, 0x72, 0xd6, 0x83, 0x9d, 0x3f, 0xff, 0xd9, 0xd8, 0x26, 0xbd, 0xef,
	0x69, 0x99, 0x1f, 0xeb, 0x7f, 0x1c, 0x41, 0xfb, 0x94, 0xf2, 0x69, 0xc7, 0xbc, 0x85, 0xbe, 0xfc,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x3b, 0x10, 0x99, 0xab, 0x0c, 0x00, 0x00,
}
