// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/chai2010/qingcloud-go/spec.pb/qingcloud_sdk_rule"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import "github.com/chai2010/qingcloud-go/config"
import "github.com/chai2010/qingcloud-go/request"
import "github.com/chai2010/qingcloud-go/request/data"

var _ = config.Config{}
var _ = request.Request{}
var _ = data.Operation{}

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MonitorServiceProperties struct {
	Zone string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
}

func (m *MonitorServiceProperties) Reset()                    { *m = MonitorServiceProperties{} }
func (m *MonitorServiceProperties) String() string            { return proto.CompactTextString(m) }
func (*MonitorServiceProperties) ProtoMessage()               {}
func (*MonitorServiceProperties) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *MonitorServiceProperties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type GetMonitorInput struct {
	Resource  string                      `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	Meters    []string                    `protobuf:"bytes,2,rep,name=meters" json:"meters,omitempty"`
	Step      string                      `protobuf:"bytes,3,opt,name=step" json:"step,omitempty"`
	StartTime *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime   *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *GetMonitorInput) Reset()                    { *m = GetMonitorInput{} }
func (m *GetMonitorInput) String() string            { return proto.CompactTextString(m) }
func (*GetMonitorInput) ProtoMessage()               {}
func (*GetMonitorInput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *GetMonitorInput) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *GetMonitorInput) GetMeters() []string {
	if m != nil {
		return m.Meters
	}
	return nil
}

func (m *GetMonitorInput) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *GetMonitorInput) GetStartTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *GetMonitorInput) GetEndTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type GetMonitorOutput struct {
	Action     string                           `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode    int32                            `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message    string                           `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	ResourceId string                           `protobuf:"bytes,4,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	MeterSet   []*GetMonitorOutput_ResponseItem `protobuf:"bytes,5,rep,name=meter_set,json=meterSet" json:"meter_set,omitempty"`
}

func (m *GetMonitorOutput) Reset()                    { *m = GetMonitorOutput{} }
func (m *GetMonitorOutput) String() string            { return proto.CompactTextString(m) }
func (*GetMonitorOutput) ProtoMessage()               {}
func (*GetMonitorOutput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *GetMonitorOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *GetMonitorOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *GetMonitorOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetMonitorOutput) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *GetMonitorOutput) GetMeterSet() []*GetMonitorOutput_ResponseItem {
	if m != nil {
		return m.MeterSet
	}
	return nil
}

type GetMonitorOutput_ResponseItem struct {
	// data: [[1392072000,[12,12]],[15,29],[11,12]]
	VxnetId  string `protobuf:"bytes,2,opt,name=vxnet_id,json=vxnetId" json:"vxnet_id,omitempty"`
	MeterId  string `protobuf:"bytes,3,opt,name=meter_id,json=meterId" json:"meter_id,omitempty"`
	Sequence int32  `protobuf:"varint,4,opt,name=sequence" json:"sequence,omitempty"`
}

func (m *GetMonitorOutput_ResponseItem) Reset()         { *m = GetMonitorOutput_ResponseItem{} }
func (m *GetMonitorOutput_ResponseItem) String() string { return proto.CompactTextString(m) }
func (*GetMonitorOutput_ResponseItem) ProtoMessage()    {}
func (*GetMonitorOutput_ResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{2, 0}
}

func (m *GetMonitorOutput_ResponseItem) GetVxnetId() string {
	if m != nil {
		return m.VxnetId
	}
	return ""
}

func (m *GetMonitorOutput_ResponseItem) GetMeterId() string {
	if m != nil {
		return m.MeterId
	}
	return ""
}

func (m *GetMonitorOutput_ResponseItem) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type GetLoadBalancerMonitorInput struct {
	Resource  string                      `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	Meters    []string                    `protobuf:"bytes,2,rep,name=meters" json:"meters,omitempty"`
	Step      string                      `protobuf:"bytes,3,opt,name=step" json:"step,omitempty"`
	StartTime *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime   *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *GetLoadBalancerMonitorInput) Reset()                    { *m = GetLoadBalancerMonitorInput{} }
func (m *GetLoadBalancerMonitorInput) String() string            { return proto.CompactTextString(m) }
func (*GetLoadBalancerMonitorInput) ProtoMessage()               {}
func (*GetLoadBalancerMonitorInput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

func (m *GetLoadBalancerMonitorInput) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *GetLoadBalancerMonitorInput) GetMeters() []string {
	if m != nil {
		return m.Meters
	}
	return nil
}

func (m *GetLoadBalancerMonitorInput) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *GetLoadBalancerMonitorInput) GetStartTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *GetLoadBalancerMonitorInput) GetEndTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type GetLoadBalancerMonitorOutput struct {
	Action     string                                       `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode    int32                                        `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message    string                                       `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	ResourceId string                                       `protobuf:"bytes,4,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	MeterSet   []*GetLoadBalancerMonitorOutput_ResponseItem `protobuf:"bytes,5,rep,name=meter_set,json=meterSet" json:"meter_set,omitempty"`
}

func (m *GetLoadBalancerMonitorOutput) Reset()                    { *m = GetLoadBalancerMonitorOutput{} }
func (m *GetLoadBalancerMonitorOutput) String() string            { return proto.CompactTextString(m) }
func (*GetLoadBalancerMonitorOutput) ProtoMessage()               {}
func (*GetLoadBalancerMonitorOutput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

func (m *GetLoadBalancerMonitorOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *GetLoadBalancerMonitorOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *GetLoadBalancerMonitorOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetLoadBalancerMonitorOutput) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *GetLoadBalancerMonitorOutput) GetMeterSet() []*GetLoadBalancerMonitorOutput_ResponseItem {
	if m != nil {
		return m.MeterSet
	}
	return nil
}

type GetLoadBalancerMonitorOutput_ResponseItem struct {
	EipId string `protobuf:"bytes,1,opt,name=eip_id,json=eipId" json:"eip_id,omitempty"`
	// data: ...
	MeterId string `protobuf:"bytes,3,opt,name=meter_id,json=meterId" json:"meter_id,omitempty"`
}

func (m *GetLoadBalancerMonitorOutput_ResponseItem) Reset() {
	*m = GetLoadBalancerMonitorOutput_ResponseItem{}
}
func (m *GetLoadBalancerMonitorOutput_ResponseItem) String() string { return proto.CompactTextString(m) }
func (*GetLoadBalancerMonitorOutput_ResponseItem) ProtoMessage()    {}
func (*GetLoadBalancerMonitorOutput_ResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{4, 0}
}

func (m *GetLoadBalancerMonitorOutput_ResponseItem) GetEipId() string {
	if m != nil {
		return m.EipId
	}
	return ""
}

func (m *GetLoadBalancerMonitorOutput_ResponseItem) GetMeterId() string {
	if m != nil {
		return m.MeterId
	}
	return ""
}

type GetRDBMonitorInput struct {
}

func (m *GetRDBMonitorInput) Reset()                    { *m = GetRDBMonitorInput{} }
func (m *GetRDBMonitorInput) String() string            { return proto.CompactTextString(m) }
func (*GetRDBMonitorInput) ProtoMessage()               {}
func (*GetRDBMonitorInput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

type GetRDBMonitorOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *GetRDBMonitorOutput) Reset()                    { *m = GetRDBMonitorOutput{} }
func (m *GetRDBMonitorOutput) String() string            { return proto.CompactTextString(m) }
func (*GetRDBMonitorOutput) ProtoMessage()               {}
func (*GetRDBMonitorOutput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{6} }

func (m *GetRDBMonitorOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *GetRDBMonitorOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *GetRDBMonitorOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetCacheMonitorInput struct {
}

func (m *GetCacheMonitorInput) Reset()                    { *m = GetCacheMonitorInput{} }
func (m *GetCacheMonitorInput) String() string            { return proto.CompactTextString(m) }
func (*GetCacheMonitorInput) ProtoMessage()               {}
func (*GetCacheMonitorInput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{7} }

type GetCacheMonitorOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *GetCacheMonitorOutput) Reset()                    { *m = GetCacheMonitorOutput{} }
func (m *GetCacheMonitorOutput) String() string            { return proto.CompactTextString(m) }
func (*GetCacheMonitorOutput) ProtoMessage()               {}
func (*GetCacheMonitorOutput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{8} }

func (m *GetCacheMonitorOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *GetCacheMonitorOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *GetCacheMonitorOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetZooKeeperMonitorInput struct {
}

func (m *GetZooKeeperMonitorInput) Reset()                    { *m = GetZooKeeperMonitorInput{} }
func (m *GetZooKeeperMonitorInput) String() string            { return proto.CompactTextString(m) }
func (*GetZooKeeperMonitorInput) ProtoMessage()               {}
func (*GetZooKeeperMonitorInput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{9} }

type GetZooKeeperMonitorOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *GetZooKeeperMonitorOutput) Reset()                    { *m = GetZooKeeperMonitorOutput{} }
func (m *GetZooKeeperMonitorOutput) String() string            { return proto.CompactTextString(m) }
func (*GetZooKeeperMonitorOutput) ProtoMessage()               {}
func (*GetZooKeeperMonitorOutput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{10} }

func (m *GetZooKeeperMonitorOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *GetZooKeeperMonitorOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *GetZooKeeperMonitorOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetQueueMonitorInput struct {
}

func (m *GetQueueMonitorInput) Reset()                    { *m = GetQueueMonitorInput{} }
func (m *GetQueueMonitorInput) String() string            { return proto.CompactTextString(m) }
func (*GetQueueMonitorInput) ProtoMessage()               {}
func (*GetQueueMonitorInput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{11} }

type GetQueueMonitorOutput struct {
	Action  string `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode int32  `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *GetQueueMonitorOutput) Reset()                    { *m = GetQueueMonitorOutput{} }
func (m *GetQueueMonitorOutput) String() string            { return proto.CompactTextString(m) }
func (*GetQueueMonitorOutput) ProtoMessage()               {}
func (*GetQueueMonitorOutput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{12} }

func (m *GetQueueMonitorOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *GetQueueMonitorOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *GetQueueMonitorOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MonitorServiceProperties)(nil), "service.MonitorServiceProperties")
	proto.RegisterType((*GetMonitorInput)(nil), "service.GetMonitorInput")
	proto.RegisterType((*GetMonitorOutput)(nil), "service.GetMonitorOutput")
	proto.RegisterType((*GetMonitorOutput_ResponseItem)(nil), "service.GetMonitorOutput.ResponseItem")
	proto.RegisterType((*GetLoadBalancerMonitorInput)(nil), "service.GetLoadBalancerMonitorInput")
	proto.RegisterType((*GetLoadBalancerMonitorOutput)(nil), "service.GetLoadBalancerMonitorOutput")
	proto.RegisterType((*GetLoadBalancerMonitorOutput_ResponseItem)(nil), "service.GetLoadBalancerMonitorOutput.ResponseItem")
	proto.RegisterType((*GetRDBMonitorInput)(nil), "service.GetRDBMonitorInput")
	proto.RegisterType((*GetRDBMonitorOutput)(nil), "service.GetRDBMonitorOutput")
	proto.RegisterType((*GetCacheMonitorInput)(nil), "service.GetCacheMonitorInput")
	proto.RegisterType((*GetCacheMonitorOutput)(nil), "service.GetCacheMonitorOutput")
	proto.RegisterType((*GetZooKeeperMonitorInput)(nil), "service.GetZooKeeperMonitorInput")
	proto.RegisterType((*GetZooKeeperMonitorOutput)(nil), "service.GetZooKeeperMonitorOutput")
	proto.RegisterType((*GetQueueMonitorInput)(nil), "service.GetQueueMonitorInput")
	proto.RegisterType((*GetQueueMonitorOutput)(nil), "service.GetQueueMonitorOutput")
}

type MonitorServiceInterface interface {
	GetMonitor(in *GetMonitorInput) (out *GetMonitorOutput, err error)
	GetLoadBalancerMonitor(in *GetLoadBalancerMonitorInput) (out *GetLoadBalancerMonitorOutput, err error)
	GetRDBMonitor(in *GetRDBMonitorInput) (out *GetRDBMonitorOutput, err error)
	GetCacheMonitor(in *GetCacheMonitorInput) (out *GetCacheMonitorOutput, err error)
	GetZooKeeperMonitor(in *GetZooKeeperMonitorInput) (out *GetZooKeeperMonitorOutput, err error)
	GetQueueMonitor(in *GetQueueMonitorInput) (out *GetQueueMonitorOutput, err error)
}

type MonitorService struct {
	Config           *config.Config
	Properties       *MonitorServiceProperties
	LastResponseBody string
}

func NewMonitorService(conf *config.Config, zone string) (p *MonitorService) {
	return &MonitorService{
		Config:     conf,
		Properties: &MonitorServiceProperties{Zone: zone},
	}
}

func (s *QingCloudService) Monitor(zone string) (*MonitorService, error) {
	properties := &MonitorServiceProperties{
		Zone: zone,
	}

	return &MonitorService{Config: s.Config, Properties: properties}, nil
}

func (p *MonitorService) GetMonitor(in *GetMonitorInput) (out *GetMonitorOutput, err error) {
	if in == nil {
		in = &GetMonitorInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "GetMonitor",
		RequestMethod: "GET", // GET or POST
	}

	x := &GetMonitorOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *GetMonitorInput) Validate() error {
	return nil
}

func (p *MonitorService) GetLoadBalancerMonitor(in *GetLoadBalancerMonitorInput) (out *GetLoadBalancerMonitorOutput, err error) {
	if in == nil {
		in = &GetLoadBalancerMonitorInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "GetLoadBalancerMonitor",
		RequestMethod: "GET", // GET or POST
	}

	x := &GetLoadBalancerMonitorOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *GetLoadBalancerMonitorInput) Validate() error {
	return nil
}

func (p *MonitorService) GetRDBMonitor(in *GetRDBMonitorInput) (out *GetRDBMonitorOutput, err error) {
	if in == nil {
		in = &GetRDBMonitorInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "GetRDBMonitor",
		RequestMethod: "GET", // GET or POST
	}

	x := &GetRDBMonitorOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *GetRDBMonitorInput) Validate() error {
	return nil
}

func (p *MonitorService) GetCacheMonitor(in *GetCacheMonitorInput) (out *GetCacheMonitorOutput, err error) {
	if in == nil {
		in = &GetCacheMonitorInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "GetCacheMonitor",
		RequestMethod: "GET", // GET or POST
	}

	x := &GetCacheMonitorOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *GetCacheMonitorInput) Validate() error {
	return nil
}

func (p *MonitorService) GetZooKeeperMonitor(in *GetZooKeeperMonitorInput) (out *GetZooKeeperMonitorOutput, err error) {
	if in == nil {
		in = &GetZooKeeperMonitorInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "GetZooKeeperMonitor",
		RequestMethod: "GET", // GET or POST
	}

	x := &GetZooKeeperMonitorOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *GetZooKeeperMonitorInput) Validate() error {
	return nil
}

func (p *MonitorService) GetQueueMonitor(in *GetQueueMonitorInput) (out *GetQueueMonitorOutput, err error) {
	if in == nil {
		in = &GetQueueMonitorInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "GetQueueMonitor",
		RequestMethod: "GET", // GET or POST
	}

	x := &GetQueueMonitorOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	p.LastResponseBody = o.ResponseBody

	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *GetQueueMonitorInput) Validate() error {
	return nil
}

func init() { proto.RegisterFile("monitor.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x96, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xc7, 0x95, 0x34, 0x97, 0xe6, 0xf4, 0xeb, 0x07, 0x1a, 0xda, 0xc8, 0x75, 0x5b, 0x1a, 0x2c,
	0x40, 0x59, 0xb9, 0x52, 0x10, 0x0b, 0x76, 0xd0, 0x20, 0x45, 0xe1, 0xa2, 0xb6, 0x2e, 0x2b, 0x84,
	0x14, 0x5c, 0xcf, 0x21, 0xb5, 0x48, 0x3c, 0xee, 0xcc, 0x71, 0x85, 0x78, 0x04, 0x5e, 0x02, 0x89,
	0x0d, 0x0f, 0xc3, 0x03, 0xf0, 0x1c, 0xbc, 0x01, 0x1a, 0x5f, 0x5a, 0x3b, 0x71, 0x5a, 0x36, 0x11,
	0x12, 0x9b, 0xc8, 0x67, 0xce, 0x9c, 0xcb, 0xff, 0xcc, 0xcf, 0xe3, 0xc0, 0xfa, 0x54, 0x04, 0x3e,
	0x09, 0x69, 0x87, 0x52, 0x90, 0x60, 0x4d, 0x85, 0xf2, 0xc2, 0xf7, 0xd0, 0xdc, 0x3d, 0xf7, 0x83,
	0xb1, 0x37, 0x11, 0x11, 0x1f, 0x29, 0xfe, 0x71, 0x24, 0xa3, 0x09, 0xee, 0xeb, 0x9f, 0x64, 0x9f,
	0xb9, 0x37, 0x16, 0x62, 0x3c, 0xc1, 0xfd, 0xd8, 0x3a, 0x8d, 0x3e, 0xec, 0x93, 0x3f, 0x45, 0x45,
	0xee, 0x34, 0x4c, 0x36, 0x58, 0x36, 0x18, 0xaf, 0x93, 0xcc, 0x27, 0x49, 0xc6, 0x23, 0x29, 0x42,
	0x94, 0xe4, 0xa3, 0x62, 0x0c, 0x6a, 0x9f, 0x45, 0x80, 0x46, 0xa5, 0x53, 0xe9, 0xb6, 0x9c, 0xf8,
	0xd9, 0xfa, 0x51, 0x81, 0x5b, 0x03, 0xa4, 0x34, 0x66, 0x18, 0x84, 0x11, 0x31, 0x13, 0x56, 0x25,
	0x2a, 0x11, 0x49, 0x2f, 0xdb, 0x7b, 0x69, 0xb3, 0x36, 0x34, 0xa6, 0x48, 0x28, 0x95, 0x51, 0xed,
	0xac, 0x74, 0x5b, 0x4e, 0x6a, 0xe9, 0xdc, 0x8a, 0x30, 0x34, 0x56, 0x92, 0xdc, 0xfa, 0x99, 0x3d,
	0x01, 0x50, 0xe4, 0x4a, 0x1a, 0xe9, 0x26, 0x8d, 0x5a, 0xa7, 0xd2, 0x5d, 0xeb, 0x99, 0x76, 0xa2,
	0xc0, 0xce, 0x14, 0xd8, 0x6f, 0x32, 0x05, 0x4e, 0x2b, 0xde, 0xad, 0x6d, 0xf6, 0x18, 0x56, 0x31,
	0xe0, 0x49, 0x60, 0xfd, 0xc6, 0xc0, 0x26, 0x06, 0x5c, 0x5b, 0xd6, 0xf7, 0x2a, 0xdc, 0xbe, 0x52,
	0x73, 0x18, 0x91, 0x96, 0xd3, 0x86, 0x86, 0xeb, 0x91, 0x2f, 0x82, 0x54, 0x4c, 0x6a, 0xb1, 0x2d,
	0x2d, 0x93, 0x46, 0x9e, 0xe0, 0x68, 0x54, 0x3b, 0x95, 0x6e, 0xdd, 0x69, 0x4a, 0xa4, 0xbe, 0xe0,
	0xc8, 0x0c, 0x68, 0x4e, 0x51, 0x29, 0x77, 0x8c, 0xa9, 0xa0, 0xcc, 0x64, 0x7b, 0xb0, 0x96, 0xcd,
	0x62, 0xe4, 0xf3, 0x58, 0x54, 0xcb, 0x81, 0x6c, 0x69, 0xc8, 0x59, 0x1f, 0x5a, 0xf1, 0x48, 0x46,
	0x0a, 0xc9, 0xa8, 0x77, 0x56, 0xba, 0x6b, 0xbd, 0x87, 0x76, 0x7a, 0xba, 0xf6, 0x6c, 0x6f, 0xb6,
	0x83, 0x2a, 0x14, 0x81, 0xc2, 0x21, 0xe1, 0xd4, 0x59, 0x8d, 0x03, 0x4f, 0x90, 0xcc, 0xf7, 0xf0,
	0x5f, 0xde, 0xa3, 0x5b, 0xbd, 0xf8, 0x14, 0x20, 0xe9, 0x92, 0xd5, 0xa4, 0xa1, 0xd8, 0x1e, 0x72,
	0xed, 0x4a, 0xea, 0xf9, 0xfc, 0xaa, 0x57, 0x42, 0x39, 0xe4, 0xfa, 0x1c, 0x15, 0x9e, 0x47, 0x18,
	0x78, 0xc9, 0xf4, 0xeb, 0xce, 0xa5, 0x6d, 0xfd, 0xac, 0xc0, 0xf6, 0x00, 0xe9, 0x95, 0x70, 0xf9,
	0x81, 0x3b, 0x71, 0x03, 0x0f, 0xe5, 0x3f, 0xc2, 0xc0, 0xd7, 0x2a, 0xec, 0x94, 0x2b, 0xfb, 0x2b,
	0x3c, 0x1c, 0xce, 0xf3, 0xd0, 0xcb, 0xf3, 0xb0, 0xb0, 0xcf, 0x45, 0x6c, 0x3c, 0x9d, 0x61, 0x63,
	0x13, 0x1a, 0xe8, 0x87, 0xba, 0x78, 0x22, 0xa7, 0x8e, 0x7e, 0x78, 0x2d, 0x17, 0xd6, 0x06, 0xb0,
	0x01, 0x92, 0xf3, 0xfc, 0x20, 0x7f, 0xe2, 0xd6, 0x29, 0xdc, 0x29, 0xac, 0x2e, 0x61, 0x5a, 0x56,
	0x1b, 0x36, 0x06, 0x48, 0x7d, 0xd7, 0x3b, 0xc3, 0x42, 0x6d, 0x0e, 0x9b, 0x33, 0xeb, 0xcb, 0xa8,
	0x6e, 0x82, 0x31, 0x40, 0x7a, 0x2b, 0xc4, 0x4b, 0xc4, 0xb0, 0xc8, 0xbb, 0x75, 0x06, 0x5b, 0x25,
	0xbe, 0xe5, 0xcd, 0xe0, 0x38, 0xc2, 0xa8, 0x6c, 0x06, 0xf9, 0xf5, 0x25, 0x54, 0xef, 0x7d, 0xab,
	0xc1, 0xff, 0xc5, 0x0f, 0x04, 0x7b, 0x06, 0x70, 0x75, 0x2f, 0x31, 0xa3, 0xe4, 0xb2, 0x8a, 0x1b,
	0x34, 0xb7, 0x16, 0x5e, 0x63, 0x0c, 0xa1, 0x5d, 0x8e, 0x32, 0xbb, 0x7f, 0x03, 0xeb, 0x49, 0xea,
	0x07, 0x7f, 0xf4, 0x46, 0xb0, 0x17, 0xb0, 0x5e, 0x40, 0x94, 0x6d, 0xe7, 0xe3, 0x66, 0x80, 0x36,
	0x77, 0xca, 0x9d, 0x69, 0xae, 0xa3, 0xf8, 0xbb, 0x97, 0x47, 0x8e, 0xed, 0xe6, 0x03, 0xe6, 0x20,
	0x35, 0xef, 0x2e, 0x72, 0xa7, 0x19, 0xdf, 0xc5, 0x2f, 0xd0, 0x2c, 0x42, 0xec, 0x5e, 0x3e, 0xac,
	0x14, 0x3e, 0xd3, 0xba, 0x6e, 0x4b, 0xa1, 0xdf, 0x3c, 0x1e, 0xc5, 0x7e, 0xe7, 0x80, 0x2a, 0xf6,
	0x3b, 0xcf, 0x95, 0x69, 0x7c, 0xf9, 0x55, 0xdb, 0x60, 0xad, 0x63, 0x3f, 0x18, 0xf7, 0xf5, 0x1f,
	0x0e, 0xb3, 0x99, 0xfa, 0x4f, 0x1b, 0xf1, 0xfd, 0xfa, 0xe8, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x02, 0x10, 0xff, 0xe1, 0xa5, 0x08, 0x00, 0x00,
}
