// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nic.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import "github.com/chai2010/qingcloud-go/config"
import "github.com/chai2010/qingcloud-go/request"
import "github.com/chai2010/qingcloud-go/request/data"

var _ = config.Config{}
var _ = request.Request{}
var _ = data.Operation{}

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NicServiceProperties struct {
	Zone string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
}

func (m *NicServiceProperties) Reset()                    { *m = NicServiceProperties{} }
func (m *NicServiceProperties) String() string            { return proto.CompactTextString(m) }
func (*NicServiceProperties) ProtoMessage()               {}
func (*NicServiceProperties) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{0} }

func (m *NicServiceProperties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type CreateNicsInput struct {
}

func (m *CreateNicsInput) Reset()                    { *m = CreateNicsInput{} }
func (m *CreateNicsInput) String() string            { return proto.CompactTextString(m) }
func (*CreateNicsInput) ProtoMessage()               {}
func (*CreateNicsInput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{1} }

type CreateNicsOutput struct {
}

func (m *CreateNicsOutput) Reset()                    { *m = CreateNicsOutput{} }
func (m *CreateNicsOutput) String() string            { return proto.CompactTextString(m) }
func (*CreateNicsOutput) ProtoMessage()               {}
func (*CreateNicsOutput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{2} }

type DescribeNicsInput struct {
	Instances []string `protobuf:"bytes,1,rep,name=instances" json:"instances,omitempty"`
	Limit     int32    `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	NicName   string   `protobuf:"bytes,3,opt,name=nic_name,json=nicName" json:"nic_name,omitempty"`
	Nics      []string `protobuf:"bytes,4,rep,name=nics" json:"nics,omitempty"`
	Offset    int32    `protobuf:"varint,5,opt,name=offset" json:"offset,omitempty"`
	Status    string   `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	VxnetType int32    `protobuf:"varint,7,opt,name=vxnet_type,json=vxnetType" json:"vxnet_type,omitempty"`
	Vxnets    []string `protobuf:"bytes,8,rep,name=vxnets" json:"vxnets,omitempty"`
}

func (m *DescribeNicsInput) Reset()                    { *m = DescribeNicsInput{} }
func (m *DescribeNicsInput) String() string            { return proto.CompactTextString(m) }
func (*DescribeNicsInput) ProtoMessage()               {}
func (*DescribeNicsInput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{3} }

func (m *DescribeNicsInput) GetInstances() []string {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *DescribeNicsInput) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeNicsInput) GetNicName() string {
	if m != nil {
		return m.NicName
	}
	return ""
}

func (m *DescribeNicsInput) GetNics() []string {
	if m != nil {
		return m.Nics
	}
	return nil
}

func (m *DescribeNicsInput) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeNicsInput) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DescribeNicsInput) GetVxnetType() int32 {
	if m != nil {
		return m.VxnetType
	}
	return 0
}

func (m *DescribeNicsInput) GetVxnets() []string {
	if m != nil {
		return m.Vxnets
	}
	return nil
}

type DescribeNicsOutput struct {
	Message    string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Action     string `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	NicSet     []*NIC `protobuf:"bytes,3,rep,name=nic_set,json=nicSet" json:"nic_set,omitempty"`
	RetCode    int32  `protobuf:"varint,4,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	TotalCount int32  `protobuf:"varint,5,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
}

func (m *DescribeNicsOutput) Reset()                    { *m = DescribeNicsOutput{} }
func (m *DescribeNicsOutput) String() string            { return proto.CompactTextString(m) }
func (*DescribeNicsOutput) ProtoMessage()               {}
func (*DescribeNicsOutput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{4} }

func (m *DescribeNicsOutput) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DescribeNicsOutput) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DescribeNicsOutput) GetNicSet() []*NIC {
	if m != nil {
		return m.NicSet
	}
	return nil
}

func (m *DescribeNicsOutput) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *DescribeNicsOutput) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type AttachNicsInput struct {
}

func (m *AttachNicsInput) Reset()                    { *m = AttachNicsInput{} }
func (m *AttachNicsInput) String() string            { return proto.CompactTextString(m) }
func (*AttachNicsInput) ProtoMessage()               {}
func (*AttachNicsInput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{5} }

type AttachNicsOutput struct {
}

func (m *AttachNicsOutput) Reset()                    { *m = AttachNicsOutput{} }
func (m *AttachNicsOutput) String() string            { return proto.CompactTextString(m) }
func (*AttachNicsOutput) ProtoMessage()               {}
func (*AttachNicsOutput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{6} }

type DetachNicsInput struct {
}

func (m *DetachNicsInput) Reset()                    { *m = DetachNicsInput{} }
func (m *DetachNicsInput) String() string            { return proto.CompactTextString(m) }
func (*DetachNicsInput) ProtoMessage()               {}
func (*DetachNicsInput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{7} }

type DetachNicsOutput struct {
}

func (m *DetachNicsOutput) Reset()                    { *m = DetachNicsOutput{} }
func (m *DetachNicsOutput) String() string            { return proto.CompactTextString(m) }
func (*DetachNicsOutput) ProtoMessage()               {}
func (*DetachNicsOutput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{8} }

type ModifyNicAttributesInput struct {
}

func (m *ModifyNicAttributesInput) Reset()                    { *m = ModifyNicAttributesInput{} }
func (m *ModifyNicAttributesInput) String() string            { return proto.CompactTextString(m) }
func (*ModifyNicAttributesInput) ProtoMessage()               {}
func (*ModifyNicAttributesInput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{9} }

type ModifyNicAttributesOutput struct {
}

func (m *ModifyNicAttributesOutput) Reset()                    { *m = ModifyNicAttributesOutput{} }
func (m *ModifyNicAttributesOutput) String() string            { return proto.CompactTextString(m) }
func (*ModifyNicAttributesOutput) ProtoMessage()               {}
func (*ModifyNicAttributesOutput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{10} }

type DeleteNicsInput struct {
}

func (m *DeleteNicsInput) Reset()                    { *m = DeleteNicsInput{} }
func (m *DeleteNicsInput) String() string            { return proto.CompactTextString(m) }
func (*DeleteNicsInput) ProtoMessage()               {}
func (*DeleteNicsInput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{11} }

type DeleteNicsOutput struct {
}

func (m *DeleteNicsOutput) Reset()                    { *m = DeleteNicsOutput{} }
func (m *DeleteNicsOutput) String() string            { return proto.CompactTextString(m) }
func (*DeleteNicsOutput) ProtoMessage()               {}
func (*DeleteNicsOutput) Descriptor() ([]byte, []int) { return fileDescriptor14, []int{12} }

func init() {
	proto.RegisterType((*NicServiceProperties)(nil), "service.NicServiceProperties")
	proto.RegisterType((*CreateNicsInput)(nil), "service.CreateNicsInput")
	proto.RegisterType((*CreateNicsOutput)(nil), "service.CreateNicsOutput")
	proto.RegisterType((*DescribeNicsInput)(nil), "service.DescribeNicsInput")
	proto.RegisterType((*DescribeNicsOutput)(nil), "service.DescribeNicsOutput")
	proto.RegisterType((*AttachNicsInput)(nil), "service.AttachNicsInput")
	proto.RegisterType((*AttachNicsOutput)(nil), "service.AttachNicsOutput")
	proto.RegisterType((*DetachNicsInput)(nil), "service.DetachNicsInput")
	proto.RegisterType((*DetachNicsOutput)(nil), "service.DetachNicsOutput")
	proto.RegisterType((*ModifyNicAttributesInput)(nil), "service.ModifyNicAttributesInput")
	proto.RegisterType((*ModifyNicAttributesOutput)(nil), "service.ModifyNicAttributesOutput")
	proto.RegisterType((*DeleteNicsInput)(nil), "service.DeleteNicsInput")
	proto.RegisterType((*DeleteNicsOutput)(nil), "service.DeleteNicsOutput")
}

type NicServiceInterface interface {
	CreateNics(in *CreateNicsInput) (out *CreateNicsOutput, err error)
	DescribeNics(in *DescribeNicsInput) (out *DescribeNicsOutput, err error)
	AttachNics(in *AttachNicsInput) (out *AttachNicsOutput, err error)
	DetachNics(in *DetachNicsInput) (out *DetachNicsOutput, err error)
	ModifyNicAttributes(in *ModifyNicAttributesInput) (out *ModifyNicAttributesOutput, err error)
	DeleteNics(in *DeleteNicsInput) (out *DeleteNicsOutput, err error)
}

type NicService struct {
	Config     *config.Config
	Properties *NicServiceProperties
}

func NewNicService(conf *config.Config, zone string) (p *NicService) {
	return &NicService{
		Config:     conf,
		Properties: &NicServiceProperties{Zone: zone},
	}
}

func (s *QingCloudService) Nic(zone string) (*NicService, error) {
	properties := &NicServiceProperties{
		Zone: zone,
	}

	return &NicService{Config: s.Config, Properties: properties}, nil
}

func (p *NicService) CreateNics(in *CreateNicsInput) (out *CreateNicsOutput, err error) {
	if in == nil {
		in = &CreateNicsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateNics",
		RequestMethod: "GET", // GET or POST
	}

	x := &CreateNicsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *CreateNicsInput) Validate() error {
	return nil
}

func (p *NicService) DescribeNics(in *DescribeNicsInput) (out *DescribeNicsOutput, err error) {
	if in == nil {
		in = &DescribeNicsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeNics",
		RequestMethod: "GET", // GET or POST
	}

	x := &DescribeNicsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DescribeNicsInput) Validate() error {
	return nil
}

func (p *NicService) AttachNics(in *AttachNicsInput) (out *AttachNicsOutput, err error) {
	if in == nil {
		in = &AttachNicsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "AttachNics",
		RequestMethod: "GET", // GET or POST
	}

	x := &AttachNicsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *AttachNicsInput) Validate() error {
	return nil
}

func (p *NicService) DetachNics(in *DetachNicsInput) (out *DetachNicsOutput, err error) {
	if in == nil {
		in = &DetachNicsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DetachNics",
		RequestMethod: "GET", // GET or POST
	}

	x := &DetachNicsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DetachNicsInput) Validate() error {
	return nil
}

func (p *NicService) ModifyNicAttributes(in *ModifyNicAttributesInput) (out *ModifyNicAttributesOutput, err error) {
	if in == nil {
		in = &ModifyNicAttributesInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyNicAttributes",
		RequestMethod: "GET", // GET or POST
	}

	x := &ModifyNicAttributesOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *ModifyNicAttributesInput) Validate() error {
	return nil
}

func (p *NicService) DeleteNics(in *DeleteNicsInput) (out *DeleteNicsOutput, err error) {
	if in == nil {
		in = &DeleteNicsInput{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteNics",
		RequestMethod: "GET", // GET or POST
	}

	x := &DeleteNicsOutput{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *DeleteNicsInput) Validate() error {
	return nil
}

func init() { proto.RegisterFile("nic.proto", fileDescriptor14) }

var fileDescriptor14 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdb, 0x8a, 0x13, 0x41,
	0x10, 0x65, 0xcc, 0x6d, 0xa7, 0xb2, 0xb0, 0xa6, 0x5d, 0xa4, 0x33, 0xab, 0x18, 0x03, 0x42, 0xf0,
	0x21, 0x0f, 0xeb, 0x17, 0x84, 0x2c, 0xc8, 0x3e, 0x18, 0x25, 0xfa, 0x28, 0x84, 0x49, 0xa7, 0xa2,
	0x0d, 0x49, 0xf7, 0x30, 0x5d, 0xb3, 0x18, 0xff, 0xc8, 0xaf, 0xf0, 0x4b, 0xfc, 0x17, 0xe9, 0x9e,
	0x4e, 0x7a, 0x66, 0x36, 0xfa, 0x36, 0x75, 0xaa, 0xfa, 0xe4, 0xd4, 0x39, 0x45, 0x20, 0x56, 0x52,
	0x4c, 0xb3, 0x5c, 0x93, 0x66, 0x3d, 0x83, 0xf9, 0x83, 0x14, 0x98, 0xf4, 0xe9, 0x90, 0xa1, 0x29,
	0xd1, 0xf1, 0x5b, 0xb8, 0x5e, 0x48, 0xf1, 0xb9, 0x6c, 0x7d, 0xca, 0x75, 0x86, 0x39, 0x49, 0x34,
	0x8c, 0x41, 0xfb, 0xa7, 0x56, 0xc8, 0xa3, 0x51, 0x34, 0x89, 0x97, 0xee, 0x7b, 0x3c, 0x80, 0xab,
	0x79, 0x8e, 0x29, 0xe1, 0x42, 0x0a, 0x73, 0xaf, 0xb2, 0x82, 0xc6, 0x0c, 0x9e, 0x06, 0xe8, 0x63,
	0x41, 0x16, 0xfb, 0x13, 0xc1, 0xe0, 0x0e, 0x8d, 0xc8, 0xe5, 0x3a, 0x4c, 0xb2, 0x17, 0x10, 0x4b,
	0x65, 0x28, 0x55, 0x02, 0x0d, 0x8f, 0x46, 0xad, 0x49, 0xbc, 0x0c, 0x00, 0xbb, 0x86, 0xce, 0x4e,
	0xee, 0x25, 0xf1, 0x27, 0xa3, 0x68, 0xd2, 0x59, 0x96, 0x05, 0x1b, 0xc2, 0x85, 0x92, 0x62, 0xa5,
	0xd2, 0x3d, 0xf2, 0x96, 0x13, 0xd2, 0x53, 0x52, 0x2c, 0xd2, 0x3d, 0x5a, 0x7d, 0x4a, 0x0a, 0xc3,
	0xdb, 0x8e, 0xc9, 0x7d, 0xb3, 0xe7, 0xd0, 0xd5, 0xdb, 0xad, 0x41, 0xe2, 0x1d, 0xc7, 0xe2, 0x2b,
	0x8b, 0x1b, 0x4a, 0xa9, 0x30, 0xbc, 0xeb, 0x48, 0x7c, 0xc5, 0x5e, 0x02, 0x3c, 0xfc, 0x50, 0x48,
	0x2b, 0x6b, 0x08, 0xef, 0xb9, 0x37, 0xb1, 0x43, 0xbe, 0x1c, 0x32, 0xb4, 0xcf, 0x5c, 0x61, 0xf8,
	0x85, 0xfb, 0x11, 0x5f, 0x8d, 0x7f, 0x45, 0xc0, 0xaa, 0xfb, 0x95, 0x6b, 0x33, 0x0e, 0xbd, 0x3d,
	0x1a, 0x93, 0x7e, 0x3b, 0x9a, 0x76, 0x2c, 0x2d, 0x51, 0x2a, 0x48, 0x6a, 0xe5, 0xb6, 0x8b, 0x97,
	0xbe, 0x62, 0x6f, 0xc0, 0xae, 0xb3, 0xb2, 0x82, 0x5b, 0xa3, 0xd6, 0xa4, 0x7f, 0x7b, 0x39, 0xf5,
	0x19, 0x4d, 0x17, 0xf7, 0xf3, 0x65, 0x57, 0xd9, 0x60, 0x9c, 0x0b, 0x39, 0xd2, 0x4a, 0xe8, 0x0d,
	0xf2, 0xb6, 0x13, 0xd9, 0xcb, 0x91, 0xe6, 0x7a, 0x83, 0xec, 0x15, 0xf4, 0x49, 0x53, 0xba, 0x5b,
	0x09, 0x5d, 0xa8, 0xe3, 0xda, 0xe0, 0xa0, 0xb9, 0x45, 0x6c, 0x64, 0x33, 0xa2, 0x54, 0x7c, 0xaf,
	0x45, 0x16, 0x20, 0x1f, 0xd9, 0x00, 0xae, 0xee, 0xf0, 0xd1, 0x58, 0x80, 0xfc, 0x58, 0x02, 0xfc,
	0x83, 0xde, 0xc8, 0xed, 0x61, 0x21, 0xc5, 0x8c, 0x28, 0x97, 0xeb, 0x82, 0xd0, 0xcf, 0xdf, 0xc0,
	0xf0, 0x4c, 0xaf, 0xca, 0xbf, 0xc3, 0xc6, 0xe5, 0x04, 0xa8, 0x1c, 0xbb, 0xfd, 0xdd, 0x02, 0x08,
	0xd7, 0xc8, 0x66, 0x00, 0xe1, 0xb8, 0x18, 0x3f, 0x99, 0xd3, 0x38, 0xc2, 0x64, 0x78, 0xa6, 0xe3,
	0x43, 0x79, 0x0f, 0x97, 0xd5, 0xa8, 0x58, 0x72, 0x1a, 0x7d, 0x74, 0xa1, 0xc9, 0xcd, 0xd9, 0x9e,
	0x27, 0x9a, 0x01, 0x04, 0xd7, 0x2a, 0x5a, 0x1a, 0xee, 0x56, 0xb4, 0x34, 0x4d, 0xb6, 0x14, 0xc1,
	0xd1, 0x0a, 0x45, 0xc3, 0xf9, 0x0a, 0x45, 0x33, 0x00, 0xf6, 0x15, 0x9e, 0x9d, 0x31, 0x99, 0xbd,
	0x3e, 0xbd, 0xf8, 0x57, 0x3c, 0xc9, 0xf8, 0x7f, 0x23, 0x55, 0x81, 0xc7, 0x48, 0x6a, 0x02, 0x6b,
	0xd1, 0xd5, 0x04, 0xd6, 0x13, 0x5c, 0x77, 0xdd, 0xbf, 0xca, 0xbb, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xb3, 0xa5, 0xca, 0xf6, 0x78, 0x04, 0x00, 0x00,
}
