// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s2.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/chai2010/qingcloud-go/spec.pb/qingcloud_sdk_rule"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import "github.com/chai2010/qingcloud-go/config"
import "github.com/chai2010/qingcloud-go/request"
import "github.com/chai2010/qingcloud-go/request/data"

var _ = config.Config{}
var _ = request.Request{}
var _ = data.Operation{}

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type S2ServiceProperties struct {
	Zone string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
}

func (m *S2ServiceProperties) Reset()                    { *m = S2ServiceProperties{} }
func (m *S2ServiceProperties) String() string            { return proto.CompactTextString(m) }
func (*S2ServiceProperties) ProtoMessage()               {}
func (*S2ServiceProperties) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{0} }

func (m *S2ServiceProperties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func init() {
	proto.RegisterType((*S2ServiceProperties)(nil), "service.S2ServiceProperties")
}

type S2ServiceInterface interface {
	CreateS2Server(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DescribeS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	ModifyS2Server(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	ResizeS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DeleteS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	PowerOnS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	PowerOffS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	UpdateS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	ChangeS2ServerVxnet(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	CreateS2SharedTarget(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DescribeS2SharedTargets(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DeleteS2SharedTargets(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	EnableS2SharedTargets(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DisableS2SharedTargets(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	ModifyS2SharedTargetAttributes(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	AttachToS2SharedTarget(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DetachFromS2SharedTarget(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DescribeS2DefaultParameters(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	CreateS2Group(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DescribeS2Groups(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	ModifyS2Group(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DeleteS2Groups(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	CreateS2Account(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DescribeS2Accounts(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	ModifyS2Account(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DeleteS2Accounts(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	AssociateS2AccountGroup(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
	DissociateS2AccountGroup(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error)
}

type S2Service struct {
	Config     *config.Config
	Properties *S2ServiceProperties
}

func NewS2Service(conf *config.Config, zone string) (p *S2Service) {
	return &S2Service{
		Config:     conf,
		Properties: &S2ServiceProperties{Zone: zone},
	}
}

func (s *QingCloudService) S2(zone string) (*S2Service, error) {
	properties := &S2ServiceProperties{
		Zone: zone,
	}

	return &S2Service{Config: s.Config, Properties: properties}, nil
}

func (p *S2Service) CreateS2Server(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateS2Server",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DescribeS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeS2Servers",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) ModifyS2Server(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyS2Server",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) ResizeS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ResizeS2Servers",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DeleteS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteS2Servers",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) PowerOnS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "PowerOnS2Servers",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) PowerOffS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "PowerOffS2Servers",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) UpdateS2Servers(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "UpdateS2Servers",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) ChangeS2ServerVxnet(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ChangeS2ServerVxnet",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) CreateS2SharedTarget(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateS2SharedTarget",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DescribeS2SharedTargets(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeS2SharedTargets",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DeleteS2SharedTargets(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteS2SharedTargets",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) EnableS2SharedTargets(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "EnableS2SharedTargets",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DisableS2SharedTargets(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DisableS2SharedTargets",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) ModifyS2SharedTargetAttributes(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyS2SharedTargetAttributes",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) AttachToS2SharedTarget(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "AttachToS2SharedTarget",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DetachFromS2SharedTarget(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DetachFromS2SharedTarget",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DescribeS2DefaultParameters(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeS2DefaultParameters",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) CreateS2Group(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateS2Group",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DescribeS2Groups(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeS2Groups",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) ModifyS2Group(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyS2Group",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DeleteS2Groups(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteS2Groups",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) CreateS2Account(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "CreateS2Account",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DescribeS2Accounts(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DescribeS2Accounts",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) ModifyS2Account(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "ModifyS2Account",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DeleteS2Accounts(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DeleteS2Accounts",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) AssociateS2AccountGroup(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "AssociateS2AccountGroup",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func (p *S2Service) DissociateS2AccountGroup(in *google_protobuf1.Empty) (out *google_protobuf1.Empty, err error) {
	if in == nil {
		in = &google_protobuf1.Empty{}
	}
	o := &data.Operation{
		Config:        p.Config,
		Properties:    p.Properties,
		APIName:       "DissociateS2AccountGroup",
		RequestMethod: "GET", // GET or POST
	}

	x := &google_protobuf1.Empty{}
	r, err := request.New(o, in, x)
	if err != nil {
		return nil, err
	}

	err = r.Send()
	if err != nil {
		return nil, err
	}

	return x, err
}

func init() { proto.RegisterFile("s2.proto", fileDescriptor20) }

var fileDescriptor20 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xd1, 0x6e, 0x94, 0x40,
	0x14, 0x86, 0x53, 0xd3, 0xa8, 0x7b, 0x12, 0x17, 0x3b, 0xab, 0x6d, 0xb3, 0x8d, 0xc6, 0x78, 0xa5,
	0x37, 0x6c, 0x82, 0x0f, 0xe0, 0x22, 0x6c, 0x6b, 0x4d, 0x1a, 0xb1, 0x5b, 0xbd, 0x6d, 0x06, 0x38,
	0xb0, 0x13, 0xd9, 0x19, 0x9c, 0x19, 0xd4, 0xf6, 0x11, 0x7c, 0x41, 0x9f, 0xc3, 0x37, 0x30, 0x80,
	0xb0, 0xdc, 0x78, 0xc1, 0x4c, 0x6f, 0x36, 0xcb, 0x70, 0xf2, 0x9d, 0xff, 0x9c, 0xff, 0x9f, 0x04,
	0x78, 0xa8, 0x3c, 0xb7, 0x94, 0x42, 0x0b, 0xf2, 0x40, 0xa1, 0xfc, 0xce, 0x12, 0x9c, 0x3f, 0xfb,
	0xc6, 0x78, 0x9e, 0x14, 0xa2, 0x4a, 0xaf, 0x55, 0xfa, 0xf5, 0x5a, 0x56, 0x05, 0x2e, 0xea, 0x9f,
	0xb6, 0x6e, 0x7e, 0x92, 0x0b, 0x91, 0x17, 0xb8, 0x68, 0x9e, 0xe2, 0x2a, 0x5b, 0xe0, 0xb6, 0xd4,
	0x37, 0xed, 0xcb, 0x97, 0xaf, 0x61, 0xb6, 0xf6, 0xd6, 0x2d, 0x28, 0x92, 0xa2, 0x44, 0xa9, 0x19,
	0x2a, 0x42, 0x60, 0xff, 0x56, 0x70, 0x3c, 0xde, 0x7b, 0xb1, 0xf7, 0x6a, 0x72, 0xd9, 0xfc, 0xf7,
	0x7e, 0x3b, 0x30, 0xe9, 0x6b, 0xc9, 0x12, 0xa6, 0x81, 0x44, 0xaa, 0xb1, 0x3d, 0x42, 0x49, 0x0e,
	0xdd, 0xb6, 0x91, 0xdb, 0x35, 0x72, 0x57, 0x75, 0xa3, 0xf9, 0x7f, 0xce, 0x49, 0x00, 0x07, 0x21,
	0xaa, 0x44, 0xb2, 0xb8, 0x67, 0xa8, 0xd1, 0x90, 0x25, 0x4c, 0x2f, 0x44, 0xca, 0xb2, 0x1b, 0x63,
	0x19, 0x3e, 0x38, 0x97, 0xa8, 0xd8, 0xad, 0x85, 0x08, 0x1f, 0x9c, 0x10, 0x0b, 0xd4, 0x16, 0x88,
	0x77, 0xf0, 0x38, 0x12, 0x3f, 0x50, 0x7e, 0xe4, 0xe6, 0x8c, 0x00, 0x0e, 0x5a, 0x46, 0x96, 0x59,
	0xcd, 0xf2, 0xb9, 0x4c, 0xa9, 0xcd, 0x2c, 0x2b, 0x98, 0x05, 0x1b, 0xca, 0xf3, 0x1e, 0xf1, 0xe5,
	0x27, 0x47, 0x3d, 0x1a, 0x73, 0x0a, 0x4f, 0xfa, 0x84, 0x6d, 0xa8, 0xc4, 0xf4, 0x8a, 0xca, 0xdc,
	0x80, 0x73, 0x0e, 0x47, 0x83, 0x9c, 0x0d, 0x48, 0xe3, 0x27, 0x3b, 0x83, 0xa7, 0xbd, 0xd1, 0xb6,
	0xa0, 0x15, 0xa7, 0x71, 0x61, 0x0d, 0x7a, 0x0f, 0x87, 0x21, 0x53, 0x77, 0x41, 0x8a, 0xe0, 0x79,
	0x7f, 0x93, 0x06, 0x20, 0x5f, 0x6b, 0xc9, 0xe2, 0x4a, 0xa3, 0x91, 0x36, 0x5f, 0x6b, 0x9a, 0x6c,
	0xae, 0x84, 0xa5, 0x85, 0x1f, 0xe0, 0x38, 0xc4, 0x9a, 0x74, 0x2a, 0xc5, 0xd6, 0x92, 0x75, 0x01,
	0x27, 0xbb, 0x38, 0x84, 0x98, 0xd1, 0xaa, 0xd0, 0x11, 0x95, 0x74, 0x8b, 0xda, 0x24, 0xec, 0x6f,
	0xe1, 0x51, 0x97, 0xd2, 0x33, 0x29, 0xaa, 0xd2, 0xe4, 0xe6, 0xef, 0xf4, 0x34, 0x08, 0x23, 0x11,
	0x9d, 0x77, 0x66, 0x22, 0x96, 0x30, 0xed, 0x82, 0x6d, 0x28, 0xc1, 0x07, 0xa7, 0xdb, 0x83, 0x9f,
	0x24, 0xa2, 0xe2, 0xe3, 0x9d, 0x09, 0x81, 0xec, 0x36, 0xf1, 0x0f, 0x62, 0x24, 0xa4, 0xdb, 0x85,
	0xa9, 0x90, 0xc6, 0x92, 0x76, 0x1b, 0xc6, 0x32, 0xce, 0xe1, 0xc8, 0x57, 0x4a, 0x24, 0x6c, 0xb8,
	0x12, 0x33, 0x73, 0xea, 0xf4, 0xb3, 0xbb, 0x61, 0xcd, 0x67, 0xbf, 0xfe, 0xec, 0x3b, 0x30, 0xf9,
	0xc4, 0x78, 0x1e, 0xd4, 0x5f, 0x0c, 0xe4, 0xde, 0xda, 0x8b, 0xef, 0x37, 0x45, 0x6f, 0xfe, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x4b, 0x8f, 0x41, 0x5b, 0x5c, 0x08, 0x00, 0x00,
}
