// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification_center.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/chai2010/qingcloud-go/pkg/service.pb/qingcloud_sdk_rule"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NotificationCenterServiceProperties struct {
	Zone             *string `protobuf:"bytes,1,opt,name=zone" json:"zone,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotificationCenterServiceProperties) Reset()         { *m = NotificationCenterServiceProperties{} }
func (m *NotificationCenterServiceProperties) String() string { return proto.CompactTextString(m) }
func (*NotificationCenterServiceProperties) ProtoMessage()    {}
func (*NotificationCenterServiceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor15, []int{0}
}

func (m *NotificationCenterServiceProperties) GetZone() string {
	if m != nil && m.Zone != nil {
		return *m.Zone
	}
	return ""
}

type DescribeNotificationCenterUserPostsInput struct {
	PostType         []string `protobuf:"bytes,1,rep,name=post_type,json=postType" json:"post_type,omitempty"`
	Status           []string `protobuf:"bytes,2,rep,name=status" json:"status,omitempty"`
	Offset           *int32   `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Limit            *int32   `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DescribeNotificationCenterUserPostsInput) Reset() {
	*m = DescribeNotificationCenterUserPostsInput{}
}
func (m *DescribeNotificationCenterUserPostsInput) String() string { return proto.CompactTextString(m) }
func (*DescribeNotificationCenterUserPostsInput) ProtoMessage()    {}
func (*DescribeNotificationCenterUserPostsInput) Descriptor() ([]byte, []int) {
	return fileDescriptor15, []int{1}
}

func (m *DescribeNotificationCenterUserPostsInput) GetPostType() []string {
	if m != nil {
		return m.PostType
	}
	return nil
}

func (m *DescribeNotificationCenterUserPostsInput) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeNotificationCenterUserPostsInput) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *DescribeNotificationCenterUserPostsInput) GetLimit() int32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

type DescribeNotificationCenterUserPostsOutput struct {
	Action                    *string                                                   `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	RetCode                   *int32                                                    `protobuf:"varint,2,opt,name=ret_code,json=retCode" json:"ret_code,omitempty"`
	Message                   *string                                                   `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	NotificationCenterPostSet []*DescribeNotificationCenterUserPostsOutput_ResponseItem `protobuf:"bytes,4,rep,name=notification_center_post_set,json=notificationCenterPostSet" json:"notification_center_post_set,omitempty"`
	TotalCount                *int32                                                    `protobuf:"varint,5,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	XXX_unrecognized          []byte                                                    `json:"-"`
}

func (m *DescribeNotificationCenterUserPostsOutput) Reset() {
	*m = DescribeNotificationCenterUserPostsOutput{}
}
func (m *DescribeNotificationCenterUserPostsOutput) String() string { return proto.CompactTextString(m) }
func (*DescribeNotificationCenterUserPostsOutput) ProtoMessage()    {}
func (*DescribeNotificationCenterUserPostsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor15, []int{2}
}

func (m *DescribeNotificationCenterUserPostsOutput) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *DescribeNotificationCenterUserPostsOutput) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *DescribeNotificationCenterUserPostsOutput) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *DescribeNotificationCenterUserPostsOutput) GetNotificationCenterPostSet() []*DescribeNotificationCenterUserPostsOutput_ResponseItem {
	if m != nil {
		return m.NotificationCenterPostSet
	}
	return nil
}

func (m *DescribeNotificationCenterUserPostsOutput) GetTotalCount() int32 {
	if m != nil && m.TotalCount != nil {
		return *m.TotalCount
	}
	return 0
}

type DescribeNotificationCenterUserPostsOutput_ResponseItem struct {
	NotificationCenterPostId *string                     `protobuf:"bytes,1,opt,name=notification_center_post_id,json=notificationCenterPostId" json:"notification_center_post_id,omitempty"`
	Status                   *string                     `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	LatestSnapshotTime       *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=latest_snapshot_time,json=latestSnapshotTime" json:"latest_snapshot_time,omitempty"`
	PostType                 *string                     `protobuf:"bytes,4,opt,name=post_type,json=postType" json:"post_type,omitempty"`
	Title                    *string                     `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Content                  *string                     `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized         []byte                      `json:"-"`
}

func (m *DescribeNotificationCenterUserPostsOutput_ResponseItem) Reset() {
	*m = DescribeNotificationCenterUserPostsOutput_ResponseItem{}
}
func (m *DescribeNotificationCenterUserPostsOutput_ResponseItem) String() string {
	return proto.CompactTextString(m)
}
func (*DescribeNotificationCenterUserPostsOutput_ResponseItem) ProtoMessage() {}
func (*DescribeNotificationCenterUserPostsOutput_ResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor15, []int{2, 0}
}

func (m *DescribeNotificationCenterUserPostsOutput_ResponseItem) GetNotificationCenterPostId() string {
	if m != nil && m.NotificationCenterPostId != nil {
		return *m.NotificationCenterPostId
	}
	return ""
}

func (m *DescribeNotificationCenterUserPostsOutput_ResponseItem) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *DescribeNotificationCenterUserPostsOutput_ResponseItem) GetLatestSnapshotTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LatestSnapshotTime
	}
	return nil
}

func (m *DescribeNotificationCenterUserPostsOutput_ResponseItem) GetPostType() string {
	if m != nil && m.PostType != nil {
		return *m.PostType
	}
	return ""
}

func (m *DescribeNotificationCenterUserPostsOutput_ResponseItem) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *DescribeNotificationCenterUserPostsOutput_ResponseItem) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*NotificationCenterServiceProperties)(nil), "service.NotificationCenterServiceProperties")
	proto.RegisterType((*DescribeNotificationCenterUserPostsInput)(nil), "service.DescribeNotificationCenterUserPostsInput")
	proto.RegisterType((*DescribeNotificationCenterUserPostsOutput)(nil), "service.DescribeNotificationCenterUserPostsOutput")
	proto.RegisterType((*DescribeNotificationCenterUserPostsOutput_ResponseItem)(nil), "service.DescribeNotificationCenterUserPostsOutput.ResponseItem")
}

func init() { proto.RegisterFile("notification_center.proto", fileDescriptor15) }

var fileDescriptor15 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x53, 0x27, 0x69, 0x36, 0x9c, 0x56, 0x51, 0xe5, 0xb8, 0x45, 0x8d, 0xd2, 0x4b, 0xb8,
	0xd8, 0x22, 0x37, 0x90, 0x2a, 0x0e, 0xe1, 0x12, 0x09, 0x41, 0x71, 0xca, 0x11, 0x59, 0xae, 0x3d,
	0x49, 0x56, 0xd8, 0x3b, 0x8b, 0x77, 0x8c, 0x28, 0xa7, 0x9e, 0x11, 0xfd, 0x0d, 0xfc, 0x46, 0xfe,
	0x01, 0xda, 0xb5, 0x03, 0x89, 0x9a, 0x4a, 0xe9, 0x25, 0xca, 0x9b, 0xcf, 0x37, 0xfb, 0x9e, 0xd9,
	0x50, 0x22, 0x89, 0xa5, 0x48, 0x13, 0x12, 0x28, 0xe3, 0x14, 0x24, 0x41, 0x19, 0xa8, 0x12, 0x09,
	0x79, 0x57, 0x43, 0xf9, 0x4d, 0xa4, 0xe0, 0x3f, 0xff, 0x2a, 0xe4, 0x2a, 0xcd, 0xb1, 0xca, 0x62,
	0x9d, 0x7d, 0x89, 0xcb, 0x2a, 0x87, 0xd0, 0xfc, 0xd4, 0x75, 0xfe, 0xf9, 0x0a, 0x71, 0x95, 0x43,
	0x68, 0xd1, 0x4d, 0xb5, 0x0c, 0x49, 0x14, 0xa0, 0x29, 0x29, 0x54, 0x5d, 0x30, 0x7e, 0xc5, 0x2e,
	0xde, 0x6f, 0x6d, 0x99, 0xd9, 0x25, 0x8b, 0x7a, 0xf8, 0x55, 0x89, 0x0a, 0x4a, 0x12, 0xa0, 0x39,
	0x67, 0xee, 0x0f, 0x94, 0xe0, 0x39, 0x23, 0x67, 0xd2, 0x8b, 0xec, 0xff, 0xf1, 0xbd, 0xc3, 0x26,
	0x6f, 0x41, 0xa7, 0xa5, 0xb8, 0x81, 0x87, 0x33, 0x3e, 0x69, 0x28, 0xaf, 0x50, 0x93, 0x9e, 0x4b,
	0x55, 0x11, 0x3f, 0x65, 0x3d, 0x85, 0x9a, 0x62, 0xba, 0x55, 0x66, 0xca, 0xd1, 0xa4, 0x17, 0x1d,
	0x9b, 0xc0, 0xf5, 0xad, 0x02, 0x7e, 0xc2, 0x3a, 0x9a, 0x12, 0xaa, 0xb4, 0xd7, 0xb2, 0x99, 0x06,
	0x99, 0x38, 0x2e, 0x97, 0x1a, 0xc8, 0x3b, 0x1a, 0x39, 0x93, 0x76, 0xd4, 0x20, 0x3e, 0x60, 0xed,
	0x5c, 0x14, 0x82, 0x3c, 0xd7, 0x86, 0x6b, 0x30, 0xfe, 0xed, 0xb2, 0x17, 0x07, 0xf0, 0xf9, 0x50,
	0x91, 0x21, 0x74, 0xc2, 0x3a, 0x49, 0x6a, 0xd2, 0xcd, 0x4d, 0x0d, 0xe2, 0x43, 0x76, 0x5c, 0x02,
	0xc5, 0x29, 0x66, 0xe0, 0xb5, 0xec, 0xf8, 0x6e, 0x09, 0x34, 0xc3, 0x0c, 0xb8, 0xc7, 0xba, 0x05,
	0x68, 0x9d, 0xac, 0xc0, 0xf2, 0xe9, 0x45, 0x1b, 0xc8, 0xef, 0x1c, 0x76, 0xb6, 0x47, 0xac, 0xd8,
	0x9e, 0x6c, 0xf8, 0xbb, 0xa3, 0xa3, 0x49, 0x7f, 0xfa, 0x26, 0x68, 0x64, 0x0b, 0x0e, 0xe6, 0x19,
	0x44, 0xa0, 0x15, 0x4a, 0x0d, 0x73, 0x82, 0x22, 0xda, 0x71, 0x44, 0x5d, 0x6f, 0x6a, 0x17, 0x40,
	0xfc, 0x9c, 0xf5, 0x09, 0x29, 0xc9, 0xe3, 0x14, 0x2b, 0x49, 0x5e, 0xdb, 0x52, 0x67, 0x36, 0x34,
	0x33, 0x11, 0xff, 0xae, 0xc5, 0x9e, 0x6d, 0x0f, 0xe3, 0x97, 0xec, 0xf4, 0x51, 0xce, 0x22, 0x6b,
	0x9e, 0xc5, 0xdb, 0xbf, 0x71, 0x9e, 0xed, 0x88, 0xe6, 0x6c, 0x89, 0xf6, 0x8e, 0x0d, 0xf2, 0x84,
	0xc0, 0x1c, 0x2e, 0x13, 0xa5, 0xd7, 0x48, 0xb1, 0x31, 0x9d, 0x7d, 0xb2, 0xfe, 0xd4, 0x0f, 0x6a,
	0x47, 0x06, 0x1b, 0x47, 0x06, 0xd7, 0x1b, 0x47, 0x46, 0xbc, 0xee, 0x5b, 0x34, 0x6d, 0x26, 0xb1,
	0xeb, 0x1b, 0xd7, 0x2e, 0xfa, 0xef, 0x9b, 0x01, 0x6b, 0x93, 0xa0, 0x1c, 0xec, 0xb5, 0xbd, 0xa8,
	0x06, 0x46, 0xa6, 0x14, 0x25, 0x81, 0x24, 0xaf, 0x53, 0xcb, 0xd4, 0xc0, 0xe9, 0x7d, 0x8b, 0x0d,
	0x1f, 0x75, 0x3b, 0xff, 0xe5, 0xb0, 0x8b, 0x03, 0x74, 0xe1, 0x2f, 0x9f, 0xa2, 0xa2, 0x75, 0xbf,
	0x3f, 0x7d, 0xba, 0xf0, 0x7e, 0xf2, 0xf3, 0x8f, 0xfb, 0x99, 0x5d, 0xae, 0x89, 0x94, 0x7e, 0x1d,
	0x86, 0x19, 0xa6, 0x3a, 0xf8, 0xf7, 0xb1, 0x07, 0x29, 0x16, 0x61, 0xa2, 0x44, 0xb8, 0x47, 0xc1,
	0x50, 0xc8, 0x0c, 0xbe, 0x07, 0x6b, 0x2a, 0x72, 0x7e, 0xf6, 0x51, 0xc8, 0xd5, 0xcc, 0x76, 0x3c,
	0xdc, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x67, 0x77, 0x7a, 0xef, 0x61, 0x04, 0x00, 0x00,
}
