# Copyright 2017 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a Apache
# license that can be found in the LICENSE file.

default:

clean:
	-rm *.pb.qcli.go
	-rm *.pb.qcli.go.txt
