# Copyright 2017 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a Apache
# license that can be found in the LICENSE file.

default:
	convert logo-01.png -resize 600x130 logo-01-600x130.png
	@echo "ok"

clean:
	@echo "ok"
