# Copyright 2017 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a Apache
# license that can be found in the LICENSE file.

default:
	convert logo-01.png -resize 600x130 logo-01-600x130.png
	convert logo-2018-01.png -resize 490x130 logo-2018-01-490x130.png
	@echo "ok"

crop:
	convert logo-01.png -crop 1150x304+0+0 logo-2018-01.png
	convert logo-02.png -crop 1150x304+0+0 logo-2018-02.png
	convert logo-03.png -crop 1150x304+0+0 logo-2018-03.png

clean:
	@echo "ok"
